// ============================================================================
// MYCALCULATORS TRADING SYSTEM — REGISTRY (PHASES 1 & 2 HARDENED)
// Completely isolated from lib/registry.ts. Zero external calculator dependencies.
// ============================================================================

import { TradingCategory, TradingCategoryMeta, TradingToolDefinition } from "./types";

export const TRADING_CATEGORIES: TradingCategoryMeta[] = [
  {
    id: "options",
    name: "Options Trading",
    tagline: "Options Mechanics",
    description: "Call/Put payoffs, Moneyness (ITM/ATM/OTM), intrinsic value, and breakevens.",
    badgeColor: "text-emerald-700",
  },
  {
    id: "options-strategies",
    name: "Options Strategy Tools",
    tagline: "Multi-Leg Simulators",
    description: "Bull Call Spread, Straddles, Strangles, and Iron Condors with SVG payoff curves.",
    badgeColor: "text-cyan-700",
  },
  {
    id: "futures-leverage",
    name: "Futures & Leverage",
    tagline: "Contract Derivatives",
    description: "Futures margin, leverage multipliers, notional exposure, and liquidation points.",
    badgeColor: "text-orange-700",
  },
  {
    id: "forex-crypto",
    name: "Forex & Crypto",
    tagline: "Currency & Decentralized",
    description: "Pip value calculators, lot sizing, and Dollar-Cost Averaging (DCA).",
    badgeColor: "text-indigo-700",
  },
  {
    id: "pnl-trades",
    name: "P&L & Trade Calculators",
    tagline: "Profit & Loss Modeling",
    description: "Intraday, delivery, multi-entry averages, and target profit calculators.",
    badgeColor: "text-steel",
  },
  {
    id: "risk-management",
    name: "Risk Management",
    tagline: "Capital Preservation",
    description: "Position sizing, risk-to-reward ratios, stop-loss limits, and ruin probability.",
    badgeColor: "text-amber-700",
  },
  {
    id: "charges-brokerage",
    name: "Brokerage & Trading Charges",
    tagline: "Regulatory Friction",
    description: "STT, Exchange Turnover, SEBI fees, Stamp Duty, and 18% GST analysis.",
    badgeColor: "text-rose-700",
  },
  {
    id: "technical-analysis",
    name: "Technical Analysis",
    tagline: "Market Indicators",
    description: "Pivots (CPR, Camarilla), Fibonacci retracements, and ATR volatility limits.",
    badgeColor: "text-navy/50",
  },
  {
    id: "portfolio-market",
    name: "Portfolio & Market Tools",
    tagline: "Asset Allocation",
    description: "Portfolio rebalancing, stock weights, XIRR returns, and sector exposures.",
    badgeColor: "text-navy/50",
  },
];

export const TRADING_TOOLS: TradingToolDefinition[] = [
  // --------------------------------------------------------------------------
  // 1. OPTIONS MECHANICS TOOLS
  // --------------------------------------------------------------------------
  {
    slug: "call-option-payoff-calculator",
    name: "Call Option Payoff Calculator",
    shortDescription: "Calculate intrinsic payoff, net profit/loss, and expiry breakeven for long and short call contracts.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["call option payoff calculator", "call option profit calculator", "long call payoff", "call option breakeven"],
    popular: true,
    status: "active",
    formulaDescription: "Long Call Net P&L = [max(Underlying Expiry Price - Strike Price, 0) - Premium] × Quantity × Multiplier",
    formulaVariables: [
      { symbol: "S", label: "Underlying market price at contract expiration" },
      { symbol: "K", label: "Selected call strike price" },
      { symbol: "P", label: "Option premium paid or received per unit" },
      { symbol: "Breakeven", label: "Strike Price + Option Premium (K + P)" },
    ],
    workedExample: {
      scenario: "Buying 1 lot (50 units) of Nifty 24,500 Call at ₹180 premium with underlying expiring at 24,800.",
      inputs: { "Strike Price": "₹24,500.00", "Option Premium": "₹180.00", "Expiry Spot Price": "₹24,800.00", "Contracts / Multiplier": "1 Lot × 50 Units" },
      result: "Gross Payoff: ₹300.00/unit | Net Profit: +₹6,000.00 (+66.67% ROI) | Breakeven: ₹24,680.00",
      explanation: "At 24,800, intrinsic value is ₹300 per unit (24,800 - 24,500). Subtracting the ₹180 premium paid leaves ₹120 net profit per unit. Multiplied by 50 units, total net profit is ₹6,000.00.",
    },
    assumptions: [
      "Calculation reflects deterministic intrinsic expiration value; pre-expiry time decay (theta) is not modeled.",
      "Regulatory brokerage, STT, and exchange turnover taxes are excluded from the mathematical payoff line.",
      "Contract quantity strictly equals number of lots multiplied by lot multiplier.",
    ],
    faqs: [
      { q: "What is a call option payoff?", a: "A call option payoff represents the cash realization of the option contract at expiration before deducting the initial premium paid to acquire it." },
      { q: "How is call option profit calculated?", a: "Profit equals intrinsic expiration value (Underlying Price minus Strike Price, minimum zero) minus the per-unit premium paid, multiplied by total units." },
      { q: "What is the breakeven price of a long call?", a: "The breakeven price equals the Strike Price plus the Premium Paid (K + P). At this price, intrinsic payoff exactly covers your premium outlay." },
      { q: "What happens if the underlying closes below the strike at expiry?", a: "The option expires out-of-the-money (OTM) with zero intrinsic value. Your loss is strictly capped at the initial premium paid." },
      { q: "What is the maximum risk on a long call?", a: "The maximum loss on a long call is 100% of the premium paid. It occurs if the underlying price expires at or below the strike price." },
      { q: "Is the risk on a short call unlimited?", a: "Yes. A naked short call has theoretically unlimited risk because there is no statutory ceiling on how high an asset price can climb." },
      { q: "Does this calculator include brokerage and statutory taxes?", a: "No. This tool models the mathematical derivatives payoff. To calculate exchange turnover, STT, and 18% GST friction, link to our Indian Brokerage Calculator." },
      { q: "Does the calculator model Black-Scholes pricing before expiry?", a: "No. This engine computes deterministic intrinsic expiration payoffs. Intraday implied volatility shifts prior to expiration require option Greeks." },
    ],
    relatedTradingSlugs: ["put-option-payoff-calculator", "bull-call-spread-calculator", "options-breakeven-calculator", "options-moneyness-calculator"],
  },
  {
    slug: "put-option-payoff-calculator",
    name: "Put Option Payoff Calculator",
    shortDescription: "Calculate put option intrinsic value, expiry profit/loss, and downside breakeven price.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["put option payoff calculator", "put option profit calculator", "long put payoff", "put breakeven"],
    popular: true,
    status: "active",
    formulaDescription: "Long Put Net P&L = [max(Strike Price - Underlying Expiry Price, 0) - Premium] × Quantity × Multiplier",
    formulaVariables: [
      { symbol: "K", label: "Selected put strike price" },
      { symbol: "S", label: "Underlying market price at contract expiration" },
      { symbol: "P", label: "Option premium paid or received per unit" },
      { symbol: "Breakeven", label: "Strike Price - Option Premium (K - P)" },
    ],
    workedExample: {
      scenario: "Buying 1 lot (50 units) of 24,500 Put at ₹180 premium with underlying expiring at 24,700.",
      inputs: { "Strike Price": "₹24,500.00", "Option Premium": "₹180.00", "Expiry Spot Price": "₹24,700.00", "Contracts / Multiplier": "1 Lot × 50 Units" },
      result: "Intrinsic Payoff: ₹0.00 | Net Loss: -₹9,000.00 (-100% Capital Loss) | Breakeven: ₹24,320.00",
      explanation: "Because the spot price at expiry (24,700) is above the strike (24,500), intrinsic value is ₹0. The entire premium of ₹180 per unit is forfeited, producing a net loss of -₹9,000.00 across 50 units. Maximum theoretical profit if the asset falls to zero is ₹12,16,000.00.",
    },
    assumptions: [
      "Calculation reflects deterministic expiration intrinsic payoff; early exercise adjustments are excluded.",
      "Maximum theoretical profit occurs if the underlying asset drops to absolute zero.",
      "Contract units equal lots multiplied by contract lot size.",
    ],
    faqs: [
      { q: "What is a put option payoff?", a: "A put option payoff is the value realized at expiration from the right to sell the underlying asset at the strike price." },
      { q: "How is long put profit calculated?", a: "Net profit equals intrinsic expiration value (Strike Price minus Underlying Price, minimum zero) minus the option premium paid, multiplied by total units." },
      { q: "What is the breakeven price for a put option?", a: "The breakeven price equals the Strike Price minus the Premium Paid (K - P). The underlying must decline below this level for profit." },
      { q: "What is the maximum profit for a long put?", a: "Maximum profit is capped at (Strike Price - Premium) × Quantity × Multiplier, which is achieved if the underlying falls to exactly zero." },
      { q: "What is the maximum loss on a long put?", a: "Your maximum risk is strictly limited to the premium paid to purchase the contract." },
      { q: "What happens when the underlying finishes above the strike at expiry?", a: "The put expires out-of-the-money (OTM) worthless, resulting in the total loss of the initial premium outlay." },
      { q: "What is the difference between intrinsic value and premium?", a: "Intrinsic value is the immediate tangible profit if exercised right now. Premium includes both intrinsic value and extrinsic time value." },
      { q: "Can a short put lose more money than a long put?", a: "Yes. A short put takes on substantial downside risk as the underlying crashes towards zero, offset only by the premium collected upfront." },
    ],
    relatedTradingSlugs: ["call-option-payoff-calculator", "bear-put-spread-calculator", "options-breakeven-calculator", "long-straddle-calculator"],
  },
  {
    slug: "options-moneyness-calculator",
    name: "Options Moneyness & Intrinsic Value Calculator",
    shortDescription: "Determine In-The-Money (ITM), At-The-Money (ATM), and Out-of-The-Money (OTM) status and time value.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["options moneyness calculator", "itm atm otm calculator", "intrinsic value calculator", "time value options"],
    status: "active",
    formulaDescription: "Call Intrinsic = max(Spot - Strike, 0) | Put Intrinsic = max(Strike - Spot, 0) | Time Value = Premium - Intrinsic",
    formulaVariables: [
      { symbol: "Intrinsic Value", label: "Immediate tangible value if exercised today" },
      { symbol: "Extrinsic / Time Value", label: "Speculative premium reflecting time until expiration" },
      { symbol: "Moneyness %", label: "Percentage distance of spot from strike [(Spot - Strike) / Strike × 100]" },
    ],
    workedExample: {
      scenario: "Nifty trading at 24,620 with a 24,500 Call option quoting at ₹210 market premium.",
      inputs: { "Underlying Spot": "₹24,620.00", "Strike Price": "₹24,500.00", "Option Premium": "₹210.00", "Option Type": "Call" },
      result: "Moneyness: ITM (In-The-Money) | Intrinsic Value: ₹120.00 | Extrinsic (Time) Value: ₹90.00",
      explanation: "Because spot exceeds strike by 120 points, the call has ₹120 in intrinsic value. The remaining ₹90 of the ₹210 premium represents extrinsic time decay value.",
    },
    assumptions: [
      "Moneyness boundaries consider options within ±0.25% of strike as At-The-Money (ATM).",
      "Time value is clamped to zero to prevent floating point noise if market premium dips below intrinsic parity.",
    ],
    faqs: [
      { q: "What does In-The-Money (ITM) mean?", a: "An option is ITM when it possesses positive intrinsic value. For a call, spot > strike; for a put, spot < strike." },
      { q: "What does At-The-Money (ATM) mean?", a: "An option is ATM when the underlying price is identical or exceptionally close to the strike price." },
      { q: "What does Out-of-The-Money (OTM) mean?", a: "An option is OTM when it has zero intrinsic value and consists entirely of extrinsic time value." },
      { q: "Can an option be ITM but still result in a net loss?", a: "Yes. If an ITM option's intrinsic value at expiry is less than the premium originally paid, you sustain a net loss on the trade." },
      { q: "How is extrinsic time value computed?", a: "Extrinsic value equals the total market option premium minus its calculated intrinsic value." },
      { q: "Why does time value decay towards zero?", a: "As expiration approaches, the probability of further favorable price movement diminishes, causing time value (theta) to decay to zero." },
      { q: "Does high moneyness guarantee trade profitability?", a: "No. Profitability requires the underlying to move beyond the breakeven threshold (strike plus or minus premium paid)." },
    ],
    relatedTradingSlugs: ["call-option-payoff-calculator", "options-breakeven-calculator", "bull-call-spread-calculator"],
  },
  {
    slug: "options-breakeven-calculator",
    name: "Options Breakeven Calculator",
    shortDescription: "Calculate the exact underlying price needed at expiry to break even on Calls and Puts.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["options breakeven calculator", "call breakeven", "put breakeven", "option break even point"],
    status: "active",
    formulaDescription: "Call Breakeven = Strike + Premium | Put Breakeven = Strike - Premium",
    formulaVariables: [
      { symbol: "Call BE", label: "Expiry price where Call intrinsic value equals premium paid" },
      { symbol: "Put BE", label: "Expiry price where Put intrinsic value equals premium paid" },
      { symbol: "Move Required", label: "Absolute point distance from current spot to breakeven" },
    ],
    workedExample: {
      scenario: "Nifty at 24,500; purchasing a 24,200 Strike Put at ₹140 premium.",
      inputs: { "Current Spot": "₹24,500.00", "Strike Price": "₹24,200.00", "Option Premium": "₹140.00" },
      result: "Breakeven Price: ₹24,060.00 | Move Required: -440.00 pts (-1.80%)",
      explanation: "The underlying must fall 440 points (300 points to strike plus 140 points to cover premium) to reach the ₹24,060 breakeven point at expiry.",
    },
    assumptions: [
      "Breakeven calculation represents expiration parity and excludes intermediary mark-to-market fluctuations.",
      "Statutory levies and broker commissions are excluded unless factored directly into entered premium.",
    ],
    faqs: [
      { q: "How is call breakeven calculated?", a: "Call breakeven is calculated as Strike Price plus Premium Paid. The underlying must expire above this price for net profit." },
      { q: "How is put breakeven calculated?", a: "Put breakeven is calculated as Strike Price minus Premium Paid. The underlying must expire below this price for net profit." },
      { q: "Does the breakeven point change if premium fluctuates before expiry?", a: "Yes. If you exit before expiration, your breakeven depends on the prevailing market premium rather than the expiry formula." },
      { q: "Why is breakeven different from the strike price?", a: "Because you paid an upfront premium to buy the contract, the asset must move past the strike by at least the premium amount to recover that cost." },
      { q: "Does this calculation include STT and brokerage?", a: "No. This formula computes pure derivatives breakeven. To cover broker fees, add estimated round-trip charges divided by quantity." },
      { q: "Is breakeven relevant for option sellers?", a: "Yes. For option sellers, the breakeven is the boundary beyond which their initial premium credit is fully wiped out by losses." },
    ],
    relatedTradingSlugs: ["call-option-payoff-calculator", "put-option-payoff-calculator", "bull-call-spread-calculator"],
  },

  // --------------------------------------------------------------------------
  // 2. OPTIONS STRATEGY SIMULATORS
  // --------------------------------------------------------------------------
  {
    slug: "bull-call-spread-calculator",
    name: "Bull Call Spread Calculator",
    shortDescription: "Simulate two-leg debit call spread payoffs, maximum profit caps, and net debit risk with SVG charts.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["bull call spread calculator", "call spread calculator", "vertical debit spread", "options spread payoff"],
    popular: true,
    status: "active",
    formulaDescription: "Max Profit = (Upper Strike - Lower Strike - Net Debit) × Qty | Max Loss = Net Debit × Qty | BE = Lower Strike + Net Debit",
    formulaVariables: [
      { symbol: "Lower Strike", label: "Purchased Long Call strike price" },
      { symbol: "Upper Strike", label: "Sold Short Call strike price" },
      { symbol: "Net Debit", label: "Lower Call Premium Paid - Upper Call Premium Received" },
      { symbol: "Spread Width", label: "Upper Strike - Lower Strike" },
    ],
    workedExample: {
      scenario: "Buying 24,500 Call at ₹190 and selling 25,000 Call at ₹60 with 50 units (1 lot Nifty).",
      inputs: { "Lower Strike": "₹24,500.00", "Upper Strike": "₹25,000.00", "Net Debit Paid": "₹130.00 (₹6,500 total)", "Units": "50" },
      result: "Max Profit: +₹18,500.00 | Max Loss: -₹6,500.00 | Breakeven: ₹24,630.00 | R:R: 1 : 2.85",
      explanation: "The spread width is 500 points. Net debit is 130 points. Maximum profit is capped at 370 points (500 - 130) = ₹18,500 on 50 units. Maximum loss is the ₹6,500 net debit.",
    },
    assumptions: [
      "Both option legs share the exact same underlying asset and expiration date.",
      "Early assignment risk on the short call prior to expiration is not factored into the terminal curve.",
    ],
    faqs: [
      { q: "What is a bull call spread?", a: "A bull call spread is a defined-risk, moderately bullish strategy created by buying an in-the-money or at-the-money call and selling an out-of-the-money call." },
      { q: "What is the maximum profit on a bull call spread?", a: "Maximum profit equals (Difference between strikes minus Net Debit paid) multiplied by contract quantity." },
      { q: "What is the maximum loss?", a: "Maximum loss is strictly capped at the net debit paid upfront to establish the two legs." },
      { q: "How is the breakeven point calculated?", a: "The breakeven price equals the lower strike price plus the net debit per unit paid." },
      { q: "What happens if the underlying expires between the strikes?", a: "The short call expires worthless while the long call maintains partial intrinsic value, reducing loss or yielding modest profit." },
      { q: "Why use a spread instead of a naked long call?", a: "Selling the higher call finances part of the long call's cost and reduces time decay (theta) risk, though it caps your maximum upside." },
      { q: "Can a bull call spread lose more than the initial debit?", a: "No. Because both legs are secured against each other, the maximum loss can never exceed the initial net debit paid." },
    ],
    relatedTradingSlugs: ["bear-put-spread-calculator", "long-straddle-calculator", "iron-condor-calculator"],
  },
  {
    slug: "bear-put-spread-calculator",
    name: "Bear Put Spread Calculator",
    shortDescription: "Simulate vertical debit put spread returns, capped downside profit, and breakeven levels.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["bear put spread calculator", "debit put spread", "bearish options spread"],
    popular: true,
    status: "active",
    formulaDescription: "Max Profit = (Upper Strike - Lower Strike - Net Debit) × Qty | Max Loss = Net Debit × Qty | BE = Upper Strike - Net Debit",
    formulaVariables: [
      { symbol: "Upper Strike", label: "Purchased Long Put strike price" },
      { symbol: "Lower Strike", label: "Sold Short Put strike price" },
      { symbol: "Net Debit", label: "Upper Put Premium Paid - Lower Put Premium Received" },
    ],
    workedExample: {
      scenario: "Buying 24,500 Put at ₹160 and selling 24,000 Put at ₹45 across 50 units.",
      inputs: { "Upper Put": "₹24,500.00", "Lower Put": "₹24,000.00", "Net Debit Paid": "₹115.00 (₹5,750 total)", "Units": "50" },
      result: "Max Profit: +₹19,250.00 | Max Loss: -₹5,750.00 | Breakeven: ₹24,385.00 | R:R: 1 : 3.35",
      explanation: "Spread width is 500 points. Net debit is 115 points. Max upside is capped at 385 points (₹19,250 on 50 units) if underlying closes at or below 24,000 at expiry.",
    },
    assumptions: [
      "Both legs share identical expiration dates and underlying contract roots.",
      "Execution slippage during simultaneous leg entry is not included.",
    ],
    faqs: [
      { q: "What is a bear put spread?", a: "A bear put spread is a defined-risk, moderately bearish strategy formed by buying a higher-strike put and selling a lower-strike put." },
      { q: "What is the maximum profit?", a: "Maximum profit equals the difference between the two strike prices minus the net debit paid, multiplied by total units." },
      { q: "What is the maximum loss?", a: "Maximum loss is limited to the net premium paid to initiate the position." },
      { q: "How is the breakeven price calculated?", a: "Breakeven equals the higher (long put) strike price minus the net debit per unit." },
      { q: "Why not simply buy a naked put?", a: "A spread significantly reduces the cash outlay and offsets negative theta decay, though it caps gains beyond the lower strike." },
      { q: "What happens if the underlying rises strongly?", a: "Both puts expire out-of-the-money worthless. Your total loss remains strictly capped at the initial net debit." },
    ],
    relatedTradingSlugs: ["bull-call-spread-calculator", "long-straddle-calculator", "iron-condor-calculator"],
  },
  {
    slug: "long-straddle-calculator",
    name: "Long Straddle Payoff Calculator",
    shortDescription: "Calculate dual breakevens and unlimited volatility expansion payoffs on ATM Call + Put combinations.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["long straddle calculator", "straddle options calculator", "volatility breakout options"],
    popular: true,
    status: "active",
    formulaDescription: "Lower BE = Strike - Combined Premium | Upper BE = Strike + Combined Premium | Max Loss = Combined Premium",
    formulaVariables: [
      { symbol: "Strike Price", label: "Shared identical strike for both Call and Put" },
      { symbol: "Combined Premium", label: "Call Premium Paid + Put Premium Paid" },
      { symbol: "Profit Zone", label: "Below Lower BE or Above Upper BE" },
    ],
    workedExample: {
      scenario: "Buying 24,500 Call at ₹180 and 24,500 Put at ₹170 with 50 units.",
      inputs: { "Strike Price": "₹24,500.00", "Call Premium": "₹180.00", "Put Premium": "₹170.00", "Total Outlay": "₹350.00 (₹17,500 total)" },
      result: "Lower BE: ₹24,150.00 | Upper BE: ₹24,850.00 | Max Loss: -₹17,500.00 | Max Profit: Unlimited",
      explanation: "Combined cost is ₹350 per unit. The trade generates net profit if the underlying finishes either below 24,150 or above 24,850 at expiration.",
    },
    assumptions: [
      "Both the call and put legs must be opened at the exact same strike price and expiration date.",
      "Implied volatility crush post-event (e.g. earnings/elections) severely affects returns if held prior to expiry.",
    ],
    faqs: [
      { q: "What is a long straddle?", a: "A long straddle is a market-neutral, high-volatility strategy created by purchasing an equal number of calls and puts at the exact same strike and expiration." },
      { q: "What is the maximum risk on a long straddle?", a: "The maximum loss is 100% of the combined premium paid for both legs. It occurs if the price closes exactly at the strike on expiry." },
      { q: "How are the dual breakeven points calculated?", a: "Lower Breakeven = Strike Price - Total Premium; Upper Breakeven = Strike Price + Total Premium." },
      { q: "When should a trader execute a long straddle?", a: "When expecting explosive market volatility before or during a major event, regardless of which direction the price moves." },
      { q: "What is the biggest risk with a straddle?", a: "Theta (time decay) and volatility crush. If the price moves sideways, both legs decay rapidly towards zero." },
      { q: "Can a long straddle have unlimited profit?", a: "Yes, on the upside there is no mathematical ceiling, while on the downside profit is capped only if the asset drops to zero." },
    ],
    relatedTradingSlugs: ["iron-condor-calculator", "bull-call-spread-calculator", "call-option-payoff-calculator"],
  },
  {
    slug: "iron-condor-calculator",
    name: "Iron Condor Strategy Calculator",
    shortDescription: "Model 4-leg market-neutral credit condors with defined risk wings, dual breakevens, and net credit collection.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["iron condor calculator", "4 leg options strategy", "range bound options calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Max Profit = Net Credit | Max Loss = Wing Width - Net Credit | Lower BE = Put Sell K - Net Credit | Upper BE = Call Sell K + Net Credit",
    formulaVariables: [
      { symbol: "Wing Width", label: "Distance between long and short strikes (K_sell - K_buy)" },
      { symbol: "Net Credit", label: "Total premiums received minus total premiums paid" },
      { symbol: "Profit Zone", label: "Between Lower Breakeven and Upper Breakeven" },
    ],
    workedExample: {
      scenario: "Sell 24,100 Put (₹90) & 24,800 Call (₹85); Buy 23,800 Put (₹30) & 25,100 Call (₹25) on 50 units.",
      inputs: { "Wing Width": "300 pts", "Net Credit": "₹110.00/unit (₹5,500 total)", "Units": "50" },
      result: "Max Profit: +₹5,500.00 | Max Loss: -₹9,500.00 | Profit Zone: ₹23,990.00 to ₹24,910.00",
      explanation: "Maximum profit of ₹5,500 is retained if underlying finishes between 24,100 and 24,800. Maximum loss is capped at ₹9,500 (300 wing width minus 110 credit = 190 pts × 50 units).",
    },
    assumptions: [
      "Wing widths on both put and call sides are assumed symmetrical unless customized in the editor.",
      "Early assignment on short legs is not accounted for in terminal expiration modeling.",
    ],
    faqs: [
      { q: "What is an iron condor?", a: "An iron condor is a defined-risk, non-directional option strategy formed by selling an out-of-the-money put spread and an out-of-the-money call spread." },
      { q: "What is the maximum profit?", a: "Maximum profit is strictly limited to the net premium credit collected when entering all four legs." },
      { q: "What is the maximum loss on an iron condor?", a: "Maximum loss equals the wing width (distance between adjacent long and short strikes) minus the net credit received, multiplied by contract units." },
      { q: "How are the two breakeven points calculated?", a: "Lower BE = Short Put Strike minus Net Credit; Upper BE = Short Call Strike plus Net Credit." },
      { q: "What market condition favors an iron condor?", a: "A low-volatility, range-bound market where the underlying is expected to consolidate between the short strikes." },
      { q: "What happens if the market breaches one of the wings?", a: "The outer long option acts as a protective firewall, capping your loss at the defined maximum threshold." },
    ],
    relatedTradingSlugs: ["long-straddle-calculator", "bull-call-spread-calculator", "bear-put-spread-calculator"],
  },

  // --------------------------------------------------------------------------
  // 3. FUTURES & LEVERAGE TOOLS
  // --------------------------------------------------------------------------
  {
    slug: "futures-pnl-calculator",
    name: "Futures P&L Calculator",
    shortDescription: "Calculate futures trade profit, points gained, notional exposure, and return on deposited margin.",
    category: "futures-leverage",
    renderer: "futures",
    keywords: ["futures pnl calculator", "nifty futures calculator", "futures profit calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Long Futures P&L = (Exit Price - Entry Price) × Quantity Lots × Lot Size",
    formulaVariables: [
      { symbol: "Notional Value", label: "Entry Price × Total Units" },
      { symbol: "Points Move", label: "Exit Price - Entry Price (Long) or Entry Price - Exit Price (Short)" },
      { symbol: "Return on Margin", label: "(Net P&L / Initial Margin Deposited) × 100" },
    ],
    workedExample: {
      scenario: "Buying 2 Lots of Nifty Futures (100 units) at 24,500 and exiting at 24,750.",
      inputs: { "Entry Price": "₹24,500.00", "Exit Price": "₹24,750.00", "Lots": "2", "Lot Size": "50" },
      result: "Points Captured: +250.00 pts | Realized P&L: +₹25,000.00 | Notional: ₹24,50,000.00",
      explanation: "A 250-point gain across 100 contract units yields ₹25,000 gross gain on a ₹24.50 Lakh notional contract value.",
    },
    assumptions: [
      "Calculations evaluate gross trade P&L; statutory exchange charges and STT are computed separately.",
      "Contract multipliers must be set in accordance with exchange specifications (e.g. 50 for Nifty).",
    ],
    faqs: [
      { q: "How is futures P&L calculated?", a: "Futures P&L is calculated by multiplying the points gained or lost by the total number of underlying units (Lots × Lot Size)." },
      { q: "What is contract notional value?", a: "Notional value is the total underlying cash value controlled by the futures contract (Price × Lot Size × Lots)." },
      { q: "How does return on margin differ from return on notional value?", a: "Because futures are traded on margin, a 1% move in notional value can yield an 8% to 15% return on your deposited margin." },
      { q: "Can a short futures position generate profit?", a: "Yes. In a short futures position, you profit when the exit price is lower than your entry price." },
      { q: "Are mark-to-market (MTM) settlements modeled here?", a: "This calculator determines total realized P&L between entry and exit rather than daily interim cash debits and credits." },
      { q: "Does this calculator deduct brokerage fees?", a: "No. For an exact net deduction of exchange turnover, SEBI fees, and GST, consult our Indian Brokerage Calculator." },
    ],
    relatedTradingSlugs: ["futures-margin-calculator", "liquidation-price-calculator", "intraday-pnl-calculator"],
  },
  {
    slug: "futures-margin-calculator",
    name: "Futures Margin & Leverage Calculator",
    shortDescription: "Determine initial SPAN + Exposure margin requirements, effective leverage, and margin utilization.",
    category: "futures-leverage",
    renderer: "futures",
    keywords: ["futures margin calculator", "span margin calculator", "derivatives leverage calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Initial Margin = Notional Value × Margin Rate % | Embedded Leverage = 100 / Margin Rate %",
    formulaVariables: [
      { symbol: "SPAN + Exposure Margin", label: "Mandatory regulatory capital deposit required to hold contracts" },
      { symbol: "Effective Leverage", label: "Notional Exposure / Margin Capital Deposited" },
      { symbol: "Margin Utilization", label: "(Margin Required / Total Account Equity) × 100" },
    ],
    workedExample: {
      scenario: "Contract price ₹24,500, lot size 50, 2 lots traded at 12% statutory margin requirement with ₹4,00,000 account equity.",
      inputs: { "Notional Value": "₹24,50,000.00", "Margin Rate": "12.0%", "Account Equity": "₹4,00,000.00" },
      result: "Margin Required: ₹2,94,000.00 | Embedded Leverage: 8.3x | Margin Utilization: 73.5%",
      explanation: "A ₹2,94,000 deposit controls ₹24.50 Lakh in notional exposure. Account utilization is 73.5%, leaving ₹1,06,000 in free usable buffer.",
    },
    assumptions: [
      "Margin rate reflects combined SPAN and exposure margin percentages prescribed by clearing corporations.",
      "Intraday margin multipliers (MIS) can reduce margin requirements depending on your broker.",
    ],
    faqs: [
      { q: "What is initial margin in futures?", a: "Initial margin is the minimum capital required in your trading account to initiate and carry an open futures position." },
      { q: "What is SPAN margin?", a: "SPAN (Standard Portfolio Analysis of Risk) margin is a standardized algorithm used by exchanges to calculate portfolio risk based on worst-case scenarios." },
      { q: "How is effective leverage calculated?", a: "Effective leverage equals the total notional value of the contract divided by the margin deposited (e.g. ₹24.5L / ₹2.94L = 8.33x)." },
      { q: "What is a dangerous margin utilization percentage?", a: "Utilization above 75% leaves minimal cushion. Adverse market gaps can trigger sudden margin calls or automatic squared-off liquidations." },
      { q: "Can margin requirements change while holding an overnight position?", a: "Yes. Exchanges can hike margin percentages during periods of extreme market volatility." },
      { q: "What is free usable equity?", a: "Free equity is your total account balance minus the margin locked into active derivative contracts." },
    ],
    relatedTradingSlugs: ["futures-pnl-calculator", "liquidation-price-calculator", "position-size-calculator"],
  },
  {
    slug: "liquidation-price-calculator",
    name: "Estimated Liquidation Price Calculator",
    shortDescription: "Estimate liquidation price based on leverage multiplier and maintenance margin buffer.",
    category: "futures-leverage",
    renderer: "futures",
    keywords: ["liquidation price calculator", "crypto liquidation calculator", "margin liquidation"],
    status: "active",
    formulaDescription: "Long Liq = Entry × [1 - (1 / Leverage) + Maintenance Margin %] | Short Liq = Entry × [1 + (1 / Leverage) - Maintenance Margin %]",
    formulaVariables: [
      { symbol: "Entry Price", label: "Initial position entry level" },
      { symbol: "Leverage Multiplier", label: "Ratio of borrowed funds to initial margin deposit" },
      { symbol: "Maintenance Margin", label: "Minimum equity threshold before broker initiates liquidation" },
    ],
    workedExample: {
      scenario: "Long position entered at ₹24,500 with 10x leverage and 0.5% maintenance margin requirement.",
      inputs: { "Entry Price": "₹24,500.00", "Leverage": "10x", "Maintenance Buffer": "0.5%" },
      result: "Estimated Liquidation Price: ₹22,172.50 | Adverse Move to Liquidation: 9.50%",
      explanation: "With 10x leverage (10% margin), a 9.50% drop consumes your equity buffer down to the 0.5% maintenance threshold, triggering mandatory liquidation.",
    },
    assumptions: [
      "Model assumes isolated margin rules. Cross-margin account balances can buffer liquidation points.",
      "Funding fees, interest costs, and execution market slippage are not factored into the baseline formula.",
    ],
    faqs: [
      { q: "What is a liquidation price?", a: "The liquidation price is the market price at which your losses deplete your margin buffer, forcing the broker to close the position." },
      { q: "Why is this labeled an 'Estimated' liquidation price?", a: "Actual liquidation varies across exchanges depending on bankruptcy fees, funding rates, index vs mark price, and queue priority." },
      { q: "How does higher leverage affect the liquidation price?", a: "Higher leverage moves the liquidation price significantly closer to your entry, meaning even small market fluctuations can wipe out the trade." },
      { q: "How can I prevent forced liquidation?", a: "Use strict stop-loss orders well ahead of the liquidation threshold, lower your leverage multiplier, or add margin to your buffer." },
      { q: "What is maintenance margin?", a: "Maintenance margin is the bare minimum percentage of equity required to keep a leveraged contract active." },
      { q: "Does isolated margin differ from cross margin?", a: "Yes. Isolated margin risks only the capital allocated to that specific trade, while cross margin risks your entire account balance." },
    ],
    relatedTradingSlugs: ["futures-margin-calculator", "position-size-calculator", "risk-reward-calculator"],
  },

  // --------------------------------------------------------------------------
  // 4. FOREX & CRYPTO TOOLS
  // --------------------------------------------------------------------------
  {
    slug: "forex-pip-value-calculator",
    name: "Forex Pip Value Calculator",
    shortDescription: "Calculate cash value per pip across standard, mini, and micro lots in local account currency.",
    category: "forex-crypto",
    renderer: "forex",
    keywords: ["forex pip value calculator", "pip calculator", "currency pip value in inr"],
    popular: true,
    status: "active",
    formulaDescription: "Pip Value = Lots × Contract Units × Pip Decimal Size × Exchange Rate to Account Currency",
    formulaVariables: [
      { symbol: "Standard Lot", label: "100,000 units of the base currency" },
      { symbol: "Pip Decimal Size", label: "0.0001 for standard currency pairs; 0.01 for JPY pairs" },
      { symbol: "FX Conversion Rate", label: "Exchange rate converting quote currency into account base currency" },
    ],
    workedExample: {
      scenario: "1 Standard Lot (100,000 units) on EUR/USD (0.0001 pip) with USD/INR conversion rate at 85.50.",
      inputs: { "Lots Traded": "1.0 Lot", "Contract Size": "100,000 Units", "Pip Size": "0.0001", "USD/INR Rate": "85.50" },
      result: "Pip Value: $10.00 / pip | Local Value: ₹855.00 / pip",
      explanation: "A 1-pip move on 1 standard lot produces a $10 quote currency variance. Converting at 85.50 yields ₹855.00 INR per pip.",
    },
    assumptions: [
      "Calculation reflects pure pip valuation. Broker spreads and liquidity slippage are excluded.",
      "Account currency conversion uses the user-entered static exchange conversion rate.",
    ],
    faqs: [
      { q: "What is a pip in Forex trading?", a: "A pip (percentage in point) is the standard unit of measurement representing the smallest price move in a currency pair, usually 0.0001." },
      { q: "Why is the pip size different for Japanese Yen (JPY) pairs?", a: "JPY pairs are quoted to two decimal places, meaning a pip equals 0.01 rather than 0.0001." },
      { q: "What is the pip value of 1 standard lot on EUR/USD?", a: "For 1 standard lot (100,000 units), 1 pip equals exactly $10 USD in quote currency." },
      { q: "What is a mini lot and micro lot?", a: "A mini lot is 10,000 units ($1/pip), and a micro lot is 1,000 units ($0.10/pip)." },
      { q: "Why does the exchange rate affect pip value?", a: "If your account currency differs from the pair's quote currency, the dollar pip value must be converted using the active exchange rate." },
      { q: "How do I use pip value for position sizing?", a: "Divide your maximum allowable rupee risk by (Stop-loss distance in pips multiplied by pip value per lot)." },
    ],
    relatedTradingSlugs: ["forex-position-size-calculator", "position-size-calculator"],
  },
  {
    slug: "forex-position-size-calculator",
    name: "Forex Lot Size & Risk Calculator",
    shortDescription: "Determine exact lot sizing to ensure risk remains fixed to 1% of account capital.",
    category: "forex-crypto",
    renderer: "forex",
    keywords: ["forex position size calculator", "forex lot size calculator", "forex risk calculator"],
    status: "active",
    formulaDescription: "Allowable Lots = (Account Capital × Risk %) / (Stop Loss Pips × Pip Value Per Standard Lot)",
    formulaVariables: [
      { symbol: "Account Capital", label: "Total active trading equity balance" },
      { symbol: "Risk %", label: "Maximum allowable risk percentage per trade (1-2%)" },
      { symbol: "Stop Loss Pips", label: "Distance from entry fill to protective stop in pips" },
    ],
    workedExample: {
      scenario: "₹1,00,000 capital risking 1.5% with a 25-pip stop loss on USD/INR (₹855 pip value per standard lot).",
      inputs: { "Account Capital": "₹1,00,000.00", "Risk %": "1.5%", "Stop Loss": "25 Pips", "Pip Value": "₹855.00/lot" },
      result: "Allowable Lot Size: 0.07 Standard Lots (7 Micro Lots) | Total Risk Capped: ₹1,500.00",
      explanation: "Allowable loss is ₹1,500. A 25-pip move on 1 lot risks ₹21,375. Dividing ₹1,500 by ₹21,375 yields an exact allocation of 0.07 lots.",
    },
    assumptions: [
      "Calculation assumes uniform execution at the stop-loss price without adverse weekend price gaps.",
      "Pip value per standard lot must be accurately configured in the local account currency.",
    ],
    faqs: [
      { q: "How is Forex position size calculated?", a: "Position size is calculated by dividing your cash risk budget by (Stop Loss in pips multiplied by Pip value per standard lot)." },
      { q: "Why is position sizing vital in currency markets?", a: "High leverage in Forex can lead to rapid capital wipeout unless position size is calculated strictly from stop-loss distance." },
      { q: "What happens if my calculated lot size is smaller than 0.01?", a: "Most brokers require a minimum order size of 0.01 micro lots. If your risk permits less, you must widen your stop or deposit additional capital." },
      { q: "Does this formula change for mini or micro accounts?", a: "No. The formula calculates total lot units; 0.07 standard lots simply equals 0.7 mini lots or 7 micro lots." },
      { q: "Should I include broker commissions in risk sizing?", a: "Yes. You can add expected commission costs directly to the stop-loss distance to ensure total friction is covered." },
    ],
    relatedTradingSlugs: ["forex-pip-value-calculator", "position-size-calculator", "risk-reward-calculator"],
  },
  {
    slug: "crypto-dca-calculator",
    name: "Crypto DCA (Dollar-Cost Averaging) Calculator",
    shortDescription: "Calculate weighted average buy price and accumulated coin holdings across recurring purchase orders.",
    category: "forex-crypto",
    renderer: "crypto",
    keywords: ["crypto dca calculator", "dollar cost average bitcoin", "crypto average buy price"],
    popular: true,
    status: "active",
    formulaDescription: "DCA Average Price = Total Fiat Capital Invested / Total Coin Tokens Acquired",
    formulaVariables: [
      { symbol: "Total Invested", label: "Sum of all recurring fiat purchase amounts [Σ Cash]" },
      { symbol: "Total Tokens", label: "Sum of coin quantities acquired across all price tiers [Σ (Cash / Price)]" },
      { symbol: "Effective Basis", label: "Volume-weighted average procurement cost per unit" },
    ],
    workedExample: {
      scenario: "Buying ₹50,000 of Bitcoin at ₹55,00,000 and another ₹50,000 at ₹50,00,000.",
      inputs: { "Order 1": "₹50,000 @ ₹55,00,000", "Order 2": "₹50,00,000 @ ₹50,00,000" },
      result: "Total Invested: ₹1,00,000.00 | Total Coins: 0.019091 BTC | DCA Average Price: ₹52,380.95",
      explanation: "Investing equal cash amounts acquires more coins when prices are lower, pulling the volume-weighted average price (₹52,380.95) below the arithmetic midpoint (₹52,500.00).",
    },
    assumptions: [
      "Prices and order values represent user-entered historical purchases; live exchange feeds are not utilized.",
      "Trading fees, gas costs, and exchange withdrawal levies are excluded from basic coin quantity calculations.",
    ],
    faqs: [
      { q: "What is Dollar-Cost Averaging (DCA)?", a: "DCA is an investment strategy where you invest a fixed amount of money at regular intervals, regardless of the asset's price." },
      { q: "How does DCA lower your average purchase price?", a: "Because you invest fixed cash amounts, you automatically buy more coins when prices are low and fewer when prices are high." },
      { q: "Does DCA guarantee profit in cryptocurrency?", a: "No. If the underlying cryptocurrency continues to decline indefinitely, DCA simply averages down your cost basis without preventing losses." },
      { q: "Why is the DCA average lower than the simple mathematical average?", a: "DCA is volume-weighted. More units are accumulated at lower price tiers, which pulls the weighted average downwards." },
      { q: "How often should I DCA?", a: "Common schedules include daily, weekly, or monthly intervals, often aligned with personal cash flow and market cycles." },
      { q: "How do exchange fees impact DCA?", a: "Frequent small orders can accumulate trading and network withdrawal fees; ensure transaction charges do not consume your margin." },
    ],
    relatedTradingSlugs: ["average-price-calculator", "average-down-calculator", "position-size-calculator"],
  },

  // --------------------------------------------------------------------------
  // 5. PHASE 1 HARDENED TOOLS (PRESERVED)
  // --------------------------------------------------------------------------
  {
    slug: "intraday-pnl-calculator",
    name: "Intraday P&L Calculator",
    shortDescription: "Calculate gross & net profit/loss, point movements, and trade return percentage for day trading.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["intraday pnl calculator", "day trading profit calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Long P&L = (Exit - Entry) × Qty - Charges | Short P&L = (Entry - Exit) × Qty - Charges",
    workedExample: {
      scenario: "Buying 100 shares at ₹500 and exiting at ₹540 with ₹20 total charges.",
      inputs: { "Entry": "₹500.00", "Exit": "₹540.00", "Quantity": "100" },
      result: "Gross P&L: +₹4,000.00 | Net P&L: +₹3,980.00",
      explanation: "A 40-point move generates ₹4,000 gross. After ₹20 fees, net profit is ₹3,980.",
    },
    relatedTradingSlugs: ["position-size-calculator", "brokerage-charges-calculator"],
  },
  {
    slug: "equity-pnl-calculator",
    name: "Equity Delivery P&L Calculator",
    shortDescription: "Calculate investment profit, cost basis, sale value, and capital gains for delivery holdings.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["equity delivery calculator", "cnc pnl calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Net Return = (Sell Price × Quantity) - (Buy Price × Quantity) - Charges",
    workedExample: {
      scenario: "Buying 50 shares at ₹1,000 and selling at ₹1,200 after holding with ₹100 charges.",
      inputs: { "Buy Price": "₹1,000.00", "Sell Price": "₹1,200.00", "Quantity": "50" },
      result: "Cost Basis: ₹50,000 | Sale Value: ₹60,000 | Net Profit: +₹9,900.00",
      explanation: "Capital appreciated by ₹10,000. Deducting ₹100 leaves ₹9,900 net gain.",
    },
    relatedTradingSlugs: ["intraday-pnl-calculator", "average-price-calculator"],
  },
  {
    slug: "target-profit-calculator",
    name: "Target Profit Price Calculator",
    shortDescription: "Determine the exact target exit price needed to hit your rupee profit goal.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["target profit calculator", "target price calculator"],
    status: "active",
    formulaDescription: "Long Target Exit = Entry Price + [(Desired Profit + Charges) / Quantity]",
    workedExample: {
      scenario: "Buying 200 shares at ₹250 targeting a net ₹5,000 profit with ₹50 estimated charges.",
      inputs: { "Entry Price": "₹250.00", "Quantity": "200", "Target Profit": "₹5,000.00" },
      result: "Required Target Price: ₹275.25 (+25.25 points move needed)",
      explanation: "Exit at ₹275.25 secures ₹5,050 gross, yielding ₹5,000 net after fees.",
    },
    relatedTradingSlugs: ["intraday-pnl-calculator", "risk-reward-calculator"],
  },
  {
    slug: "stop-loss-calculator",
    name: "Stop-Loss Price Calculator",
    shortDescription: "Calculate exact stop-loss price corresponding to your maximum allowable rupee risk.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["stop loss price calculator", "sl price calculator"],
    status: "active",
    formulaDescription: "Long Stop-Loss = Entry Price - [(Capital × Risk %) / Quantity]",
    workedExample: {
      scenario: "₹1,00,000 capital risking 1% on 100 shares bought at ₹400.",
      inputs: { "Capital": "₹1,00,000", "Risk %": "1.0%", "Quantity": "100", "Entry": "₹400.00" },
      result: "Max Risk: ₹1,000 | Stop-Loss Price: ₹390.00",
      explanation: "Dividing allowable ₹1,000 loss by 100 shares permits a 10-point stop at ₹390.",
    },
    relatedTradingSlugs: ["position-size-calculator", "risk-reward-calculator"],
  },
  {
    slug: "average-price-calculator",
    name: "Multi-Entry Average Price Calculator",
    shortDescription: "Calculate weighted average purchase price and total investment across multiple trade legs.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["average price calculator", "stock average calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Weighted Average Price = Σ(Price × Quantity) / Σ Quantity",
    workedExample: {
      scenario: "Bought 100 shares at ₹100 and 200 shares at ₹85.",
      inputs: { "Leg 1": "100 @ ₹100", "Leg 2": "200 @ ₹85" },
      result: "Total Quantity: 300 | Invested: ₹27,000 | Weighted Avg: ₹90.00",
      explanation: "Total capital ₹27,000 divided by 300 shares equals ₹90.00 average cost.",
    },
    relatedTradingSlugs: ["average-down-calculator", "equity-pnl-calculator"],
  },
  {
    slug: "average-down-calculator",
    name: "Average Down Calculator",
    shortDescription: "Calculate new blended cost basis and additional shares needed to lower your average price.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["average down calculator", "stock averaging down"],
    status: "active",
    formulaDescription: "New Average = (Existing Capital + New Capital) / (Existing Qty + New Qty)",
    workedExample: {
      scenario: "Holding 100 shares at ₹500; buying 100 more at ₹400.",
      inputs: { "Holding": "100 @ ₹500", "New Buy": "100 @ ₹400" },
      result: "New Combined Average: ₹450.00 | Total Shares: 200",
      explanation: "Total capital ₹90,000 across 200 shares brings the average down to ₹450.",
    },
    relatedTradingSlugs: ["average-price-calculator", "equity-pnl-calculator"],
  },
  {
    slug: "position-size-calculator",
    name: "Position Size Calculator",
    shortDescription: "Determine exact share quantity so trade loss is strictly capped at 1% to 2% of capital.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["position size calculator", "risk per trade calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Allowable Quantity = ⌊(Account Capital × Risk %) / |Entry Price - Stop Loss|⌋",
    workedExample: {
      scenario: "₹2,00,000 capital risking 1.5% with entry at ₹450 and stop-loss at ₹435.",
      inputs: { "Capital": "₹2,00,000", "Risk %": "1.5%", "Entry": "₹450.00", "SL": "₹435.00" },
      result: "Allowable Quantity: 200 Shares | Total Risk: ₹3,000.00",
      explanation: "Risk per share is ₹15. Allowable risk is ₹3,000. ₹3,000 / ₹15 = 200 shares.",
    },
    relatedTradingSlugs: ["risk-reward-calculator", "drawdown-recovery-calculator"],
  },
  {
    slug: "risk-reward-calculator",
    name: "Risk/Reward Ratio Calculator",
    shortDescription: "Calculate risk-to-reward ratio, reward multiplier, and required break-even win rate.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["risk reward calculator", "rr ratio calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Reward/Risk = |Target - Entry| / |Entry - Stop Loss|",
    workedExample: {
      scenario: "Long setup with Entry at ₹100, Stop Loss at ₹95, and Target at ₹115.",
      inputs: { "Entry": "₹100.00", "SL": "₹95.00", "Target": "₹115.00" },
      result: "Risk: 5.00 pts | Reward: 15.00 pts | R:R Ratio: 1 : 3.00",
      explanation: "A 1:3 ratio breaks even with a 25% win rate over time.",
    },
    relatedTradingSlugs: ["position-size-calculator", "risk-of-ruin-calculator"],
  },
  {
    slug: "drawdown-recovery-calculator",
    name: "Drawdown Recovery Calculator",
    shortDescription: "Determine the nonlinear percentage gain required to restore capital after an account drawdown.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["drawdown recovery calculator", "drawdown calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Required Recovery % = [Drawdown % / (100 - Drawdown %)] × 100",
    workedExample: {
      scenario: "An account suffers a 50% drawdown from ₹1,00,000 down to ₹50,000.",
      inputs: { "Drawdown": "50.0%", "Starting Capital": "₹1,00,000" },
      result: "Capital Left: ₹50,000 | Required Recovery Gain: +100.00%",
      explanation: "Recovering back to ₹1,00,000 from ₹50,000 requires doubling the balance (+100%).",
    },
    relatedTradingSlugs: ["position-size-calculator", "daily-loss-limit-calculator"],
  },
  {
    slug: "daily-loss-limit-calculator",
    name: "Daily Loss Limit Calculator",
    shortDescription: "Calculate daily loss thresholds and monitor remaining loss capacity to prevent overtrading.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["daily loss limit calculator", "overtrading prevention"],
    status: "active",
    formulaDescription: "Remaining Allowance = (Capital × Max Loss %) - Realized Loss",
    workedExample: {
      scenario: "₹5,00,000 capital with a 2% daily loss rule, having lost ₹6,000 so far today.",
      inputs: { "Capital": "₹5,00,000", "Daily Limit %": "2.0%", "Current Loss": "₹6,000" },
      result: "Max Daily Limit: ₹10,000 | Remaining Buffer: ₹4,000.00",
      explanation: "You have ₹4,000 in risk capacity left before discipline mandates closing terminals.",
    },
    relatedTradingSlugs: ["drawdown-recovery-calculator", "position-size-calculator"],
  },
  {
    slug: "risk-of-ruin-calculator",
    name: "Risk of Ruin Calculator",
    shortDescription: "Simulate probability of account bankruptcy based on edge, win rate, and risk per trade.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["risk of ruin calculator", "gamblers ruin trading"],
    status: "active",
    formulaDescription: "Ruin Probability = [(1 - Edge) / (1 + Edge)]^(Capital Units)",
    workedExample: {
      scenario: "55% win rate, 1.5 payoff ratio, and 2% risk per trade.",
      inputs: { "Win Rate": "55%", "Payoff": "1.5", "Risk %": "2.0%" },
      result: "Mathematical Edge: +0.375 | Statistical Risk of Ruin: < 0.01%",
      explanation: "With positive expectancy and conservative risk, ruin probability is statistically negligible.",
    },
    relatedTradingSlugs: ["risk-reward-calculator", "position-size-calculator"],
  },
  {
    slug: "brokerage-charges-calculator",
    name: "Indian Brokerage & Taxes Calculator",
    shortDescription: "Calculate STT, GST (18%), exchange turnover fees, SEBI charges, and net break-even for Zerodha, Groww, and Angel One.",
    category: "charges-brokerage",
    renderer: "brokerage",
    keywords: ["zerodha brokerage calculator", "groww charges calculator", "stt calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Total Frictions = Brokerage + STT + Exchange Charges + SEBI Fees + Stamp Duty + 18% GST on services",
    workedExample: {
      scenario: "Buying 100 shares at ₹1,000 and selling at ₹1,050 intraday via Zerodha.",
      inputs: { "Buy": "100 @ ₹1,000", "Sell": "100 @ ₹1,050", "Broker": "Zerodha" },
      result: "Gross P&L: +₹5,000.00 | Total Charges: -₹86.42 | Net P&L: +₹4,913.58",
      explanation: "Turnover is ₹2,05,000. Brokerage ₹40, STT ₹26, Stamp Duty ₹3, GST ₹8.30.",
    },
    relatedTradingSlugs: ["intraday-pnl-calculator", "break-even-after-brokerage-calculator"],
  },
  {
    slug: "break-even-after-brokerage-calculator",
    name: "Break-Even Price After Charges Calculator",
    shortDescription: "Calculate the exact ticks and exit price needed to fully recover all brokerage and regulatory taxes.",
    category: "charges-brokerage",
    renderer: "brokerage",
    keywords: ["break even after charges", "zerodha breakeven calculator"],
    status: "active",
    formulaDescription: "Break-Even Exit = Buy Price + (Total Estimated Charges / Quantity)",
    workedExample: {
      scenario: "Buying 500 shares of an equity stock at ₹200 intraday on Zerodha.",
      inputs: { "Buy Price": "₹200.00", "Quantity": "500", "Segment": "Intraday" },
      result: "Break-Even Points: +₹0.16 | Minimum Profitable Exit: ₹200.16",
      explanation: "A 16-paise gain on 500 shares fully covers all round-trip brokerage, STT, and taxes.",
    },
    relatedTradingSlugs: ["brokerage-charges-calculator", "intraday-pnl-calculator"],
  },
];

export function getTradingToolBySlug(slug: string): TradingToolDefinition | undefined {
  return TRADING_TOOLS.find((t) => t.slug === slug);
}

export function getTradingToolsByCategory(cat: TradingCategory): TradingToolDefinition[] {
  return TRADING_TOOLS.filter((t) => t.category === cat);
}

export function getAllTradingTools(): TradingToolDefinition[] {
  return TRADING_TOOLS;
}
