// ============================================================================
// INDEPENDENT TRADING REGISTRY — PHASE 1 + PHASE 2 TOOLS
// Completely isolated from lib/registry.ts. Zero old-calculator imports.
// ============================================================================

import { TradingCategory, TradingCategoryMeta, TradingToolDefinition } from "./types";

export const TRADING_CATEGORIES: TradingCategoryMeta[] = [
  {
    id: "pnl-trades",
    name: "P&L & Trade Calculators",
    tagline: "Profit & Loss Modeling",
    description: "Intraday, delivery, multi-entry averages, and target profit calculators.",
    badgeColor: "text-steel",
  },
  {
    id: "risk-management",
    name: "Risk Management",
    tagline: "Capital Preservation",
    description: "Position sizing, risk-to-reward ratios, stop-loss limits, and ruin probability.",
    badgeColor: "text-amber-600",
  },
  {
    id: "charges-brokerage",
    name: "Brokerage & Trading Charges",
    tagline: "Regulatory Friction",
    description: "STT, Exchange Turnover, SEBI fees, Stamp Duty, and 18% GST analysis.",
    badgeColor: "text-rose-600",
  },
  {
    id: "options",
    name: "Options Trading",
    tagline: "Options Mechanics",
    description: "Call/Put payoffs, Moneyness (ITM/ATM/OTM), intrinsic value, and breakevens.",
    badgeColor: "text-emerald-600",
  },
  {
    id: "options-strategies",
    name: "Options Strategy Tools",
    tagline: "Multi-Leg Simulators",
    description: "Bull Call Spread, Straddles, Strangles, and Iron Condors with SVG payoff curves.",
    badgeColor: "text-cyan-600",
  },
  {
    id: "futures-leverage",
    name: "Futures & Leverage",
    tagline: "Contract Derivatives",
    description: "Futures margin, leverage multipliers, notional exposure, and liquidation points.",
    badgeColor: "text-orange-600",
  },
  {
    id: "forex-crypto",
    name: "Forex & Crypto",
    tagline: "Currency & Decentralized",
    description: "Pip value calculators, lot sizing, and Dollar-Cost Averaging (DCA).",
    badgeColor: "text-indigo-600",
  },
  {
    id: "performance",
    name: "Trading Performance",
    tagline: "Upcoming Phase 3+",
    description: "Win rate expectancies, Profit Factors, Sharpe, and Sortino ratios.",
    badgeColor: "text-navy/50",
  },
  {
    id: "compounding",
    name: "Compounding & Growth",
    tagline: "Upcoming Phase 3+",
    description: "Daily reinvestment targets, Kelly Criterion, and time-to-target simulations.",
    badgeColor: "text-navy/50",
  },
  {
    id: "technical-analysis",
    name: "Technical Analysis",
    tagline: "Upcoming Phase 3+",
    description: "Pivots (CPR, Camarilla), Fibonacci retracements, and ATR volatility limits.",
    badgeColor: "text-navy/50",
  },
  {
    id: "candlestick-patterns",
    name: "Candlestick Tools",
    tagline: "Upcoming Phase 3+",
    description: "Wick-to-body ratios for Pin Bars, Hammers, Dojis, and Engulfing structures.",
    badgeColor: "text-navy/50",
  },
  {
    id: "portfolio-market",
    name: "Portfolio & Market Tools",
    tagline: "Upcoming Phase 3+",
    description: "Portfolio rebalancing, stock weights, XIRR returns, and sector exposures.",
    badgeColor: "text-navy/50",
  },
  {
    id: "psychology-discipline",
    name: "Trading Psychology & Discipline",
    tagline: "Upcoming Phase 3+",
    description: "Revenge trading risk meters, FOMO checkers, and pre-trade decision scores.",
    badgeColor: "text-navy/50",
  },
  {
    id: "journal-analytics",
    name: "Trading Journal & Analytics",
    tagline: "Upcoming Phase 3+",
    description: "Time-of-day analytics, equity curves, and CSV execution exports.",
    badgeColor: "text-navy/50",
  },
  {
    id: "ai-trading",
    name: "AI Trading Tools",
    tagline: "Upcoming Phase 3+",
    description: "Trade plan evaluation, post-trade reviews, and strategy comparison matrices.",
    badgeColor: "text-navy/50",
  },
  {
    id: "trader-intelligence",
    name: "Trader Intelligence",
    tagline: "Upcoming Phase 3+",
    description: "Trade reality checkers, loss recovery matrices, and 100-trade scenario runs.",
    badgeColor: "text-navy/50",
  },
];

export const TRADING_TOOLS: TradingToolDefinition[] = [
  // --------------------------------------------------------------------------
  // 1. P&L & TRADE CALCULATORS (PHASE 1)
  // --------------------------------------------------------------------------
  {
    slug: "intraday-pnl-calculator",
    name: "Intraday P&L Calculator",
    shortDescription: "Calculate gross & net profit/loss, point movements, and trade return percentage for day trading.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["intraday pnl calculator", "day trading profit calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Long P&L = (Exit - Entry) × Qty - Charges | Short P&L = (Entry - Exit) × Qty - Charges",
    workedExample: {
      scenario: "Buying 100 shares at ₹500 and exiting at ₹540 with ₹20 total charges.",
      inputs: { "Entry": "₹500.00", "Exit": "₹540.00", "Quantity": "100" },
      result: "Gross P&L: +₹4,000.00 | Net P&L: +₹3,980.00",
      explanation: "A 40-point move generates ₹4,000 gross. After ₹20 fees, net profit is ₹3,980.",
    },
    relatedTradingSlugs: ["position-size-calculator", "brokerage-charges-calculator"],
  },
  {
    slug: "equity-pnl-calculator",
    name: "Equity Delivery P&L Calculator",
    shortDescription: "Calculate investment profit, cost basis, sale value, and capital gains for delivery holdings.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["equity delivery calculator", "cnc pnl calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Net Return = (Sell Price × Quantity) - (Buy Price × Quantity) - Charges",
    workedExample: {
      scenario: "Buying 50 shares at ₹1,000 and selling at ₹1,200 after holding with ₹100 charges.",
      inputs: { "Buy Price": "₹1,000.00", "Sell Price": "₹1,200.00", "Quantity": "50" },
      result: "Cost Basis: ₹50,000 | Sale Value: ₹60,000 | Net Profit: +₹9,900.00",
      explanation: "Capital appreciated by ₹10,000. Deducting ₹100 leaves ₹9,900 net gain.",
    },
    relatedTradingSlugs: ["intraday-pnl-calculator", "average-price-calculator"],
  },
  {
    slug: "target-profit-calculator",
    name: "Target Profit Price Calculator",
    shortDescription: "Determine the exact target exit price needed to hit your rupee profit goal.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["target profit calculator", "target price calculator"],
    status: "active",
    formulaDescription: "Long Target Exit = Entry Price + [(Desired Profit + Charges) / Quantity]",
    workedExample: {
      scenario: "Buying 200 shares at ₹250 targeting a net ₹5,000 profit with ₹50 estimated charges.",
      inputs: { "Entry Price": "₹250.00", "Quantity": "200", "Target Profit": "₹5,000.00" },
      result: "Required Target Price: ₹275.25 (+25.25 points move needed)",
      explanation: "Exit at ₹275.25 secures ₹5,050 gross, yielding ₹5,000 net after fees.",
    },
    relatedTradingSlugs: ["intraday-pnl-calculator", "risk-reward-calculator"],
  },
  {
    slug: "stop-loss-calculator",
    name: "Stop-Loss Price Calculator",
    shortDescription: "Calculate exact stop-loss price corresponding to your maximum allowable rupee risk.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["stop loss price calculator", "sl price calculator"],
    status: "active",
    formulaDescription: "Long Stop-Loss = Entry Price - [(Capital × Risk %) / Quantity]",
    workedExample: {
      scenario: "₹1,00,000 capital risking 1% on 100 shares bought at ₹400.",
      inputs: { "Capital": "₹1,00,000", "Risk %": "1.0%", "Quantity": "100", "Entry": "₹400.00" },
      result: "Max Risk: ₹1,000 | Stop-Loss Price: ₹390.00",
      explanation: "Dividing allowable ₹1,000 loss by 100 shares permits a 10-point stop at ₹390.",
    },
    relatedTradingSlugs: ["position-size-calculator", "risk-reward-calculator"],
  },
  {
    slug: "average-price-calculator",
    name: "Multi-Entry Average Price Calculator",
    shortDescription: "Calculate weighted average purchase price and total investment across multiple trade legs.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["average price calculator", "stock average calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Weighted Average Price = Σ(Price × Quantity) / Σ Quantity",
    workedExample: {
      scenario: "Bought 100 shares at ₹100 and 200 shares at ₹85.",
      inputs: { "Leg 1": "100 @ ₹100", "Leg 2": "200 @ ₹85" },
      result: "Total Quantity: 300 | Invested: ₹27,000 | Weighted Avg: ₹90.00",
      explanation: "Total capital ₹27,000 divided by 300 shares equals ₹90.00 average cost.",
    },
    relatedTradingSlugs: ["average-down-calculator", "equity-pnl-calculator"],
  },
  {
    slug: "average-down-calculator",
    name: "Average Down Calculator",
    shortDescription: "Calculate new blended cost basis and additional shares needed to lower your average price.",
    category: "pnl-trades",
    renderer: "pnl",
    keywords: ["average down calculator", "stock averaging down"],
    status: "active",
    formulaDescription: "New Average = (Existing Capital + New Capital) / (Existing Qty + New Qty)",
    workedExample: {
      scenario: "Holding 100 shares at ₹500; buying 100 more at ₹400.",
      inputs: { "Holding": "100 @ ₹500", "New Buy": "100 @ ₹400" },
      result: "New Combined Average: ₹450.00 | Total Shares: 200",
      explanation: "Total capital ₹90,000 across 200 shares brings the average down to ₹450.",
    },
    relatedTradingSlugs: ["average-price-calculator", "equity-pnl-calculator"],
  },

  // --------------------------------------------------------------------------
  // 2. RISK MANAGEMENT TOOLS (PHASE 1)
  // --------------------------------------------------------------------------
  {
    slug: "position-size-calculator",
    name: "Position Size Calculator",
    shortDescription: "Determine exact share quantity so trade loss is strictly capped at 1% to 2% of capital.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["position size calculator", "risk per trade calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Allowable Quantity = ⌊(Account Capital × Risk %) / |Entry Price - Stop Loss|⌋",
    workedExample: {
      scenario: "₹2,00,000 capital risking 1.5% with entry at ₹450 and stop-loss at ₹435.",
      inputs: { "Capital": "₹2,00,000", "Risk %": "1.5%", "Entry": "₹450.00", "SL": "₹435.00" },
      result: "Allowable Quantity: 200 Shares | Total Risk: ₹3,000.00",
      explanation: "Risk per share is ₹15. Allowable risk is ₹3,000. ₹3,000 / ₹15 = 200 shares.",
    },
    relatedTradingSlugs: ["risk-reward-calculator", "drawdown-recovery-calculator"],
  },
  {
    slug: "risk-reward-calculator",
    name: "Risk/Reward Ratio Calculator",
    shortDescription: "Calculate risk-to-reward ratio, reward multiplier, and required break-even win rate.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["risk reward calculator", "rr ratio calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Reward/Risk = |Target - Entry| / |Entry - Stop Loss|",
    workedExample: {
      scenario: "Long setup with Entry at ₹100, Stop Loss at ₹95, and Target at ₹115.",
      inputs: { "Entry": "₹100.00", "SL": "₹95.00", "Target": "₹115.00" },
      result: "Risk: 5.00 pts | Reward: 15.00 pts | R:R Ratio: 1 : 3.00",
      explanation: "A 1:3 ratio breaks even with a 25% win rate over time.",
    },
    relatedTradingSlugs: ["position-size-calculator", "risk-of-ruin-calculator"],
  },
  {
    slug: "drawdown-recovery-calculator",
    name: "Drawdown Recovery Calculator",
    shortDescription: "Determine the nonlinear percentage gain required to restore capital after an account drawdown.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["drawdown recovery calculator", "drawdown calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Required Recovery % = [Drawdown % / (100 - Drawdown %)] × 100",
    workedExample: {
      scenario: "An account suffers a 50% drawdown from ₹1,00,000 down to ₹50,000.",
      inputs: { "Drawdown": "50.0%", "Starting Capital": "₹1,00,000" },
      result: "Capital Left: ₹50,000 | Required Recovery Gain: +100.00%",
      explanation: "Recovering back to ₹1,00,000 from ₹50,000 requires doubling the balance (+100%).",
    },
    relatedTradingSlugs: ["position-size-calculator", "daily-loss-limit-calculator"],
  },
  {
    slug: "daily-loss-limit-calculator",
    name: "Daily Loss Limit Calculator",
    shortDescription: "Calculate daily loss thresholds and monitor remaining loss capacity to prevent overtrading.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["daily loss limit calculator", "overtrading prevention"],
    status: "active",
    formulaDescription: "Remaining Allowance = (Capital × Max Loss %) - Realized Loss",
    workedExample: {
      scenario: "₹5,00,000 capital with a 2% daily loss rule, having lost ₹6,000 so far today.",
      inputs: { "Capital": "₹5,00,000", "Daily Limit %": "2.0%", "Current Loss": "₹6,000" },
      result: "Max Daily Limit: ₹10,000 | Remaining Buffer: ₹4,000.00",
      explanation: "You have ₹4,000 in risk capacity left before discipline mandates closing terminals.",
    },
    relatedTradingSlugs: ["drawdown-recovery-calculator", "position-size-calculator"],
  },
  {
    slug: "risk-of-ruin-calculator",
    name: "Risk of Ruin Calculator",
    shortDescription: "Simulate probability of account bankruptcy based on edge, win rate, and risk per trade.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["risk of ruin calculator", "gamblers ruin trading"],
    status: "active",
    formulaDescription: "Ruin Probability = [(1 - Edge) / (1 + Edge)]^(Capital Units)",
    workedExample: {
      scenario: "55% win rate, 1.5 payoff ratio, and 2% risk per trade.",
      inputs: { "Win Rate": "55%", "Payoff": "1.5", "Risk %": "2.0%" },
      result: "Mathematical Edge: +0.375 | Statistical Risk of Ruin: < 0.01%",
      explanation: "With positive expectancy and conservative risk, ruin probability is statistically negligible.",
    },
    relatedTradingSlugs: ["risk-reward-calculator", "position-size-calculator"],
  },

  // --------------------------------------------------------------------------
  // 3. BROKERAGE & STATUTORY CHARGES TOOLS (PHASE 1)
  // --------------------------------------------------------------------------
  {
    slug: "brokerage-charges-calculator",
    name: "Indian Brokerage & Taxes Calculator",
    shortDescription: "Calculate STT, GST (18%), exchange turnover fees, SEBI charges, and net break-even for Zerodha, Groww, and Angel One.",
    category: "charges-brokerage",
    renderer: "brokerage",
    keywords: ["zerodha brokerage calculator", "groww charges calculator", "stt calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Total Frictions = Brokerage + STT + Exchange Charges + SEBI Fees + Stamp Duty + 18% GST on services",
    workedExample: {
      scenario: "Buying 100 shares at ₹1,000 and selling at ₹1,050 intraday via Zerodha.",
      inputs: { "Buy": "100 @ ₹1,000", "Sell": "100 @ ₹1,050", "Broker": "Zerodha" },
      result: "Gross P&L: +₹5,000.00 | Total Charges: -₹86.42 | Net P&L: +₹4,913.58",
      explanation: "Turnover is ₹2,05,000. Brokerage ₹40, STT ₹26, Stamp Duty ₹3, GST ₹8.30.",
    },
    relatedTradingSlugs: ["intraday-pnl-calculator", "break-even-after-brokerage-calculator"],
  },
  {
    slug: "break-even-after-brokerage-calculator",
    name: "Break-Even Price After Charges Calculator",
    shortDescription: "Calculate the exact ticks and exit price needed to fully recover all brokerage and regulatory taxes.",
    category: "charges-brokerage",
    renderer: "brokerage",
    keywords: ["break even after charges", "zerodha breakeven calculator"],
    status: "active",
    formulaDescription: "Break-Even Exit = Buy Price + (Total Estimated Charges / Quantity)",
    workedExample: {
      scenario: "Buying 500 shares of an equity stock at ₹200 intraday on Zerodha.",
      inputs: { "Buy Price": "₹200.00", "Quantity": "500", "Segment": "Intraday" },
      result: "Break-Even Points: +₹0.16 | Minimum Profitable Exit: ₹200.16",
      explanation: "A 16-paise gain on 500 shares fully covers all round-trip brokerage, STT, and taxes.",
    },
    relatedTradingSlugs: ["brokerage-charges-calculator", "intraday-pnl-calculator"],
  },

  // --------------------------------------------------------------------------
  // 4. OPTIONS MECHANICS TOOLS (PHASE 2A)
  // --------------------------------------------------------------------------
  {
    slug: "call-option-payoff-calculator",
    name: "Call Option Payoff Calculator",
    shortDescription: "Calculate intrinsic payoff, net profit/loss, and expiry breakeven for long and short call contracts.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["call option payoff", "call option calculator", "long call payoff"],
    popular: true,
    status: "active",
    formulaDescription: "Long Call Profit = max(Underlying Price - Strike, 0) - Premium Paid",
    workedExample: {
      scenario: "Buying 1 Lot (50 units) of Nifty 24,500 Call at ₹180 premium with Nifty at 24,800 at expiry.",
      inputs: { "Strike": "24,500", "Premium": "₹180", "Expiry Spot": "24,800", "Quantity": "50" },
      result: "Gross Payoff: ₹300/unit | Net Profit: +₹6,000.00 (+66.67% ROI) | Breakeven: ₹24,680",
      explanation: "Intrinsic value at expiry is ₹300. Subtracting the ₹180 premium leaves ₹120 net profit per unit (₹6,000 total across 50 shares).",
    },
    relatedTradingSlugs: ["put-option-payoff-calculator", "bull-call-spread-calculator"],
  },
  {
    slug: "put-option-payoff-calculator",
    name: "Put Option Payoff Calculator",
    shortDescription: "Calculate put option intrinsic value, expiry profit/loss, and downside breakeven price.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["put option payoff", "put option calculator", "long put payoff"],
    popular: true,
    status: "active",
    formulaDescription: "Long Put Profit = max(Strike - Underlying Price, 0) - Premium Paid",
    workedExample: {
      scenario: "Buying 1 Lot (50 units) of 24,500 Put at ₹150 premium with spot dropping to 24,100 at expiry.",
      inputs: { "Strike": "24,500", "Premium": "₹150", "Expiry Spot": "24,100", "Quantity": "50" },
      result: "Gross Payoff: ₹400/unit | Net Profit: +₹12,500.00 | Breakeven: ₹24,350",
      explanation: "Intrinsic payoff is ₹400. Deducting the ₹150 paid premium yields ₹250 net gain per unit.",
    },
    relatedTradingSlugs: ["call-option-payoff-calculator", "bear-put-spread-calculator"],
  },
  {
    slug: "options-moneyness-calculator",
    name: "Options Moneyness & Intrinsic Value Calculator",
    shortDescription: "Determine In-The-Money (ITM), At-The-Money (ATM), and Out-of-The-Money (OTM) status and time value.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["options moneyness", "itm atm otm calculator", "intrinsic value options"],
    status: "active",
    formulaDescription: "Call Intrinsic = max(Spot - Strike, 0) | Time Value = Premium - Intrinsic Value",
    workedExample: {
      scenario: "Nifty trading at 24,620 with a 24,500 Call quoting at ₹210 premium.",
      inputs: { "Spot": "24,620", "Strike": "24,500", "Premium": "₹210" },
      result: "Status: ITM (In-The-Money) | Intrinsic Value: ₹120.00 | Time Value: ₹90.00",
      explanation: "The call is 120 points in-the-money. The remaining ₹90 of the ₹210 market premium represents extrinsic time value.",
    },
    relatedTradingSlugs: ["call-option-payoff-calculator", "options-breakeven-calculator"],
  },
  {
    slug: "options-breakeven-calculator",
    name: "Options Breakeven Calculator",
    shortDescription: "Calculate the exact underlying price needed at expiry to break even on Calls and Puts.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["options breakeven", "call option breakeven", "put option breakeven"],
    status: "active",
    formulaDescription: "Call Breakeven = Strike + Premium | Put Breakeven = Strike - Premium",
    workedExample: {
      scenario: "Buying 24,200 Strike Put at ₹140 premium.",
      inputs: { "Strike": "24,200", "Premium": "₹140" },
      result: "Breakeven Price: ₹24,060.00 (-140 points adverse move required)",
      explanation: "The underlying must fall below ₹24,060 by expiry for the trade to generate net profit.",
    },
    relatedTradingSlugs: ["put-option-payoff-calculator", "call-option-payoff-calculator"],
  },

  // --------------------------------------------------------------------------
  // 5. OPTIONS STRATEGY SIMULATORS (PHASE 2B)
  // --------------------------------------------------------------------------
  {
    slug: "bull-call-spread-calculator",
    name: "Bull Call Spread Calculator",
    shortDescription: "Simulate two-leg debit call spread payoffs, maximum profit caps, and net debit risk with SVG charts.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["bull call spread", "call spread calculator", "vertical spread options"],
    popular: true,
    status: "active",
    formulaDescription: "Max Profit = (Upper Strike - Lower Strike) - Net Debit | Max Loss = Net Debit Paid",
    workedExample: {
      scenario: "Buy 24,500 Call at ₹190, Sell 25,000 Call at ₹60 on 50 units (Nifty).",
      inputs: { "Lower Strike": "24,500", "Upper Strike": "25,000", "Net Debit": "₹130/unit (₹6,500)" },
      result: "Max Profit: +₹18,500.00 | Max Risk: -₹6,500.00 | Breakeven: ₹24,630",
      explanation: "The 500-point spread width minus the 130-point net debit caps upside at 370 points (₹18,500 on 50 shares).",
    },
    relatedTradingSlugs: ["bear-put-spread-calculator", "call-option-payoff-calculator"],
  },
  {
    slug: "bear-put-spread-calculator",
    name: "Bear Put Spread Calculator",
    shortDescription: "Simulate vertical debit put spread returns, capped downside profit, and breakeven levels.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["bear put spread", "debit put spread", "options bear spread"],
    popular: true,
    status: "active",
    formulaDescription: "Max Profit = (Upper Put Strike - Lower Put Strike) - Net Debit | Breakeven = Upper Strike - Net Debit",
    workedExample: {
      scenario: "Buy 24,500 Put at ₹160, Sell 24,000 Put at ₹45 on 50 units.",
      inputs: { "Upper Put": "24,500", "Lower Put": "24,000", "Net Debit": "₹115/unit (₹5,750)" },
      result: "Max Profit: +₹19,250.00 | Max Risk: -₹5,750.00 | Breakeven: ₹24,385",
      explanation: "Spread generates maximum ₹19,250 profit if spot closes at or below 24,000 at expiry.",
    },
    relatedTradingSlugs: ["bull-call-spread-calculator", "long-straddle-calculator"],
  },
  {
    slug: "long-straddle-calculator",
    name: "Long Straddle Payoff Calculator",
    shortDescription: "Calculate dual breakevens and unlimited volatility expansion payoffs on ATM Call + Put combinations.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["long straddle calculator", "straddle options", "volatility options strategy"],
    popular: true,
    status: "active",
    formulaDescription: "Lower BE = Strike - (Call Prem + Put Prem) | Upper BE = Strike + (Call Prem + Put Prem)",
    workedExample: {
      scenario: "Buy 24,500 Call at ₹180 and 24,500 Put at ₹170 on 50 units.",
      inputs: { "Strike": "24,500", "Total Premium": "₹350/unit (₹17,500)" },
      result: "Lower BE: ₹24,150 | Upper BE: ₹24,850 | Max Loss: -₹17,500 | Max Profit: Unlimited",
      explanation: "Strategy yields profit if the underlying closes either below ₹24,150 or above ₹24,850 at expiry.",
    },
    relatedTradingSlugs: ["bull-call-spread-calculator", "iron-condor-calculator"],
  },
  {
    slug: "iron-condor-calculator",
    name: "Iron Condor Strategy Calculator",
    shortDescription: "Model 4-leg market-neutral credit condors with defined risk wings, dual breakevens, and net credit collection.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["iron condor calculator", "4 leg options strategy", "range bound options"],
    popular: true,
    status: "active",
    formulaDescription: "Max Profit = Net Credit Received | Max Loss = Wing Width - Net Credit",
    workedExample: {
      scenario: "Sell 24,100 Put & 24,800 Call, Buy 23,800 Put & 25,100 Call. Net Credit: ₹110 (₹5,500 on 50 units).",
      inputs: { "Wing Width": "300 pts", "Net Credit": "110 pts (₹5,500)" },
      result: "Max Profit: +₹5,500.00 | Max Loss: -₹9,500.00 | Profit Range: ₹23,990 to ₹24,910",
      explanation: "Keeps full ₹5,500 credit if underlying expires anywhere between ₹24,100 and ₹24,800.",
    },
    relatedTradingSlugs: ["long-straddle-calculator", "bull-call-spread-calculator"],
  },

  // --------------------------------------------------------------------------
  // 6. FUTURES & LEVERAGE TOOLS (PHASE 2D)
  // --------------------------------------------------------------------------
  {
    slug: "futures-pnl-calculator",
    name: "Futures P&L Calculator",
    shortDescription: "Calculate futures trade profit, points gained, notional exposure, and return on deposited margin.",
    category: "futures-leverage",
    renderer: "futures",
    keywords: ["futures pnl calculator", "nifty futures calculator", "derivative pnl"],
    popular: true,
    status: "active",
    formulaDescription: "Futures P&L = (Exit Price - Entry Price) × Quantity Lots × Lot Multiplier [Long]",
    workedExample: {
      scenario: "Buying 2 Lots of Nifty Futures (100 units) at 24,500 and squaring off at 24,750.",
      inputs: { "Entry": "24,500", "Exit": "24,750", "Lots": "2", "Lot Size": "50" },
      result: "Points: +250.00 pts | Realized P&L: +₹25,000.00 | Notional: ₹24,50,000",
      explanation: "A 250-point gain across 100 contract units yields ₹25,000 gross gain on a ₹24.5 Lakh notional commitment.",
    },
    relatedTradingSlugs: ["futures-margin-calculator", "intraday-pnl-calculator"],
  },
  {
    slug: "futures-margin-calculator",
    name: "Futures Margin & Leverage Calculator",
    shortDescription: "Determine initial SPAN + Exposure margin requirements, effective leverage, and margin utilization.",
    category: "futures-leverage",
    renderer: "futures",
    keywords: ["futures margin calculator", "span margin calculator", "derivatives leverage"],
    popular: true,
    status: "active",
    formulaDescription: "Initial Margin = (Price × Lot Size × Lots) × Margin Rate % | Leverage = 100 / Margin %",
    workedExample: {
      scenario: "Contract price 24,500, lot size 50, 2 lots traded at 12% statutory margin.",
      inputs: { "Notional Value": "₹24,50,000", "Margin Rate": "12.0%" },
      result: "Initial Margin Required: ₹2,94,000.00 | Embedded Leverage: 8.3x",
      explanation: "A ₹2.94 Lakh deposit controls ₹24.50 Lakh in notional equity exposure.",
    },
    relatedTradingSlugs: ["futures-pnl-calculator", "liquidation-price-calculator"],
  },
  {
    slug: "liquidation-price-calculator",
    name: "Estimated Liquidation Price Calculator",
    shortDescription: "Estimate liquidation price based on leverage multiplier and maintenance margin buffer.",
    category: "futures-leverage",
    renderer: "futures",
    keywords: ["liquidation price calculator", "crypto liquidation", "futures liquidation"],
    status: "active",
    formulaDescription: "Long Liq = Entry × [1 - (1 / Leverage) + Maintenance Margin %]",
    workedExample: {
      scenario: "Long position entered at ₹24,500 with 10x leverage and 0.5% maintenance margin.",
      inputs: { "Entry": "₹24,500", "Leverage": "10x", "Maintenance": "0.5%" },
      result: "Estimated Liquidation Price: ₹22,172.50 (-9.50% adverse move threshold)",
      explanation: "A 9.50% drop consumes initial equity buffer, triggering mandatory contract liquidation.",
    },
    relatedTradingSlugs: ["futures-margin-calculator", "position-size-calculator"],
  },

  // --------------------------------------------------------------------------
  // 7. FOREX & CRYPTO TOOLS (PHASE 2E & 2F)
  // --------------------------------------------------------------------------
  {
    slug: "forex-pip-value-calculator",
    name: "Forex Pip Value Calculator",
    shortDescription: "Calculate cash value per pip across standard, mini, and micro lots in local account currency.",
    category: "forex-crypto",
    renderer: "forex",
    keywords: ["forex pip calculator", "pip value calculator", "currency trading pip"],
    popular: true,
    status: "active",
    formulaDescription: "Pip Value = Lots × Lot Size Units × Pip Decimal Size × Exchange Rate",
    workedExample: {
      scenario: "1 Standard Lot (100,000 units) on EUR/USD (0.0001 pip) with USD/INR at 85.50.",
      inputs: { "Lots": "1.0", "Pip Size": "0.0001", "FX Rate": "85.50" },
      result: "Pip Value: $10.00 / pip (₹855.00 INR per pip)",
      explanation: "Each 1-pip price move creates an ₹855 equity change on a 1 standard lot position.",
    },
    relatedTradingSlugs: ["forex-position-size-calculator", "position-size-calculator"],
  },
  {
    slug: "forex-position-size-calculator",
    name: "Forex Lot Size & Risk Calculator",
    shortDescription: "Determine exact lot sizing to ensure risk remains fixed to 1% of account capital.",
    category: "forex-crypto",
    renderer: "forex",
    keywords: ["forex lot size calculator", "forex position size", "forex risk calculator"],
    status: "active",
    formulaDescription: "Allowable Lots = (Account Capital × Risk %) / (Stop Loss Pips × Pip Value Per Lot)",
    workedExample: {
      scenario: "₹1,00,000 account risking 1.5% with a 25-pip stop loss on USD/INR (₹855/lot pip value).",
      inputs: { "Capital": "₹1,00,000", "Risk %": "1.5%", "Stop": "25 Pips" },
      result: "Allowable Lot Size: 0.07 Standard Lots (7 Micro Lots) | Max Risk: ₹1,500.00",
      explanation: "Trading 0.07 lots ensures a 25-pip adverse move limits total loss strictly to ₹1,500.",
    },
    relatedTradingSlugs: ["forex-pip-value-calculator", "position-size-calculator"],
  },
  {
    slug: "crypto-dca-calculator",
    name: "Crypto DCA (Dollar-Cost Averaging) Calculator",
    shortDescription: "Calculate weighted average buy price and accumulated coin holdings across recurring purchase orders.",
    category: "forex-crypto",
    renderer: "crypto",
    keywords: ["crypto dca calculator", "bitcoin dca calculator", "dollar cost average crypto"],
    popular: true,
    status: "active",
    formulaDescription: "DCA Average Price = Total Fiat Invested / Total Token Units Acquired",
    workedExample: {
      scenario: "Bought ₹50,000 of Bitcoin at ₹55,00,000 and ₹50,00,000 at ₹50,00,000.",
      inputs: { "Buy 1": "₹50k @ ₹55L", "Buy 2": "₹50k @ ₹50L" },
      result: "Total Invested: ₹1,00,000 | Tokens: 0.019091 BTC | Average Cost: ₹52,380.95",
      explanation: "Purchasing during the dip lowers the aggregate coin cost basis below the simple arithmetic average.",
    },
    relatedTradingSlugs: ["average-price-calculator", "average-down-calculator"],
  },
];

export function getTradingToolBySlug(slug: string): TradingToolDefinition | undefined {
  return TRADING_TOOLS.find((t) => t.slug === slug);
}

export function getTradingToolsByCategory(cat: TradingCategory): TradingToolDefinition[] {
  return TRADING_TOOLS.filter((t) => t.category === cat);
}

export function getAllTradingTools(): TradingToolDefinition[] {
  return TRADING_TOOLS;
}
