// ============================================================================
// INDEPENDENT TRADING REGISTRY — FULLY HARDENED (PHASES 1 & 2)
// Complete with 6-8 unique FAQs per tool, formulas, and worked examples.
// ============================================================================

import { TradingCategory, TradingCategoryMeta, TradingToolDefinition } from "./types";

export const TRADING_CATEGORIES: TradingCategoryMeta[] = [
  {
    id: "options",
    name: "Options Trading",
    tagline: "Options Mechanics",
    description: "Call/Put payoffs, Moneyness (ITM/ATM/OTM), intrinsic value, and breakevens.",
    badgeColor: "text-emerald-700",
  },
  {
    id: "options-strategies",
    name: "Options Strategy Tools",
    tagline: "Multi-Leg Simulators",
    description: "Bull Call Spread, Straddles, Strangles, and Iron Condors with SVG payoff curves.",
    badgeColor: "text-cyan-700",
  },
  {
    id: "futures-leverage",
    name: "Futures & Leverage",
    tagline: "Contract Derivatives",
    description: "Futures margin, leverage multipliers, notional exposure, and liquidation points.",
    badgeColor: "text-orange-700",
  },
  {
    id: "forex-crypto",
    name: "Forex & Crypto",
    tagline: "Currency & Decentralized",
    description: "Pip value calculators, lot sizing, and Dollar-Cost Averaging (DCA).",
    badgeColor: "text-indigo-700",
  },
  {
    id: "pnl-trades",
    name: "P&L & Trade Calculators",
    tagline: "Profit & Loss Modeling",
    description: "Intraday, delivery, multi-entry averages, and target profit calculators.",
    badgeColor: "text-steel",
  },
  {
    id: "risk-management",
    name: "Risk Management",
    tagline: "Capital Preservation",
    description: "Position sizing, risk-to-reward ratios, stop-loss limits, and ruin probability.",
    badgeColor: "text-amber-700",
  },
  {
    id: "charges-brokerage",
    name: "Brokerage & Trading Charges",
    tagline: "Regulatory Friction",
    description: "STT, Exchange Turnover, SEBI fees, Stamp Duty, and 18% GST analysis.",
    badgeColor: "text-rose-700",
  },
  {
    id: "technical-analysis",
    name: "Technical Analysis",
    tagline: "Market Indicators",
    description: "Pivots (CPR, Camarilla), Fibonacci retracements, and ATR volatility limits.",
    badgeColor: "text-navy/50",
  },
  {
    id: "portfolio-market",
    name: "Portfolio & Market Tools",
    tagline: "Asset Allocation",
    description: "Portfolio rebalancing, stock weights, XIRR returns, and sector exposures.",
    badgeColor: "text-navy/50",
  },
];

export const TRADING_TOOLS: TradingToolDefinition[] = [
  // --------------------------------------------------------------------------
  // RISK MANAGEMENT TOOLS (PHASE 1) — HARDENED WITH 6-8 UNIQUE FAQS
  // --------------------------------------------------------------------------
  {
    slug: "position-size-calculator",
    name: "Position Size Calculator",
    shortDescription: "Determine exact share quantity so trade loss is strictly capped at 1% to 2% of capital.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["position size calculator", "risk per trade calculator", "lot size calculator", "capital risk manager"],
    popular: true,
    status: "active",
    formulaDescription: "Allowable Quantity = ⌊(Account Capital × Risk %) / |Entry Price - Stop Loss Price|⌋",
    formulaVariables: [
      { symbol: "Account Capital", label: "Total active trading equity balance in rupees" },
      { symbol: "Risk %", label: "Maximum percentage willing to risk on this trade (typically 1% to 2%)" },
      { symbol: "Per Share Risk", label: "Absolute price difference between Entry and Stop-Loss" },
    ],
    workedExample: {
      scenario: "₹2,00,000 capital risking 1.5% with entry at ₹450 and stop-loss at ₹435.",
      inputs: { "Account Capital": "₹2,00,000.00", "Risk %": "1.5%", "Entry Price": "₹450.00", "Stop-Loss": "₹435.00" },
      result: "Allowable Quantity: 200 Shares | Total Rupee Risk: ₹3,000.00 | Position Value: ₹90,000.00",
      explanation: "Per share risk is ₹15. Allowable rupee risk is ₹3,000 (1.5% of ₹2.0L). Dividing ₹3,000 by ₹15 yields exactly 200 shares.",
    },
    assumptions: [
      "Quantities are rounded down to conservative whole integers to prevent breaking account risk limits.",
      "Adverse market opening gaps exceeding stop-loss levels are excluded from the baseline mathematical formula.",
    ],
    faqs: [
      { q: "What is a position size calculator?", a: "A position size calculator determines the exact number of shares or lots you should trade to ensure your maximum financial risk on the trade matches your predetermined risk budget." },
      { q: "Why should risk per trade be capped at 1% to 2%?", a: "Limiting risk to 1-2% protects your trading capital from catastrophic drawdown during inevitable losing streaks." },
      { q: "How is position size computed mathematically?", a: "It is calculated by dividing your total allowable rupee risk (Capital × Risk %) by the risk per share (Entry Price minus Stop-Loss Price)." },
      { q: "What happens if the stop-loss distance is very small?", a: "A tighter stop-loss increases the allowable share quantity for the same rupee risk budget. However, it also raises the probability of getting stopped out by routine market noise." },
      { q: "Does position sizing guarantee trading profitability?", a: "No. Position sizing manages risk and capital preservation; overall profitability depends on your strategy's win rate and edge." },
      { q: "Should I include brokerage and taxes in position sizing?", a: "While position sizing focuses on price stop-loss risk, factoring in expected brokerage and slippage ensures total friction does not breach your risk limit." },
      { q: "How does account capital affect position sizing?", a: "Larger account capital permits larger absolute position sizes while maintaining the exact same percentage risk profile." },
    ],
    relatedTradingSlugs: ["risk-reward-calculator", "drawdown-recovery-calculator", "daily-loss-limit-calculator"],
  },
  {
    slug: "risk-reward-calculator",
    name: "Risk/Reward Ratio Calculator",
    shortDescription: "Calculate risk-to-reward ratio, reward multiplier, and required break-even win rate.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["risk reward calculator", "rr ratio calculator", "reward to risk ratio"],
    popular: true,
    status: "active",
    formulaDescription: "Reward/Risk Ratio = |Target Price - Entry Price| / |Entry Price - Stop-Loss Price|",
    formulaVariables: [
      { symbol: "Risk Distance", label: "Absolute point distance from Entry to Stop-Loss" },
      { symbol: "Reward Distance", label: "Absolute point distance from Entry to Profit Target" },
      { symbol: "Break-Even Win Rate", label: "Minimum win rate needed to profit: 1 / (1 + RR Ratio)" },
    ],
    workedExample: {
      scenario: "Long setup with Entry at ₹100, Stop Loss at ₹95, and Target at ₹115.",
      inputs: { "Entry Price": "₹100.00", "Stop-Loss": "₹95.00", "Target Price": "₹115.00" },
      result: "Risk Distance: 5.00 pts | Reward Distance: 15.00 pts | R:R Ratio: 1 : 3.00 | Break-Even Win Rate: 25.0%",
      explanation: "Risk is 5 points and reward is 15 points, producing a 1:3 asymmetric risk/reward profile. This setup breaks even with only a 25% win rate over time.",
    },
    assumptions: [
      "Calculations evaluate price point distances; execution slippage and commissions are excluded.",
      "The break-even win rate assumes constant average win and loss sizes.",
    ],
    faqs: [
      { q: "What is a risk-to-reward ratio?", a: "A risk-to-reward ratio compares the potential loss of a trade (distance to stop-loss) against its anticipated profit (distance to target)." },
      { q: "What is considered a good risk/reward ratio?", a: "Professional traders typically seek a minimum risk-to-reward ratio of 1:2 or 1:3 to ensure winning trades comfortably outweigh losing ones." },
      { q: "How is break-even win rate calculated from R:R?", a: "Break-even win rate equals 1 divided by (1 plus the Reward-to-Risk ratio). A 1:2 ratio requires a 33.3% win rate to break even." },
      { q: "Can a low risk/reward trade still be profitable?", a: "Yes, if the strategy maintains an exceptionally high win rate (e.g., 80%), though a single adverse gap can wipe out multiple gains." },
      { q: "Why is risk/reward asymmetry important?", a: "Asymmetry allows you to remain profitable even when your win rate is below 50%." },
    ],
    relatedTradingSlugs: ["position-size-calculator", "risk-of-ruin-calculator", "stop-loss-calculator"],
  },
  {
    slug: "drawdown-recovery-calculator",
    name: "Drawdown Recovery Calculator",
    shortDescription: "Determine the nonlinear percentage gain required to restore capital after an account drawdown.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["drawdown recovery calculator", "drawdown calculator", "loss recovery percentage"],
    popular: true,
    status: "active",
    formulaDescription: "Required Recovery % = [Drawdown % / (100 - Drawdown %)] × 100",
    formulaVariables: [
      { symbol: "Drawdown %", label: "Percentage equity loss sustained from peak capital" },
      { symbol: "Capital Remaining", label: "Starting Capital × (1 - Drawdown %)" },
      { symbol: "Recovery Gain %", label: "Percentage gain needed on remaining equity to restore initial peak" },
    ],
    workedExample: {
      scenario: "An account suffers a 50% drawdown from ₹1,00,000 down to ₹50,000.",
      inputs: { "Drawdown %": "50.0%", "Starting Capital": "₹1,00,000.00" },
      result: "Capital Remaining: ₹50,000.00 | Required Recovery Gain: +100.00%",
      explanation: "Because your capital base has halved, recovering back to ₹1,00,000 requires doubling your remaining equity (+100% gain).",
    },
    assumptions: [
      "Recovery percentage assumes continuous compounding on remaining account equity.",
      "Additional deposits into the trading account are not factored into the baseline recovery calculation.",
    ],
    faqs: [
      { q: "Why is drawdown recovery nonlinear?", a: "Because losses are calculated from a larger capital base while gains are calculated from a depleted capital base, larger drawdowns require disproportionately larger percentage gains to recover." },
      { q: "How much gain is needed to recover from a 20% loss?", a: "A 20% loss requires a 25% gain to restore your starting balance." },
      { q: "What gain is needed to recover from a 50% loss?", a: "A 50% loss requires a 100% gain (doubling your money) just to break even." },
      { q: "Why is preventing deep drawdowns critical?", a: "Deep drawdowns (e.g., 50%+) demand extraordinary performance, significantly increasing psychological pressure and risk of total account ruin." },
      { q: "Does this calculator factor in trading fees during recovery?", a: "No. Brokerage charges and taxes incurred during recovery trades will further increase the required gross trading gains." },
      { q: "How can traders minimize drawdown depth?", a: "By adhering strictly to 1-2% position sizing and enforcing daily/weekly loss limits." },
    ],
    relatedTradingSlugs: ["position-size-calculator", "daily-loss-limit-calculator", "risk-of-ruin-calculator"],
  },
  {
    slug: "daily-loss-limit-calculator",
    name: "Daily Loss Limit Calculator",
    shortDescription: "Calculate daily loss thresholds and monitor remaining loss capacity to prevent overtrading.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["daily loss limit calculator", "overtrading prevention", "max loss limit"],
    status: "active",
    formulaDescription: "Remaining Loss Buffer = (Capital × Max Daily Loss %) - Realized Loss Today",
    formulaVariables: [
      { symbol: "Max Daily Loss %", label: "Pre-committed maximum account loss allowed in a single trading session" },
      { symbol: "Realized Loss", label: "Total closed losses incurred during the current session" },
      { symbol: "Buffer Capacity", label: "Remaining rupee capital before trading must halt" },
    ],
    workedExample: {
      scenario: "₹5,00,000 capital with a 2% daily loss rule, having lost ₹6,000 so far today.",
      inputs: { "Account Capital": "₹5,00,000.00", "Max Daily Loss %": "2.0%", "Realized Loss Today": "₹6,000.00" },
      result: "Max Daily Limit: ₹10,000.00 | Remaining Buffer: ₹4,000.00 (60.0% Capacity Consumed)",
      explanation: "Your 2% daily limit is ₹10,000. Having lost ₹6,000, you have ₹4,000 in risk capacity left before discipline mandates closing your terminal.",
    },
    assumptions: [
      "Loss calculations evaluate realized closing losses plus open unrealized trade drawdowns.",
      "Discipline rules rely entirely on trader self-enforcement to close platforms upon breach.",
    ],
    faqs: [
      { q: "What is a daily loss limit?", a: "A daily loss limit is a pre-determined risk rule that forces you to stop trading for the day once your losses reach a maximum acceptable threshold." },
      { q: "Why is a daily loss limit important?", a: "It prevents revenge trading, emotional spirals, and catastrophic account wipeouts during difficult market sessions." },
      { q: "How is the daily limit calculated?", a: "It is typically calculated as a fixed percentage (e.g., 1% to 2%) of your total active trading equity." },
      { q: "What should I do when my daily loss limit is reached?", a: "Immediately close your trading platform, step away from screens, and review your trades only after emotions have settled." },
      { q: "Can this calculator automatically lock my broker account?", a: "No. This tool calculates your thresholds mathematically. Account-level lockouts must be configured directly within your broker's risk settings." },
    ],
    relatedTradingSlugs: ["drawdown-recovery-calculator", "position-size-calculator", "risk-of-ruin-calculator"],
  },
  {
    slug: "risk-of-ruin-calculator",
    name: "Risk of Ruin Calculator",
    shortDescription: "Simulate probability of account bankruptcy based on edge, win rate, and risk per trade.",
    category: "risk-management",
    renderer: "risk",
    keywords: ["risk of ruin calculator", "gamblers ruin trading", "ruin probability"],
    status: "active",
    formulaDescription: "Ruin Probability = [(1 - Edge) / (1 + Edge)]^(Capital Units)",
    formulaVariables: [
      { symbol: "Win Rate %", label: "Historical percentage of winning trades" },
      { symbol: "Payoff Ratio", label: "Average Winning Trade / Average Losing Trade" },
      { symbol: "Mathematical Edge", label: "Expected expectancy per trade: (Win Rate × Payoff) - Loss Rate" },
    ],
    workedExample: {
      scenario: "55% win rate, 1.5 payoff ratio, and 2% risk per trade.",
      inputs: { "Win Rate": "55.0%", "Payoff Ratio": "1.5", "Risk per Trade %": "2.0%" },
      result: "Mathematical Edge: +0.375 | Statistical Risk of Ruin: < 0.01%",
      explanation: "With a positive mathematical expectancy and conservative 2% risk per trade, the statistical probability of complete account ruin is negligible.",
    },
    assumptions: [
      "Assumes independent, identically distributed trade outcomes with constant win rate and payoff ratio.",
      "Does not account for non-stationary market regimes or psychological tilt.",
    ],
    faqs: [
      { q: "What is the risk of ruin in trading?", a: "Risk of ruin is the mathematical probability that a trading system will result in total account bankruptcy over a series of trades." },
      { q: "How does win rate affect risk of ruin?", a: "Higher win rates significantly reduce the risk of ruin, provided average losses do not excessively outstrip average wins." },
      { q: "Why can a system with a positive win rate still go bankrupt?", a: "If position sizing is too aggressive (e.g., risking 20% per trade), a string of consecutive losses can wipe out equity before recovery occurs." },
      { q: "What role does the payoff ratio play?", a: "A high payoff ratio allows a trading system to remain profitable and safe even with a win rate below 50%." },
      { q: "How does position sizing impact risk of ruin?", a: "Lowering risk per trade (e.g., from 5% to 1%) exponentially decreases the statistical risk of ruin." },
    ],
    relatedTradingSlugs: ["risk-reward-calculator", "position-size-calculator", "drawdown-recovery-calculator"],
  },

  // --------------------------------------------------------------------------
  // INDIAN BROKERAGE & TAXES TOOLS (PHASE 1) — HARDENED WITH 6-8 UNIQUE FAQS
  // --------------------------------------------------------------------------
  {
    slug: "brokerage-charges-calculator",
    name: "Indian Brokerage & Taxes Calculator",
    shortDescription: "Calculate STT, GST (18%), exchange turnover fees, SEBI charges, and net break-even for Zerodha, Groww, and Angel One.",
    category: "charges-brokerage",
    renderer: "brokerage",
    keywords: ["zerodha brokerage calculator", "groww charges calculator", "stt calculator", "share market taxes india"],
    popular: true,
    status: "active",
    formulaDescription: "Total Frictions = Brokerage + STT + Exchange Charges + SEBI Fees + Stamp Duty + GST (18% on taxable services)",
    formulaVariables: [
      { symbol: "STT", label: "Securities Transaction Tax: 0.025% on sell side for intraday" },
      { symbol: "Exchange Charges", label: "NSE/BSE turnover transaction fees (~0.00297%)" },
      { symbol: "Stamp Duty", label: "State government levy on buy-side turnover (0.003% intraday)" },
      { symbol: "GST", label: "18% tax applied strictly on Brokerage + Exchange + SEBI fees" },
    ],
    workedExample: {
      scenario: "Buying 100 shares at ₹1,000 and selling at ₹1,050 intraday via Zerodha.",
      inputs: { "Buy Price": "₹1,000.00", "Sell Price": "₹1,050.00", "Quantity": "100", "Broker": "Zerodha", "Segment": "Intraday" },
      result: "Gross P&L: +₹5,000.00 | Total Charges: -₹83.63 | Net In-Pocket: +₹4,916.37",
      explanation: "Turnover is ₹2,05,000. Brokerage is ₹40, STT is ₹26, Exchange fees are ₹6.09, SEBI fees are ₹0.21, Stamp Duty is ₹3, and GST on fees is ₹8.33, totaling ₹83.63 in charges.",
    },
    assumptions: [
      "Statutory tax rates follow official schedules prescribed by NSE, BSE, SEBI, and Indian Stamp Act.",
      "GST is calculated exclusively on taxable fee components and never on statutory taxes like STT or Stamp Duty.",
    ],
    faqs: [
      { q: "How are Indian stock market brokerage charges calculated?", a: "Brokerage is calculated either as a flat fee per order (e.g. ₹20 on Zerodha) or a percentage of trade turnover depending on your broker and segment." },
      { q: "What is STT and when is it levied?", a: "STT (Securities Transaction Tax) is a direct tax levied on all taxable securities transactions. For equity intraday, it is charged at 0.025% on the sell side only." },
      { q: "Why is GST charged at 18%?", a: "GST at 18% is applied strictly to taxable service components (brokerage commission, exchange transaction charges, and SEBI turnover fees)." },
      { q: "What is Stamp Duty?", a: "Stamp duty is a state government levy charged on the buy-side transaction value (0.003% for equity intraday, 0.015% for delivery)." },
      { q: "What are SEBI turnover charges?", a: "SEBI turnover charges are regulatory fees levied at ₹10 per crore (0.0001%) on total trade turnover." },
      { q: "Why do net break-even points matter?", a: "Break-even points show the exact price movement required just to cover all round-trip brokerage and taxes before generating actual net profit." },
      { q: "Are charges identical across all brokers like Groww and Zerodha?", a: "No. While statutory taxes (STT, Stamp Duty, GST) are uniform, broker commissions vary between flat-fee discounters and traditional percentage brokers." },
    ],
    relatedTradingSlugs: ["break-even-after-brokerage-calculator", "intraday-pnl-calculator", "equity-pnl-calculator"],
  },
  {
    slug: "break-even-after-brokerage-calculator",
    name: "Break-Even Price After Charges Calculator",
    shortDescription: "Calculate the exact ticks and exit price needed to fully recover all brokerage and regulatory taxes.",
    category: "charges-brokerage",
    renderer: "brokerage",
    keywords: ["break even after charges", "zerodha breakeven calculator", "brokerage breakeven price"],
    status: "active",
    formulaDescription: "Break-Even Exit Price = Buy Price + (Total Estimated Round-Trip Charges / Quantity)",
    formulaVariables: [
      { symbol: "Buy Price", label: "Initial execution purchase price" },
      { symbol: "Total Charges", label: "Sum of brokerage, STT, exchange fees, stamp duty, and GST" },
      { symbol: "Quantity", label: "Total number of shares traded" },
    ],
    workedExample: {
      scenario: "Buying 500 shares of an equity stock at ₹200 intraday on Zerodha.",
      inputs: { "Buy Price": "₹200.00", "Quantity": "500", "Segment": "Intraday", "Broker": "Zerodha" },
      result: "Total Round-Trip Frictions: ₹80.50 | Break-Even Points: +₹0.16 | Min Profitable Exit: ₹200.16",
      explanation: "Total round-trip charges amount to ₹80.50. Dividing by 500 shares requires a 16-paise upward move to fully absorb all taxes and breakeven.",
    },
    assumptions: [
      "Calculations evaluate round-trip buy and sell execution frictions.",
      "Assumes standard intraday broker rate schedules.",
    ],
    faqs: [
      { q: "What is a break-even price after charges?", a: "It is the minimum exit price at which your trade revenue equals your total purchase cost plus all broker commissions and statutory taxes." },
      { q: "Why is break-even higher than the buy price for long trades?", a: "Because you must pay brokerage and taxes on both entry and exit, the asset price must rise enough to cover those transaction costs." },
      { q: "How are charges factored into the break-even formula?", a: "Total estimated round-trip charges are divided by the quantity of shares and added to the buy price." },
      { q: "Does trading in larger quantities lower break-even points per share?", a: "Yes. Fixed flat brokerage fees get distributed across more shares, reducing the per-share frictional burden." },
      { q: "Is this calculator useful for scalpers?", a: "Extremely useful. Scalpers must know their precise break-even ticks before entering short-duration trades." },
    ],
    relatedTradingSlugs: ["brokerage-charges-calculator", "intraday-pnl-calculator", "equity-pnl-calculator"],
  },

  // --------------------------------------------------------------------------
  // OPTIONS TRADING TOOLS (PHASE 2A)
  // --------------------------------------------------------------------------
  {
    slug: "call-option-payoff-calculator",
    name: "Call Option Payoff Calculator",
    shortDescription: "Calculate intrinsic payoff, net profit/loss, and expiry breakeven for long and short call contracts.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["call option payoff calculator", "call option profit calculator", "long call payoff"],
    popular: true,
    status: "active",
    formulaDescription: "Long Call Net P&L = [max(Underlying Expiry Price - Strike Price, 0) - Premium] × Quantity × Multiplier",
    workedExample: {
      scenario: "Buying 1 lot (50 units) of Nifty 24,500 Call at ₹180 premium with underlying expiring at 24,800.",
      inputs: { "Strike Price": "₹24,500.00", "Option Premium": "₹180.00", "Expiry Spot Price": "₹24,800.00", "Contracts / Multiplier": "1 Lot × 50 Units" },
      result: "Gross Payoff: ₹300.00/unit | Net Profit: +₹6,000.00 | Breakeven: ₹24,680.00",
      explanation: "At 24,800, intrinsic value is ₹300 per unit. Subtracting ₹180 premium paid leaves ₹120 net profit per unit (₹6,000 total).",
    },
    assumptions: ["Calculation reflects deterministic intrinsic expiration value; pre-expiry time decay is excluded."],
    faqs: [
      { q: "What is a call option payoff?", a: "A call option payoff represents cash realization at expiration before deducting initial premium." },
      { q: "How is call option profit calculated?", a: "Profit equals intrinsic expiration value minus per-unit premium paid, multiplied by total units." },
      { q: "What is the breakeven price of a long call?", a: "Strike Price plus Premium Paid (K + P)." },
      { q: "What happens if the underlying closes below the strike at expiry?", a: "The option expires OTM with zero intrinsic value. Loss is strictly capped at premium paid." },
      { q: "What is the maximum risk on a long call?", a: "100% of the premium paid." },
      { q: "Is the risk on a short call unlimited?", a: "Yes, because there is no statutory ceiling on asset prices." },
      { q: "Does this calculator include brokerage?", a: "No. Use our Indian Brokerage Calculator for tax friction." },
    ],
    relatedTradingSlugs: ["put-option-payoff-calculator", "bull-call-spread-calculator", "options-breakeven-calculator"],
  },
  {
    slug: "put-option-payoff-calculator",
    name: "Put Option Payoff Calculator",
    shortDescription: "Calculate put option intrinsic value, expiry profit/loss, and downside breakeven price.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["put option payoff calculator", "put option profit calculator", "long put payoff"],
    popular: true,
    status: "active",
    formulaDescription: "Long Put Net P&L = [max(Strike Price - Underlying Expiry Price, 0) - Premium] × Quantity × Multiplier",
    workedExample: {
      scenario: "Buying 1 lot (50 units) of 24,500 Put at ₹180 premium with underlying expiring at 24,100.",
      inputs: { "Strike": "24,500", "Premium": "₹180", "Expiry Spot": "24,100", "Multiplier": "50" },
      result: "Intrinsic Payoff: ₹400/unit | Net Profit: +₹11,000.00 | Breakeven: ₹24,320.00",
      explanation: "Intrinsic value is ₹400. Deducting ₹180 premium yields ₹220 net profit per unit (₹11,000 total). Max profit is ₹12,16,000 if asset drops to zero.",
    },
    assumptions: ["Reflects deterministic expiration intrinsic payoff."],
    faqs: [
      { q: "What is put option payoff?", a: "The value realized at expiration from the right to sell at strike." },
      { q: "How is long put profit calculated?", a: "Intrinsic expiration value minus premium paid multiplied by units." },
      { q: "What is the breakeven price?", a: "Strike Price minus Premium Paid." },
      { q: "What is maximum profit for a long put?", a: "(Strike - Premium) × Quantity × Multiplier." },
      { q: "What is maximum loss?", a: "Strictly limited to premium paid." },
    ],
    relatedTradingSlugs: ["call-option-payoff-calculator", "bear-put-spread-calculator", "options-breakeven-calculator"],
  },
  {
    slug: "options-moneyness-calculator",
    name: "Options Moneyness & Intrinsic Value Calculator",
    shortDescription: "Determine In-The-Money (ITM), At-The-Money (ATM), and Out-of-The-Money (OTM) status and time value.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["options moneyness calculator", "itm atm otm calculator", "intrinsic value calculator"],
    status: "active",
    formulaDescription: "Call Intrinsic = max(Spot - Strike, 0) | Time Value = Premium - Intrinsic Value",
    workedExample: {
      scenario: "Nifty at 24,620 with a 24,500 Call quoting at ₹210 premium.",
      inputs: { "Spot": "24,620", "Strike": "24,500", "Premium": "₹210" },
      result: "Status: ITM | Intrinsic Value: ₹120.00 | Time Value: ₹90.00",
      explanation: "Spot exceeds strike by 120 points. Remaining ₹90 represents time value.",
    },
    assumptions: ["Options within ±0.25% of strike are classified as ATM."],
    faqs: [
      { q: "What does ITM mean?", a: "In-The-Money means the option has positive intrinsic value." },
      { q: "What does ATM mean?", a: "At-The-Money means spot equals or is extremely close to strike." },
      { q: "What does OTM mean?", a: "Out-of-The-Money means zero intrinsic value." },
      { q: "Can an ITM option still lose money?", a: "Yes, if intrinsic value is less than premium originally paid." },
    ],
    relatedTradingSlugs: ["call-option-payoff-calculator", "options-breakeven-calculator"],
  },
  {
    slug: "options-breakeven-calculator",
    name: "Options Breakeven Calculator",
    shortDescription: "Calculate the exact underlying price needed at expiry to break even on Calls and Puts.",
    category: "options",
    renderer: "options-mechanics",
    keywords: ["options breakeven calculator", "call breakeven", "put breakeven"],
    status: "active",
    formulaDescription: "Call BE = Strike + Premium | Put BE = Strike - Premium",
    workedExample: {
      scenario: "Buying 24,200 Strike Put at ₹140 premium.",
      inputs: { "Strike": "24,200", "Premium": "₹140" },
      result: "Breakeven Price: ₹24,060.00",
      explanation: "Underlying must fall below ₹24,060 for net profit.",
    },
    assumptions: ["Breakeven calculation represents expiration parity."],
    faqs: [
      { q: "How is call breakeven calculated?", a: "Strike Price plus Premium Paid." },
      { q: "How is put breakeven calculated?", a: "Strike Price minus Premium Paid." },
      { q: "Why is breakeven different from strike?", a: "Upfront premium paid requires asset to move past strike to recover cost." },
    ],
    relatedTradingSlugs: ["call-option-payoff-calculator", "put-option-payoff-calculator"],
  },

  // --------------------------------------------------------------------------
  // OPTIONS STRATEGY TOOLS (PHASE 2B)
  // --------------------------------------------------------------------------
  {
    slug: "bull-call-spread-calculator",
    name: "Bull Call Spread Calculator",
    shortDescription: "Simulate two-leg debit call spread payoffs, maximum profit caps, and net debit risk with SVG charts.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["bull call spread calculator", "call spread calculator", "vertical spread"],
    popular: true,
    status: "active",
    formulaDescription: "Max Profit = (Upper Strike - Lower Strike - Net Debit) × Qty | Max Loss = Net Debit",
    workedExample: {
      scenario: "Buy 24,500 Call at ₹190, Sell 25,000 Call at ₹60 on 50 units.",
      inputs: { "Lower Strike": "24,500", "Upper Strike": "25,000", "Net Debit": "₹130" },
      result: "Max Profit: +₹18,500.00 | Max Loss: -₹6,500.00 | Breakeven: ₹24,630.00",
      explanation: "Spread width is 500 points minus 130 debit = 370 points max profit.",
    },
    assumptions: ["Both option legs share the same underlying and expiry."],
    faqs: [
      { q: "What is a bull call spread?", a: "A defined-risk, moderately bullish two-leg strategy." },
      { q: "What is maximum profit?", a: "(Strike difference minus net debit) × quantity." },
      { q: "What is maximum loss?", a: "Strictly limited to net debit paid." },
    ],
    relatedTradingSlugs: ["bear-put-spread-calculator", "long-straddle-calculator"],
  },
  {
    slug: "bear-put-spread-calculator",
    name: "Bear Put Spread Calculator",
    shortDescription: "Simulate vertical debit put spread returns, capped downside profit, and breakeven levels.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["bear put spread calculator", "debit put spread"],
    popular: true,
    status: "active",
    formulaDescription: "Max Profit = (Upper Strike - Lower Strike - Net Debit) × Qty | Max Loss = Net Debit",
    workedExample: {
      scenario: "Buy 24,500 Put at ₹160, Sell 24,000 Put at ₹45 on 50 units.",
      inputs: { "Upper Put": "24,500", "Lower Put": "24,000", "Net Debit": "₹115" },
      result: "Max Profit: +₹19,250.00 | Max Loss: -₹5,750.00 | Breakeven: ₹24,385.00",
      explanation: "Spread generates max profit if spot closes at or below 24,000.",
    },
    assumptions: ["Both legs share identical expiry and underlying."],
    faqs: [
      { q: "What is a bear put spread?", a: "A defined-risk bearish spread strategy." },
      { q: "What is maximum profit?", a: "(Strike difference minus net debit) × units." },
    ],
    relatedTradingSlugs: ["bull-call-spread-calculator", "long-straddle-calculator"],
  },
  {
    slug: "long-straddle-calculator",
    name: "Long Straddle Payoff Calculator",
    shortDescription: "Calculate dual breakevens and unlimited volatility expansion payoffs on ATM Call + Put combinations.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["long straddle calculator", "straddle options calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Lower BE = Strike - Combined Premium | Upper BE = Strike + Combined Premium",
    workedExample: {
      scenario: "Buy 24,500 Call at ₹180 and 24,500 Put at ₹170 on 50 units.",
      inputs: { "Strike": "24,500", "Total Premium": "₹350" },
      result: "Lower BE: ₹24,150.00 | Upper BE: ₹24,850.00 | Max Loss: -₹17,500.00",
      explanation: "Profitable if underlying finishes below 24,150 or above 24,850.",
    },
    assumptions: ["Call and put opened at same strike and expiry."],
    faqs: [
      { q: "What is a long straddle?", a: "A market-neutral high volatility strategy." },
      { q: "What is maximum risk?", a: "100% of combined premium paid." },
    ],
    relatedTradingSlugs: ["iron-condor-calculator", "bull-call-spread-calculator"],
  },
  {
    slug: "iron-condor-calculator",
    name: "Iron Condor Strategy Calculator",
    shortDescription: "Model 4-leg market-neutral credit condors with defined risk wings, dual breakevens, and net credit collection.",
    category: "options-strategies",
    renderer: "options-strategy",
    keywords: ["iron condor calculator", "4 leg options strategy"],
    popular: true,
    status: "active",
    formulaDescription: "Max Profit = Net Credit | Max Loss = Wing Width - Net Credit",
    workedExample: {
      scenario: "Sell 24,100 Put & 24,800 Call; Buy 23,800 Put & 25,100 Call. Net Credit: ₹110.",
      inputs: { "Wing Width": "300 pts", "Net Credit": "₹110" },
      result: "Max Profit: +₹5,500.00 | Max Loss: -₹9,500.00 | Profit Zone: ₹23,990 to ₹24,910",
      explanation: "Retains max profit if underlying finishes between 24,100 and 24,800.",
    },
    assumptions: ["Symmetrical wing widths assumed unless customized."],
    faqs: [
      { q: "What is an iron condor?", a: "A defined-risk non-directional credit spread." },
      { q: "What is maximum profit?", a: "Net premium credit collected." },
    ],
    relatedTradingSlugs: ["long-straddle-calculator", "bull-call-spread-calculator"],
  },

  // --------------------------------------------------------------------------
  // FUTURES & LEVERAGE TOOLS (PHASE 2D)
  // --------------------------------------------------------------------------
  {
    slug: "futures-pnl-calculator",
    name: "Futures P&L Calculator",
    shortDescription: "Calculate futures trade profit, points gained, notional exposure, and return on deposited margin.",
    category: "futures-leverage",
    renderer: "futures",
    keywords: ["futures pnl calculator", "nifty futures calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Futures P&L = (Exit Price - Entry Price) × Quantity Lots × Lot Size",
    workedExample: {
      scenario: "Buying 2 Lots of Nifty Futures (100 units) at 24,500 and squaring off at 24,750.",
      inputs: { "Entry": "24,500", "Exit": "24,750", "Lots": "2", "Lot Size": "50" },
      result: "Points: +250.00 pts | Realized P&L: +₹25,000.00 | Notional: ₹24,50,000.00",
      explanation: "A 250-point gain across 100 units yields ₹25,000 gross gain.",
    },
    assumptions: ["Evaluates gross trade P&L; statutory exchange fees computed separately."],
    faqs: [
      { q: "How is futures P&L calculated?", a: "Points gained/lost multiplied by total underlying units (Lots × Lot Size)." },
      { q: "What is contract notional value?", a: "Price × Lot Size × Lots." },
    ],
    relatedTradingSlugs: ["futures-margin-calculator", "liquidation-price-calculator"],
  },
  {
    slug: "futures-margin-calculator",
    name: "Futures Margin & Leverage Calculator",
    shortDescription: "Determine initial SPAN + Exposure margin requirements, effective leverage, and margin utilization.",
    category: "futures-leverage",
    renderer: "futures",
    keywords: ["futures margin calculator", "span margin calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Initial Margin = Notional Value × Margin Rate % | Leverage = 100 / Margin %",
    workedExample: {
      scenario: "Contract price ₹24,500, lot size 50, 2 lots at 12% statutory margin with ₹4L equity.",
      inputs: { "Notional": "₹24,50,000", "Margin Rate": "12.0%", "Equity": "₹4,00,000" },
      result: "Margin Required: ₹2,94,000.00 | Leverage: 8.3x | Utilization: 73.5%",
      explanation: "A ₹2.94L deposit controls ₹24.50L notional exposure.",
    },
    assumptions: ["Margin rate reflects combined SPAN and exposure requirements."],
    faqs: [
      { q: "What is initial margin in futures?", a: "Minimum capital required to hold an open futures position." },
      { q: "What is SPAN margin?", a: "Exchange risk-analysis algorithm calculating portfolio risk." },
    ],
    relatedTradingSlugs: ["futures-pnl-calculator", "liquidation-price-calculator"],
  },
  {
    slug: "liquidation-price-calculator",
    name: "Estimated Liquidation Price Calculator",
    shortDescription: "Estimate liquidation price based on leverage multiplier and maintenance margin buffer.",
    category: "futures-leverage",
    renderer: "futures",
    keywords: ["liquidation price calculator", "crypto liquidation calculator"],
    status: "active",
    formulaDescription: "Long Liq = Entry × [1 - (1 / Leverage) + Maintenance Margin %]",
    workedExample: {
      scenario: "Long position entered at ₹24,500 with 10x leverage and 0.5% maintenance margin.",
      inputs: { "Entry": "₹24,500", "Leverage": "10x", "Maintenance": "0.5%" },
      result: "Estimated Liquidation Price: ₹22,172.50 (-9.50% adverse move threshold)",
      explanation: "A 9.50% drop consumes equity buffer down to maintenance threshold.",
    },
    assumptions: ["Assumes isolated margin rules."],
    faqs: [
      { q: "What is a liquidation price?", a: "Price at which losses deplete margin buffer, forcing broker to close position." },
      { q: "How does higher leverage affect liquidation?", a: "Moves liquidation price significantly closer to entry." },
    ],
    relatedTradingSlugs: ["futures-margin-calculator", "position-size-calculator"],
  },

  // --------------------------------------------------------------------------
  // 5. FOREX & CRYPTO TOOLS
  // --------------------------------------------------------------------------
  {
    slug: "forex-pip-value-calculator",
    name: "Forex Pip Value Calculator",
    shortDescription: "Calculate cash value per pip across standard, mini, and micro lots in local account currency.",
    category: "forex-crypto",
    renderer: "forex",
    keywords: ["forex pip value calculator", "pip calculator"],
    popular: true,
    status: "active",
    formulaDescription: "Pip Value = Lots × Contract Units × Pip Decimal Size × Exchange Rate",
    workedExample: {
      scenario: "1 Standard Lot on EUR/USD (0.0001 pip) with USD/INR at 85.50.",
      inputs: { "Lots": "1.0", "Pip Size": "0.0001", "FX Rate": "85.50" },
      result: "Pip Value: $10.00 / pip (₹855.00 INR per pip)",
      explanation: "Each 1-pip move creates an ₹855 equity change on 1 standard lot.",
    },
    assumptions: ["Reflects pure pip valuation without broker spreads."],
    faqs: [
      { q: "What is a pip in Forex?", a: "Smallest standard price move, usually 0.0001." },
      { q: "Why is JPY pip size different?", a: "JPY pairs are quoted to two decimals (0.01)." },
    ],
    relatedTradingSlugs: ["forex-position-size-calculator", "position-size-calculator"],
  },
  {
    slug: "forex-position-size-calculator",
    name: "Forex Lot Size & Risk Calculator",
    shortDescription: "Determine exact lot sizing to ensure risk remains fixed to 1% of account capital.",
    category: "forex-crypto",
    renderer: "forex",
    keywords: ["forex position size calculator", "forex lot size calculator"],
    status: "active",
    formulaDescription: "Allowable Lots = (Account Capital × Risk %) / (Stop Loss Pips × Pip Value)",
    workedExample: {
      scenario: "₹1,00,000 account risking 1.5% with a 25-pip stop loss on USD/INR.",
      inputs: { "Capital": "₹1,00,000", "Risk %": "1.5%", "Stop": "25 Pips" },
      result: "Allowable Lot Size: 0.07 Standard Lots | Max Risk: ₹1,500.00",
      explanation: "Trading 0.07 lots ensures a 25-pip adverse move limits total loss to ₹1,500.",
    },
    assumptions: ["Assumes uniform execution at stop-loss without price gaps."],
    faqs: [
      { q: "How is Forex position size calculated?", a: "Cash risk budget divided by stop loss pips multiplied by pip value." },
    ],
    relatedTradingSlugs: ["forex-pip-value-calculator", "position-size-calculator"],
  },
  {
    slug: "crypto-dca-calculator",
    name: "Crypto DCA (Dollar-Cost Averaging) Calculator",
    shortDescription: "Calculate weighted average buy price and accumulated coin holdings across recurring purchase orders.",
    category: "forex-crypto",
    renderer: "crypto",
    keywords: ["crypto dca calculator", "bitcoin dca calculator"],
    popular: true,
    status: "active",
    formulaDescription: "DCA Average Price = Total Fiat Capital Invested / Total Coin Tokens Acquired",
    workedExample: {
      scenario: "Buying ₹50,000 of Bitcoin at ₹55,00,000 and ₹50,00,000 at ₹50,00,000.",
      inputs: { "Buy 1": "₹50k @ ₹55L", "Buy 2": "₹50k @ ₹50L" },
      result: "Total Invested: ₹1,00,000.00 | Average Cost: ₹52,380.95",
      explanation: "Buying the dip pulls the volume-weighted average below the arithmetic midpoint.",
    },
    assumptions: ["Prices and values reflect user-entered purchases."],
    faqs: [
      { q: "What is Dollar-Cost Averaging?", a: "Investing a fixed cash amount at regular intervals regardless of price." },
      { q: "Does DCA guarantee profit?", a: "No, if the asset declines indefinitely." },
    ],
    relatedTradingSlugs: ["average-price-calculator", "position-size-calculator"],
  },
];

export function getTradingToolBySlug(slug: string): TradingToolDefinition | undefined {
  return TRADING_TOOLS.find((t) => t.slug === slug);
}

export function getTradingToolsByCategory(cat: TradingCategory): TradingToolDefinition[] {
  return TRADING_TOOLS.filter((t) => t.category === cat);
}

export function getAllTradingTools(): TradingToolDefinition[] {
  return TRADING_TOOLS;
}
