export type CalculatorCategory =
  | "finance"
  | "business"
  | "math"
  | "health"
  | "time-date"
  | "converters"
  | "education"
  | "other";

export interface WorkedExample {
  scenario: string;
  inputs: Record<string, string>;
  result: string;
  explanation: string;
}

export interface CalculatorMeta {
  id: string;
  slug: string;
  name: string;
  category: CalculatorCategory;
  description: string;
  keywords: string[];
  popular?: boolean;
  featured?: boolean;
  lastUpdated?: string;
  formulaDescription?: string;
  formulaVariables?: { symbol: string; label: string }[];
  workedExample?: WorkedExample;
  assumptions?: string[];
  relatedCalculators?: string[];
  faqs?: { q: string; a: string }[];
}

export const CATEGORIES_META: Record<
  CalculatorCategory,
  { name: string; title: string; description: string; icon: string; longIntro: string }
> = {
  finance: {
    name: "Finance",
    title: "Finance & Loan Calculators",
    description: "Loans, investments, taxes, retirement, and savings calculators for Indian & global users.",
    icon: "TrendingUp",
    longIntro: "Plan personal loans, mortgages, mutual fund SIPs, fixed deposits, and statutory tax liabilities with deterministic, browser-native mathematical formulas.",
  },
  business: {
    name: "Business",
    title: "Business & Freelance Calculators",
    description: "Profit margins, ROAS, hourly rates, payroll, invoices, and break-even models.",
    icon: "Briefcase",
    longIntro: "Calculate ad spend returns (ROAS), hourly freelance billing rates, commercial break-even volumes, and corporate payroll deductions.",
  },
  math: {
    name: "Math",
    title: "Math & Percentage Calculators",
    description: "Percentages, discounts, markup, fractions, statistical averages, and ratios.",
    icon: "Percent",
    longIntro: "Resolve multi-step percentage changes, coupon discounts, retail markups, arithmetic means, and proportion scales instantly.",
  },
  health: {
    name: "Health",
    title: "Health & Fitness Calculators",
    description: "BMI, BMR, calorie maintenance, ideal weight, body fat, and hydration goals.",
    icon: "HeartPulse",
    longIntro: "Reference biometric estimates including Body Mass Index (BMI), Basal Metabolic Rate (BMR), and daily hydration guidelines.",
  },
  "time-date": {
    name: "Time & Date",
    title: "Time & Date Calculators",
    description: "Age calculations, date differences, duration tracking, and global timezones.",
    icon: "Clock",
    longIntro: "Compute chronological age, working days between calendar milestones, shift hours, and coordinated universal time (UTC/IST) offsets.",
  },
  converters: {
    name: "Unit Converters",
    title: "Unit & Measurement Converters",
    description: "Instant unit converters for length, weight, area, volume, temperature, and speed.",
    icon: "Scale",
    longIntro: "Convert metric and imperial units across distance, mass, land area (including Indian Bigha/Guntha), volume, and temperature scales.",
  },
  education: {
    name: "Education",
    title: "Education & Grading Calculators",
    description: "CGPA to percentage, GPA scales, exam marks, and academic grading conversions.",
    icon: "GraduationCap",
    longIntro: "Convert 10-point Indian CGPA scores to marks percentage (AICTE/CBSE formula) and compute semester weighted GPA standings.",
  },
  other: {
    name: "Other Tools",
    title: "Everyday Utility Calculators",
    description: "Fuel expenses, vehicle mileage, electricity power bills, tip splits, and countdowns.",
    icon: "Calculator",
    longIntro: "Calculate road trip fuel budgets, appliance electricity wattages, restaurant tip shares, and event countdown timers.",
  },
};

export const CATEGORIES = Object.keys(CATEGORIES_META) as CalculatorCategory[];

export const CALCULATORS: CalculatorMeta[] = [
  // ==========================================
  // 1. FINANCE CALCULATORS
  // ==========================================
  {
    id: "emi-calculator",
    slug: "emi-calculator",
    name: "EMI Calculator",
    category: "finance",
    description: "Calculate monthly loan EMI, total interest payable, and full yearly amortization schedule.",
    keywords: ["emi calculator", "loan emi", "home loan emi", "car loan emi", "monthly installment"],
    popular: true,
    featured: true,
    lastUpdated: "August 2026",
    formulaDescription: "EMI = [P × r × (1 + r)^n] / [(1 + r)^n - 1]",
    formulaVariables: [
      { symbol: "P", label: "Principal Loan Amount" },
      { symbol: "r", label: "Monthly Interest Rate (Annual Rate / 12 / 100)" },
      { symbol: "n", label: "Loan Tenure in Total Months (Years × 12)" },
    ],
    workedExample: {
      scenario: "Home Loan of ₹25,00,000 at 8.5% annual interest for 20 years",
      inputs: { "Loan Amount": "₹25,00,000", "Interest Rate": "8.5%", "Tenure": "20 Years (240 Months)" },
      result: "Monthly EMI: ₹21,696 | Total Interest: ₹27,06,939 | Total Repayment: ₹52,06,939",
      explanation: "Using monthly reducing balance compounding, the monthly installment settles at ₹21,696 with the principal component increasing every year.",
    },
    assumptions: [
      "Interest is calculated on a monthly reducing balance basis.",
      "Monthly interest rate equals Annual Rate / 1200.",
      "Repayments occur at standard regular monthly intervals without partial prepayments.",
    ],
    relatedCalculators: ["home-loan-emi-calculator", "car-loan-emi-calculator", "personal-loan-emi-calculator", "ltv-calculator", "salary-calculator"],
    faqs: [
      { q: "How is loan EMI calculated?", a: "EMI is computed using the reducing balance formula taking principal loan amount, monthly interest rate, and total monthly installments into account." },
      { q: "Does extending tenure increase total interest?", a: "Yes. Longer loan tenures reduce your monthly installment amount but significantly increase overall compound interest paid across the lifetime of the loan." },
      { q: "What happens if interest rates change?", a: "For floating-rate loans, an increase in benchmark interest rate generally increases the loan tenure or monthly EMI amount." },
    ],
  },
  {
    id: "upwork-net-earnings-calculator",
    slug: "upwork-net-earnings-calculator",
    name: "Upwork Net Earnings & Tax Calculator",
    category: "finance",
    description: "Calculate your exact take-home pay on Upwork after freelancer service fees, Indian Section 194-O TDS, forex conversion, and withdrawal charges.",
    keywords: ["upwork fee calculator", "upwork earnings calculator", "upwork tds calculator", "upwork net income", "freelance take home calculator"],
    popular: true,
    featured: true,
    lastUpdated: "August 2026",
    formulaDescription: "Net Payout = Gross Invoice - [Service Fee + Estimated TDS + (Post-Fee Amount × FX %) + Withdrawal Fee + Other Expenses]",
    formulaVariables: [
      { symbol: "Gross Invoice", label: "Total Client Billed Invoice Amount" },
      { symbol: "Service Fee", label: "Gross Invoice × Upwork Fee Rate % (e.g. 10%)" },
      { symbol: "Post-Fee Amount", label: "Gross Invoice - Upwork Service Fee" },
      { symbol: "Estimated TDS", label: "Gross Invoice × Section 194-O Rate % (1% standard, 5% non-compliant)" },
      { symbol: "FX Spread", label: "Post-Fee Amount × Currency Conversion Rate %" },
      { symbol: "Withdrawal Fee", label: "Fixed Bank Transfer / Withdrawal Charge" },
    ],
    workedExample: {
      scenario: "$1,000 Upwork Contract with 10% Service Fee, 1% Indian TDS, 1.5% FX Spread, and $0.99 Direct Bank Withdrawal Fee",
      inputs: { "Gross Invoice": "$1,000.00", "Upwork Service Fee": "10% ($100.00)", "Estimated TDS (194-O)": "1% ($10.00)", "Withdrawal + FX": "$14.49 ($0.99 + $13.50)" },
      result: "Gross Invoice: $1,000.00 | Upwork Fee: -$100.00 | Estimated TDS: -$10.00 | Withdrawal + FX: -$14.49 | Net Take-Home: $875.51",
      explanation: "From the $1,000 invoice, Upwork deducts a $100 service fee (leaving $900), $10 estimated TDS on gross billings, and $14.49 for forex spread (1.5% of $900) plus withdrawal fee ($0.99), resulting in $875.51 net payout.",
    },
    assumptions: [
      "Upwork service fee rate is fully configurable (10% standard, 5%, 0%, 15%).",
      "Section 194-O TDS is computed directly on gross client billing value (1% with PAN, 5% without).",
      "FX conversion spread applies to post-service fee earnings when transferring to local currency.",
    ],
    relatedCalculators: ["fiverr-net-earnings-calculator", "freelance-hourly-rate", "salary-calculator", "income-tax-calculator"],
    faqs: [
      { q: "How much does Upwork take from freelancers?", a: "Upwork charges a standard flat 10% freelancer service fee on all eligible contracts." },
      { q: "What is Section 194-O TDS for Indian Upwork freelancers?", a: "Under Indian Tax Laws, Upwork withholds 1% TDS on gross client billings for freelancers with a valid PAN on file." },
      { q: "Can I claim a refund for Upwork TDS?", a: "Yes, TDS withheld is deposited with the Income Tax Department and appears in Form 26AS/AIS, which you can claim back or offset during annual ITR filing." },
    ],
  },
  {
    id: "fiverr-net-earnings-calculator",
    slug: "fiverr-net-earnings-calculator",
    name: "Fiverr Net Earnings & Tax Calculator",
    category: "finance",
    description: "Calculate your net profit from Fiverr gig sales, extras, and tips after 20% seller fees, Indian TDS withholding, and bank withdrawal fees.",
    keywords: ["fiverr fee calculator", "fiverr earnings calculator", "fiverr net payout", "fiverr seller tax calculator", "fiverr reverse pricing"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "Net Payout = Gross Order - [Fiverr Fee + Estimated TDS + (Post-Platform Amount × FX %) + Withdrawal Fee + Other Expenses]",
    formulaVariables: [
      { symbol: "Gross Order", label: "Gig Price + Extras + Tips - Refunds" },
      { symbol: "Fiverr Fee", label: "Gross Order × Platform Commission % (20%)" },
      { symbol: "Post-Platform Amount", label: "Gross Order - Fiverr Commission" },
      { symbol: "Estimated TDS", label: "Gross Order × TDS Rate % (1%)" },
      { symbol: "FX Spread", label: "Post-Platform Amount × FX Conversion Rate %" },
      { symbol: "Withdrawal Fee", label: "Fixed Bank Transfer / Withdrawal Charge" },
    ],
    workedExample: {
      scenario: "$150 Total Fiverr Order ($100 Base + $30 Extras + $20 Tip) with 20% Commission, 1% TDS, 2% FX Spread, and $1.00 Withdrawal Fee",
      inputs: { "Gross Order Value": "$150.00", "Fiverr Commission (20%)": "$30.00", "Post-Platform Amount": "$120.00", "Estimated TDS (1%)": "$1.50", "Withdrawal + FX": "$3.40 ($1.00 + $2.40)" },
      result: "Gross Order: $150.00 | Total Deductions: -$34.90 | Net In-Pocket: $115.10 | Net Margin: 76.73%",
      explanation: "Fiverr retains 20% ($30.00) from the $150 order. From the remaining $120 balance, $1.50 estimated TDS, $2.40 FX spread (2% of $120), and $1.00 withdrawal fee are deducted, leaving $115.10 net earnings.",
    },
    assumptions: [
      "Fiverr seller commission is standard 20% across all order components including tips.",
      "Statutory tax withholding and bank withdrawal fees vary based on account location and payout channel.",
    ],
    relatedCalculators: ["upwork-net-earnings-calculator", "freelance-hourly-rate", "payment-gateway-fee-calculator", "profit-loss-calculator"],
    faqs: [
      { q: "Does Fiverr take 20% from tips?", a: "Yes, Fiverr charges a 20% commission on the entire order amount including buyer tips and gig extras." },
      { q: "How do I calculate what to charge to receive an exact amount on Fiverr?", a: "Use the reverse calculation mode: Required Charge = (Desired Net + Fixed Fees) / [1 - (Platform Rate + TDS Rate + FX Rate × (1 - Platform Rate))]." },
    ],
  },
  {
    id: "home-loan-emi-calculator",
    slug: "home-loan-emi-calculator",
    name: "Home Loan EMI Calculator",
    category: "finance",
    description: "Plan your housing loan monthly installments, interest rates, and total payable interest.",
    keywords: ["home loan emi", "housing loan calculator", "mortgage calculator india"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "EMI = [P × r × (1 + r)^n] / [(1 + r)^n - 1]",
    relatedCalculators: ["emi-calculator", "ltv-calculator", "loan-calculator", "hra-calculator"],
    faqs: [
      { q: "Can I claim tax deductions on home loan EMI?", a: "Yes, under the Old Tax Regime in India, you can claim principal repayment under Section 80C (up to ₹1.5 Lakh) and interest payment under Section 24(b) (up to ₹2 Lakh for self-occupied property)." },
    ],
  },
  {
    id: "car-loan-emi-calculator",
    slug: "car-loan-emi-calculator",
    name: "Car Loan EMI Calculator",
    category: "finance",
    description: "Calculate auto loan monthly payments, tenure interest, and down payment ratios.",
    keywords: ["car loan emi", "auto loan calculator", "vehicle financing"],
    lastUpdated: "August 2026",
    formulaDescription: "EMI = [P × r × (1 + r)^n] / [(1 + r)^n - 1]",
    relatedCalculators: ["emi-calculator", "personal-loan-emi-calculator", "loan-calculator"],
  },
  {
    id: "personal-loan-emi-calculator",
    slug: "personal-loan-emi-calculator",
    name: "Personal Loan EMI Calculator",
    category: "finance",
    description: "Compute personal loan installments and effective borrowing costs across Indian banks.",
    keywords: ["personal loan emi", "instant loan calculator", "unsecured loan interest"],
    lastUpdated: "August 2026",
    formulaDescription: "EMI = [P × r × (1 + r)^n] / [(1 + r)^n - 1]",
    relatedCalculators: ["emi-calculator", "loan-calculator", "simple-interest-calculator"],
  },
  {
    id: "sip-calculator",
    slug: "sip-calculator",
    name: "SIP Calculator",
    category: "finance",
    description: "Project mutual fund Systematic Investment Plan (SIP) returns and compound wealth creation.",
    keywords: ["sip calculator", "mutual fund returns", "systematic investment plan", "wealth builder"],
    popular: true,
    featured: true,
    lastUpdated: "August 2026",
    formulaDescription: "FV = P × [ (1 + i)^n - 1 ] / i × (1 + i)",
    formulaVariables: [
      { symbol: "P", label: "Monthly Deposit Amount" },
      { symbol: "i", label: "Monthly Expected Return Rate (Annual Rate / 12 / 100)" },
      { symbol: "n", label: "Total Number of Monthly Installments (Years × 12)" },
    ],
    workedExample: {
      scenario: "Monthly SIP of ₹10,000 for 15 years at an expected annual return of 12%",
      inputs: { "Monthly Deposit": "₹10,000", "Expected Return": "12% p.a.", "Investment Period": "15 Years" },
      result: "Total Deposited: ₹18,00,000 | Estimated Capital Gains: ₹32,45,760 | Maturity Corpus: ₹50,45,760",
      explanation: "Compounding returns reinvest month-over-month, yielding estimated capital growth of over 1.8x the total deposited capital.",
    },
    assumptions: [
      "Investments are deposited systematically at regular monthly intervals.",
      "Compounding frequency matches deposit frequency (monthly compounding).",
      "Expected rate of return is an annualized constant estimate and not guaranteed.",
    ],
    relatedCalculators: ["lumpsum-calculator", "cagr-calculator", "mutual-fund-returns-calculator", "compound-interest-calculator"],
    faqs: [
      { q: "How are SIP returns calculated?", a: "SIP uses monthly compounding on each installment where earlier deposits accumulate returns for longer durations." },
      { q: "Are SIP returns guaranteed?", a: "No. Mutual fund investments are subject to market risks. The expected return rate is an annualized projection." },
      { q: "What is the difference between SIP and Lump Sum?", a: "SIP invests fixed amounts at regular intervals to average market volatility, while Lump Sum invests the entire capital at once." },
    ],
  },
  {
    id: "lumpsum-calculator",
    slug: "lumpsum-calculator",
    name: "Lumpsum Calculator",
    category: "finance",
    description: "Estimate one-time mutual fund investment returns over long-term compounding horizons.",
    keywords: ["lumpsum calculator", "one time mutual fund investment", "wealth growth"],
    lastUpdated: "August 2026",
    formulaDescription: "FV = P × (1 + r)^n",
    relatedCalculators: ["sip-calculator", "cagr-calculator", "compound-interest-calculator", "fd-calculator"],
  },
  {
    id: "gst-calculator",
    slug: "gst-calculator",
    name: "GST Calculator",
    category: "finance",
    description: "Calculate GST Inclusive and Exclusive amounts with 5%, 12%, 18%, 28% slabs and CGST/SGST/IGST splits.",
    keywords: ["gst calculator", "goods and services tax", "gst inclusive", "gst exclusive", "cgst sgst igst"],
    popular: true,
    featured: true,
    lastUpdated: "August 2026",
    formulaDescription: "GST Exclusive = Base × Rate / 100 | GST Inclusive Base = Total / (1 + Rate / 100)",
    formulaVariables: [
      { symbol: "Base", label: "Pre-tax Supply Value" },
      { symbol: "Rate", label: "Applicable GST Slab Percentage (5%, 12%, 18%, 28%)" },
      { symbol: "Total", label: "Gross Inclusive Final Amount" },
    ],
    workedExample: {
      scenario: "Adding 18% GST on a base professional consulting service of ₹50,000 (Intra-State)",
      inputs: { "Base Value": "₹50,00,000", "GST Rate": "18%", "Supply Type": "Intra-State" },
      result: "Total GST: ₹9,000 (CGST ₹4,500 + SGST ₹4,500) | Grand Invoice Total: ₹59,000",
      explanation: "Intra-state supply splits 18% tax equally between Central GST (9%) and State GST (9%).",
    },
    assumptions: [
      "Intra-state transactions split GST equally between CGST (50%) and SGST (50%).",
      "Inter-state supplies apply full GST under IGST (100%).",
    ],
    relatedCalculators: ["invoice-total-calculator", "profit-loss-calculator", "percentage-calculator", "discount-calculator"],
    faqs: [
      { q: "What is GST exclusive pricing?", a: "GST exclusive adds the tax percentage on top of the net base supply amount." },
      { q: "What is GST inclusive pricing?", a: "GST inclusive extracts the embedded tax amount from the final gross selling price." },
      { q: "What is the difference between CGST, SGST, and IGST?", a: "CGST and SGST apply to transactions within the same state, while IGST applies to inter-state supplies." },
    ],
  },
  {
    id: "income-tax-calculator",
    slug: "income-tax-calculator",
    name: "Income Tax Calculator",
    category: "finance",
    description: "Calculate estimated income tax liability under AY 2026-27 and AY 2025-26 New & Old Tax Regimes.",
    keywords: ["income tax calculator", "new tax regime", "old tax regime", "tds calculation", "itr planning"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "Taxable Income = Gross Income - Standard Deduction - Exemptions | Net Tax = Slab Tax - 87A Rebate + 4% Cess",
    workedExample: {
      scenario: "Salaried employee earning ₹12,00,000 under AY 2026-27 New Tax Regime",
      inputs: { "Gross Income": "₹12,00,000", "Assessment Year": "AY 2026-27", "Regime": "New Tax Regime" },
      result: "Standard Deduction: ₹75,000 | Taxable Income: ₹11,25,000 | Slab Tax: ₹52,500 | Section 87A Rebate: ₹52,500 | Net Tax Payable: ₹0",
      explanation: "Section 87A rebate absorbs total computed tax up to ₹12,00,000 taxable income, resulting in zero net tax.",
    },
    assumptions: [
      "Salaried standard deduction of ₹75,000 applies under the New Tax Regime.",
      "Section 87A rebate provides full tax relief for eligible resident individuals with total income up to ₹12,00,000.",
      "Health & Education cess is uniformly applied at 4% on net income tax.",
    ],
    relatedCalculators: ["salary-calculator", "hra-calculator", "tds-calculator", "ppf-calculator", "gratuity-calculator"],
    faqs: [
      { q: "What is the standard deduction for AY 2026-27 in New Regime?", a: "The standard deduction for salaried individuals in the New Tax Regime is ₹75,000." },
      { q: "Is tax zero up to ₹12 Lakhs in the New Tax Regime?", a: "For eligible resident individuals, Section 87A provides a rebate of income tax where total income does not exceed ₹12,00,000 under the AY 2026-27 New Tax Regime." },
      { q: "Which tax regime should I choose?", a: "The New Tax Regime offers lower slab rates without exemptions, while the Old Tax Regime allows deductions like Section 80C, 80D, and HRA." },
    ],
  },
  {
    id: "salary-calculator",
    slug: "salary-calculator",
    name: "Salary (In-Hand) Calculator",
    category: "finance",
    description: "Calculate monthly take-home salary from Annual CTC after EPF, Professional Tax, and TDS deductions.",
    keywords: ["salary calculator", "in hand salary", "take home pay", "ctc to in hand", "payroll deductions"],
    popular: true,
    featured: true,
    lastUpdated: "August 2026",
    formulaDescription: "Net Monthly In-Hand = Gross Monthly Salary - (Employee PF + Professional Tax + Monthly TDS + Other Deductions)",
    workedExample: {
      scenario: "Annual CTC of ₹12,00,000 with standard 50% Basic pay structure",
      inputs: { "Annual CTC": "₹12,00,000", "Monthly PF": "₹1,800", "Professional Tax": "₹200", "Monthly TDS": "₹4,500" },
      result: "Monthly Gross: ₹98,200 | Monthly Deductions: ₹6,500 | Net Take-Home Salary: ₹91,700 / month",
      explanation: "Employer contributions are separated from gross salary, and statutory deductions are withheld to produce net in-pocket pay.",
    },
    assumptions: [
      "CTC-to-take-home calculations are estimates because employer CTC structures differ.",
      "Statutory EPF deduction is 12% of basic pay (capped at ₹1,800/mo standard).",
      "Professional tax is estimated at standard ₹200/month (₹2,400/year).",
    ],
    relatedCalculators: ["income-tax-calculator", "salary-hike-calculator", "payroll-calculator", "hra-calculator", "epf-calculator"],
    faqs: [
      { q: "What is the difference between CTC and take-home salary?", a: "CTC is the total cost to the company including employer benefits (PF, gratuity, insurance). Take-home is the net amount credited after employee deductions." },
      { q: "Does CTC include employer PF?", a: "Yes, most employer CTC structures bundle the employer's 12% PF contribution inside the headline CTC." },
    ],
  },
  {
    id: "fd-calculator",
    slug: "fd-calculator",
    name: "Fixed Deposit (FD) Calculator",
    category: "finance",
    description: "Calculate bank Fixed Deposit maturity value, compound interest, and tenure yield.",
    keywords: ["fd calculator", "fixed deposit interest", "bank fd rates", "maturity corpus"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "A = P × (1 + r / n)^(n × t)",
    relatedCalculators: ["rd-calculator", "compound-interest-calculator", "simple-interest-calculator", "ppf-calculator"],
    faqs: [
      { q: "How is FD interest compounded?", a: "Most Indian banks compound FD interest on a quarterly basis, adding earned interest back to the principal every 3 months." },
    ],
  },
  {
    id: "rd-calculator",
    slug: "rd-calculator",
    name: "Recurring Deposit (RD) Calculator",
    category: "finance",
    description: "Calculate maturity returns on monthly recurring deposits with compound interest compounding.",
    keywords: ["rd calculator", "recurring deposit interest", "post office rd", "monthly savings"],
    lastUpdated: "August 2026",
    relatedCalculators: ["fd-calculator", "sip-calculator", "savings-calculator"],
  },
  {
    id: "ppf-calculator",
    slug: "ppf-calculator",
    name: "PPF Calculator",
    category: "finance",
    description: "Calculate Public Provident Fund 15-year tax-free compounding interest and maturity corpus.",
    keywords: ["ppf calculator", "public provident fund", "tax free return", "section 80c"],
    popular: true,
    lastUpdated: "August 2026",
    relatedCalculators: ["epf-calculator", "nps-calculator", "fd-calculator", "income-tax-calculator"],
  },
  {
    id: "epf-calculator",
    slug: "epf-calculator",
    name: "EPF Calculator",
    category: "finance",
    description: "Project retirement corpus from employee and employer monthly Employee Provident Fund contributions.",
    keywords: ["epf calculator", "provident fund corpus", "pf balance check", "retirement fund"],
    lastUpdated: "August 2026",
    relatedCalculators: ["ppf-calculator", "epf-passbook-calculator", "gratuity-calculator", "salary-calculator"],
  },
  {
    id: "epf-passbook-calculator",
    slug: "epf-passbook-calculator",
    name: "EPF Passbook Balance Calculator",
    category: "finance",
    description: "Calculate accumulated PF interest and employee-employer ledger balance projections.",
    keywords: ["epf passbook", "pf interest calculation", "epfo balance"],
    lastUpdated: "August 2026",
    relatedCalculators: ["epf-calculator", "ppf-calculator", "salary-calculator"],
  },
  {
    id: "nps-calculator",
    slug: "nps-calculator",
    name: "NPS Calculator",
    category: "finance",
    description: "Calculate National Pension Scheme retirement corpus, monthly annuity payout, and tax benefits.",
    keywords: ["nps calculator", "national pension system", "pension annuity", "retirement corpus"],
    lastUpdated: "August 2026",
    relatedCalculators: ["epf-calculator", "ppf-calculator", "sip-calculator"],
  },
  {
    id: "hra-calculator",
    slug: "hra-calculator",
    name: "HRA Exemption Calculator",
    category: "finance",
    description: "Calculate tax-exempt House Rent Allowance (HRA) under Section 10(13A) of the Income Tax Act.",
    keywords: ["hra calculator", "house rent allowance exemption", "section 10 13a", "rent tax save"],
    lastUpdated: "August 2026",
    relatedCalculators: ["income-tax-calculator", "salary-calculator", "rent-split-calculator"],
  },
  {
    id: "gratuity-calculator",
    slug: "gratuity-calculator",
    name: "Gratuity Calculator",
    category: "finance",
    description: "Estimate statutory gratuity payout based on last drawn basic salary and completed service years.",
    keywords: ["gratuity calculator", "gratuity act 1972", "retirement gratuity payout"],
    lastUpdated: "August 2026",
    relatedCalculators: ["salary-calculator", "epf-calculator", "payroll-calculator"],
  },
  {
    id: "tds-calculator",
    slug: "tds-calculator",
    name: "TDS Calculator",
    category: "finance",
    description: "Calculate Tax Deducted at Source across salary, professional fees, contractor payments, and rent.",
    keywords: ["tds calculator", "tax deducted at source", "194j 194c", "tds rate"],
    lastUpdated: "August 2026",
    relatedCalculators: ["income-tax-calculator", "salary-calculator", "gst-calculator"],
  },
  {
    id: "cagr-calculator",
    slug: "cagr-calculator",
    name: "CAGR Calculator",
    category: "finance",
    description: "Compute Compound Annual Growth Rate for stock market, real estate, and portfolio investments.",
    keywords: ["cagr calculator", "compound annual growth rate", "investment annual yield"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "CAGR = (Final Value / Initial Value)^(1 / Years) - 1",
    relatedCalculators: ["sip-calculator", "lumpsum-calculator", "roi-calculator", "compound-interest-calculator"],
  },
  {
    id: "compound-interest-calculator",
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    category: "finance",
    description: "Calculate compound interest with annual, quarterly, monthly, and daily compounding frequencies.",
    keywords: ["compound interest calculator", "compound interest formula", "wealth growth"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "A = P × (1 + r / n)^(n × t)",
    relatedCalculators: ["simple-interest-calculator", "fd-calculator", "cagr-calculator"],
  },
  {
    id: "simple-interest-calculator",
    slug: "simple-interest-calculator",
    name: "Simple Interest Calculator",
    category: "finance",
    description: "Calculate simple interest on principal loans and short-term debt agreements instantly.",
    keywords: ["simple interest calculator", "si formula", "flat interest"],
    lastUpdated: "August 2026",
    formulaDescription: "SI = (P × R × T) / 100",
    relatedCalculators: ["compound-interest-calculator", "loan-calculator", "emi-calculator"],
  },
  {
    id: "loan-calculator",
    slug: "loan-calculator",
    name: "Loan Calculator",
    category: "finance",
    description: "General loan repayment, total interest, and installment duration estimator.",
    keywords: ["loan calculator", "bank loan repayment", "finance interest"],
    lastUpdated: "August 2026",
    relatedCalculators: ["emi-calculator", "ltv-calculator", "home-loan-emi-calculator"],
  },
  {
    id: "roi-calculator",
    slug: "roi-calculator",
    name: "ROI (Return on Investment) Calculator",
    category: "finance",
    description: "Measure efficiency and percentage profitability of financial and business investments.",
    keywords: ["roi calculator", "return on investment", "profitability ratio"],
    lastUpdated: "August 2026",
    formulaDescription: "ROI (%) = [(Net Gain - Cost of Investment) / Cost of Investment] × 100",
    relatedCalculators: ["cagr-calculator", "roas-calculator", "profit-loss-calculator"],
  },
  {
    id: "inflation-calculator",
    slug: "inflation-calculator",
    name: "Inflation Calculator",
    category: "finance",
    description: "Calculate future purchasing power and price inflation adjustments over time.",
    keywords: ["inflation calculator", "purchasing power", "cost of living increase"],
    lastUpdated: "August 2026",
    relatedCalculators: ["sip-calculator", "cagr-calculator", "savings-calculator"],
  },
  {
    id: "mutual-fund-returns-calculator",
    slug: "mutual-fund-returns-calculator",
    name: "Mutual Fund Returns Calculator",
    category: "finance",
    description: "Evaluate mutual fund SIP and lumpsum returns with annual CAGR compounding projections.",
    keywords: ["mutual fund calculator", "equity returns", "mf portfolio growth"],
    lastUpdated: "August 2026",
    relatedCalculators: ["sip-calculator", "lumpsum-calculator", "cagr-calculator"],
  },
  {
    id: "sukanya-samriddhi-calculator",
    slug: "sukanya-samriddhi-calculator",
    name: "Sukanya Samriddhi (SSY) Calculator",
    category: "finance",
    description: "Calculate maturity amount and government interest on Sukanya Samriddhi Yojana girl child scheme.",
    keywords: ["ssy calculator", "sukanya samriddhi yojana", "girl child savings scheme"],
    lastUpdated: "August 2026",
    relatedCalculators: ["ppf-calculator", "fd-calculator", "sip-calculator"],
  },
  {
    id: "ltv-calculator",
    slug: "ltv-calculator",
    name: "Loan-to-Value (LTV) Calculator",
    category: "finance",
    description: "Calculate loan-to-value ratio, required equity down payment, and mortgage risk proportions.",
    keywords: ["ltv calculator", "loan to value ratio", "mortgage down payment", "home loan eligibility"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "LTV Ratio (%) = (Loan Amount / Property Value) × 100",
    formulaVariables: [
      { symbol: "Loan Amount", label: "Borrowing Principal Amount Requested" },
      { symbol: "Property Value", label: "Total Appraised Market Valuation of Asset" },
    ],
    workedExample: {
      scenario: "Purchasing a residential property valued at ₹50,00,000 with a loan of ₹40,00,000",
      inputs: { "Property Value": "₹50,00,000", "Loan Amount": "₹40,00,000" },
      result: "LTV Ratio: 80.00% | Required Equity Down Payment: ₹10,00,000 (20%)",
      explanation: "An 80% LTV falls within the standard Indian housing finance limits, requiring 20% upfront self-funding.",
    },
    assumptions: [
      "LTV reflects the proportion of collateral asset value funded by borrowing.",
      "Actual loan approval depends on lender-specific underwriting, credit profile, property characteristics, and income.",
    ],
    relatedCalculators: ["home-loan-emi-calculator", "emi-calculator", "loan-calculator"],
    faqs: [
      { q: "What does an LTV ratio indicate?", a: "Loan-to-Value ratio measures the percentage of an asset's total appraised value that is being financed via debt." },
      { q: "Does lower LTV guarantee loan approval?", a: "No. While lower LTV reduces lender exposure, approvals also require credit score checks, documented income, and title verification." },
    ],
  },

  // ==========================================
  // 2. BUSINESS CALCULATORS
  // ==========================================
  {
    id: "payment-gateway-fee-calculator",
    slug: "payment-gateway-fee-calculator",
    name: "Payment Gateway Fee Calculator",
    category: "business",
    description: "Calculate transaction charges, fixed gateway fees, GST/taxes, and net payout for Stripe, PayPal, Razorpay, or custom payment processors.",
    keywords: ["payment gateway fee calculator", "stripe fee calculator", "paypal fee calculator", "razorpay fee calculator", "merchant fee calculator", "reverse gateway fee"],
    popular: true,
    featured: true,
    lastUpdated: "August 2026",
    formulaDescription: "Forward: Net Payout = Gross - [Processing Fee + Fixed Fee + Tax on Fee + FX Fee] | Reverse: Required Charge = (Target Net + Fixed Fee × (1 + Tax Rate)) / [1 - (Fee Rate × (1 + Tax Rate) + FX Rate)]",
    formulaVariables: [
      { symbol: "Gross Amount", label: "Customer Transaction Amount" },
      { symbol: "Processing Fee", label: "Gross Amount × Processing Fee Rate %" },
      { symbol: "Fixed Fee", label: "Fixed Gateway Transaction Fee (e.g. $0.30 or ₹0)" },
      { symbol: "Tax on Fee", label: "(Processing Fee + Fixed Fee) × GST/Tax % (18%)" },
      { symbol: "FX Fee", label: "Gross Amount × Currency Conversion Rate %" },
    ],
    workedExample: {
      scenario: "₹10,000 Customer Payment processed via Razorpay (2.0% Processing Fee + 18% GST on Fee, 0% FX, ₹0 Fixed Fee)",
      inputs: { "Transaction Amount": "₹10,000.00", "Processing Fee (2%)": "₹200.00", "GST on Fee (18%)": "₹36.00", "Fixed Fee": "₹0.00" },
      result: "Customer Charge: ₹10,000.00 | Total Gateway & Tax Fees: -₹236.00 | Net Amount Received: ₹9,764.00 | Effective Fee: 2.36%",
      explanation: "Base gateway fee of 2% on ₹10,000 is ₹200. With 18% GST applied to the fee (₹36), total deduction is ₹236, yielding a net payout of ₹9,764.00.",
    },
    assumptions: [
      "Rates vary based on payment method (UPI, Debit Card, International Credit Card, Netbanking).",
      "GST at 18% applies strictly on the gateway fee amount under Indian Tax Regulations.",
    ],
    relatedCalculators: ["ecommerce-roas-break-even-calculator", "invoice-total-calculator", "gst-calculator", "freelance-hourly-rate"],
    faqs: [
      { q: "How are payment gateway fees calculated?", a: "Gateway fees are computed by applying a percentage fee on gross transaction value, adding a fixed fee per transaction, and applying statutory taxes (like 18% GST in India) on the fee component." },
      { q: "How do I calculate what to charge a client so I receive an exact net amount?", a: "Use the reverse calculation mode: Required Charge = (Net Target + Fixed Fee × (1 + Tax)) / (1 - Effective Fee Percentage)." },
    ],
  },
  {
    id: "ecommerce-roas-break-even-calculator",
    slug: "ecommerce-roas-break-even-calculator",
    name: "E-Commerce ROAS & Break-Even Margin Calculator",
    category: "business",
    description: "Determine your break-even ROAS, maximum target CAC, net profit margin, and non-ad unit costs across Meta, Google, and Amazon ad campaigns.",
    keywords: ["ecommerce roas calculator", "break even roas calculator", "max cac calculator", "ecommerce profit margin calculator", "shopify profit calculator"],
    popular: true,
    featured: true,
    lastUpdated: "August 2026",
    formulaDescription: "Actual ROAS = Gross Revenue / Ad Spend | Break-Even ROAS = Gross Revenue / Contribution Before Ads | Max CAC = (Contribution Before Ads - Fixed Overheads) / Orders",
    formulaVariables: [
      { symbol: "Gross Revenue", label: "Orders × [Unit Selling Price × (1 - Discount %)]" },
      { symbol: "Net Revenue", label: "Gross Revenue × (1 - Returns & Refunds %)" },
      { symbol: "Non-Ad Variable Costs", label: "COGS + Shipping + Packaging + Marketplace Fees + Gateway Fees + Other Variable Costs" },
      { symbol: "Contribution Before Ads", label: "Net Revenue - Non-Ad Variable Costs" },
      { symbol: "Contribution Margin %", label: "(Contribution Before Ads / Net Revenue) × 100" },
      { symbol: "Net Profit", label: "Contribution Before Ads - Ad Spend - Fixed Overheads" },
    ],
    workedExample: {
      scenario: "100 delivered units sold at ₹1,499 with ₹400 COGS, ₹90 Shipping, ₹30 Packaging, 5% Marketplace Fee, 2% Gateway Fee, 10% Returns, ₹10,000 Overheads, and ₹25,000 Ad Spend",
      inputs: { "Unit Selling Price": "₹1,499.00", "Orders": "100", "Gross Revenue": "₹1,49,900.00", "Net Revenue (10% Returns)": "₹1,34,910.00", "Non-Ad Variable Costs": "₹61,443.70", "Contribution Before Ads": "₹73,466.30", "Ad Spend": "₹25,000.00" },
      result: "Actual ROAS: 6.00x | Break-Even ROAS: 2.04x | Net Profit: ₹38,466.30 | Profit Margin: 25.66% | Maximum Target CAC: ₹634.66",
      explanation: "Gross revenue of ₹1,49,900 yields ₹1,34,910 net revenue after 10% returns. After non-ad variable costs (₹61,443.70), contribution before ads is ₹73,466.30. Break-even ROAS is ₹1,49,900 / ₹73,466.30 = 2.04x. Against a 6.00x actual ROAS and ₹25,000 ad spend, net profit reaches ₹38,466.30 with a maximum allowable CAC of ₹634.66.",
    },
    assumptions: [
      "Break-even ROAS is defined as Gross Revenue / Contribution Before Ads.",
      "Contribution Before Ads accounts for product costs, shipping, packaging, returns allowance, and merchant fees.",
    ],
    relatedCalculators: ["roas-calculator", "break-even-calculator", "payment-gateway-fee-calculator", "profit-loss-calculator"],
    faqs: [
      { q: "What is Break-Even ROAS?", a: "Break-even ROAS is the minimum Return on Ad Spend required so that total revenue covers product cost, shipping, payment fees, returns, and marketing spend without losing money." },
      { q: "What is Maximum Target CAC?", a: "Maximum CAC is the absolute highest dollar/rupee amount you can spend to acquire a single paying customer without making an operating loss." },
    ],
  },
  {
    id: "roas-calculator",
    slug: "roas-calculator",
    name: "ROAS Calculator",
    category: "business",
    description: "Calculate Return on Ad Spend for marketing campaigns and e-commerce advertising.",
    keywords: ["roas calculator", "return on ad spend", "marketing roi"],
    lastUpdated: "August 2026",
    formulaDescription: "ROAS = Total Campaign Revenue / Total Ad Spend",
    relatedCalculators: ["ecommerce-roas-break-even-calculator", "break-even-calculator", "business-profit-calculator", "roi-calculator"],
  },
  {
    id: "break-even-calculator",
    slug: "break-even-calculator",
    name: "Break-Even Point Calculator",
    category: "business",
    description: "Determine sales volume and revenue required to cover fixed and variable overheads.",
    keywords: ["break even calculator", "break even point", "contribution margin"],
    lastUpdated: "August 2026",
    formulaDescription: "Break-Even Units = Fixed Costs / (Price per Unit - Variable Cost per Unit)",
    relatedCalculators: ["ecommerce-roas-break-even-calculator", "business-profit-calculator", "margin-calculator", "markup-calculator"],
  },
  {
    id: "commission-calculator",
    slug: "commission-calculator",
    name: "Commission Calculator",
    category: "business",
    description: "Calculate sales commission payouts, tiered incentives, and net distributor revenue.",
    keywords: ["commission calculator", "sales commission", "agent fee"],
    lastUpdated: "August 2026",
    relatedCalculators: ["freelance-hourly-rate", "salary-calculator", "percentage-calculator"],
  },
  {
    id: "freelance-hourly-rate",
    slug: "freelance-hourly-rate",
    name: "Freelance Hourly Rate Calculator",
    category: "business",
    description: "Determine ideal billing rate based on income goals, billable hours, and overheads.",
    keywords: ["freelance rate calculator", "hourly rate", "consultant pricing"],
    lastUpdated: "August 2026",
    relatedCalculators: ["upwork-net-earnings-calculator", "fiverr-net-earnings-calculator", "hourly-to-annual-salary", "salary-calculator"],
  },
  {
    id: "hourly-to-annual-salary",
    slug: "hourly-to-annual-salary",
    name: "Hourly to Annual Salary Calculator",
    category: "business",
    description: "Convert hourly pay into weekly, monthly, and yearly gross income estimates.",
    keywords: ["hourly to salary", "wage converter", "annual pay"],
    lastUpdated: "August 2026",
    relatedCalculators: ["freelance-hourly-rate", "salary-calculator", "overtime-pay-calculator"],
  },
  {
    id: "overtime-pay-calculator",
    slug: "overtime-pay-calculator",
    name: "Overtime Pay Calculator",
    category: "business",
    description: "Calculate overtime compensation with standard 1.5x and 2.0x multipliers.",
    keywords: ["overtime calculator", "ot pay", "shift pay"],
    lastUpdated: "August 2026",
    relatedCalculators: ["hourly-to-annual-salary", "salary-calculator", "payroll-calculator"],
  },
  {
    id: "salary-hike-calculator",
    slug: "salary-hike-calculator",
    name: "Salary Hike Calculator",
    category: "business",
    description: "Calculate annual appraisal percentage increase and updated monthly paycheck.",
    keywords: ["salary hike calculator", "appraisal percentage", "pay rise"],
    lastUpdated: "August 2026",
    relatedCalculators: ["salary-increment-calculator", "salary-calculator", "percentage-increase-calculator"],
  },
  {
    id: "salary-increment-calculator",
    slug: "salary-increment-calculator",
    name: "Salary Increment Calculator",
    category: "business",
    description: "Project multi-year compounding wage increments and career CTC progression.",
    keywords: ["salary increment", "annual pay increment"],
    lastUpdated: "August 2026",
    relatedCalculators: ["salary-hike-calculator", "salary-calculator", "cagr-calculator"],
  },
  {
    id: "payroll-calculator",
    slug: "payroll-calculator",
    name: "Payroll Calculator",
    category: "business",
    description: "Calculate gross salary breakdown with employee EPF, PT, and employer contributions.",
    keywords: ["payroll calculator", "salary slip calculator", "ctc breakdown"],
    lastUpdated: "August 2026",
    relatedCalculators: ["salary-calculator", "income-tax-calculator", "gratuity-calculator"],
  },
  {
    id: "invoice-total-calculator",
    slug: "invoice-total-calculator",
    name: "Invoice Total Calculator",
    category: "business",
    description: "Generate invoice totals with itemized line items, trade discounts, and GST taxes.",
    keywords: ["invoice calculator", "bill total", "gst invoice"],
    lastUpdated: "August 2026",
    relatedCalculators: ["payment-gateway-fee-calculator", "gst-calculator", "discount-calculator", "percentage-calculator"],
  },
  {
    id: "business-profit-calculator",
    slug: "business-profit-calculator",
    name: "Business Profit Calculator",
    category: "business",
    description: "Analyze operating EBIT, COGS, OpEx, and net profit margins after corporate taxes.",
    keywords: ["business profit", "operating profit", "ebit calculator"],
    lastUpdated: "August 2026",
    relatedCalculators: ["business-margin-calculator", "break-even-calculator", "markup-vs-margin-calculator"],
  },
  {
    id: "business-margin-calculator",
    slug: "business-margin-calculator",
    name: "Business Margin Calculator",
    category: "business",
    description: "Calculate gross margin, operating margin, and net profit ratios from revenue.",
    keywords: ["business margin", "gross margin", "net margin"],
    lastUpdated: "August 2026",
    relatedCalculators: ["business-profit-calculator", "margin-calculator", "markup-vs-margin-calculator"],
  },
  {
    id: "markup-vs-margin-calculator",
    slug: "markup-vs-margin-calculator",
    name: "Markup vs Margin Calculator",
    category: "business",
    description: "Convert cost markup percentage to gross profit margin and vice-versa seamlessly.",
    keywords: ["markup vs margin", "markup to margin", "pricing markup"],
    lastUpdated: "August 2026",
    formulaDescription: "Margin = Markup / (100 + Markup) × 100 | Markup = Margin / (100 - Margin) × 100",
    relatedCalculators: ["markup-calculator", "margin-calculator", "discount-calculator"],
  },
  {
    id: "rent-split-calculator",
    slug: "rent-split-calculator",
    name: "Rent Split Calculator",
    category: "business",
    description: "Fairly divide apartment rent and utility bills among flatmates.",
    keywords: ["rent split", "roommate rent calculator", "flatmate split"],
    lastUpdated: "August 2026",
    relatedCalculators: ["tip-calculator", "hra-calculator", "salary-calculator"],
  },

  // ==========================================
  // 3. MATH CALCULATORS
  // ==========================================
  {
    id: "percentage-calculator",
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    category: "math",
    description: "Calculate percentage shares, fractions, and percentage differences with real-time modes.",
    keywords: ["percentage calculator", "percent share", "math percentage"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "X% of Y = (X × Y) / 100 | Percentage Share = (X / Y) × 100",
    relatedCalculators: ["percentage-increase-calculator", "percentage-decrease-calculator", "discount-calculator"],
  },
  {
    id: "percentage-increase-calculator",
    slug: "percentage-increase-calculator",
    name: "Percentage Increase Calculator",
    category: "math",
    description: "Calculate growth and percentage appreciation between original and final amounts.",
    keywords: ["percentage increase", "growth rate", "percent addition"],
    lastUpdated: "August 2026",
    formulaDescription: "Percentage Increase (%) = [(New Value - Original Value) / Original Value] × 100",
    relatedCalculators: ["percentage-calculator", "percentage-decrease-calculator", "salary-hike-calculator"],
  },
  {
    id: "percentage-decrease-calculator",
    slug: "percentage-decrease-calculator",
    name: "Percentage Decrease Calculator",
    category: "math",
    description: "Compute price drops, depreciation, and reduction percentages accurately.",
    keywords: ["percentage decrease", "markdown rate", "price reduction"],
    lastUpdated: "August 2026",
    formulaDescription: "Percentage Decrease (%) = [(Original Value - New Value) / Original Value] × 100",
    relatedCalculators: ["percentage-calculator", "discount-calculator", "loss-calculator"],
  },
  {
    id: "discount-calculator",
    slug: "discount-calculator",
    name: "Discount Calculator",
    category: "math",
    description: "Calculate shopping discounts, clearance sales, stacked coupons, and net savings.",
    keywords: ["discount calculator", "sale price", "coupon discount"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "Discount Amount = (MRP × Discount %) / 100 | Final Price = MRP - Discount Amount",
    relatedCalculators: ["percentage-calculator", "gst-calculator", "markup-vs-margin-calculator"],
  },
  {
    id: "profit-calculator",
    slug: "profit-calculator",
    name: "Profit Calculator",
    category: "math",
    description: "Calculate gross trade profit and markup return against wholesale cost price.",
    keywords: ["profit calculator", "trade profit", "gain percentage"],
    lastUpdated: "August 2026",
    relatedCalculators: ["profit-loss-calculator", "margin-calculator", "markup-calculator"],
  },
  {
    id: "loss-calculator",
    slug: "loss-calculator",
    name: "Loss Calculator",
    category: "math",
    description: "Evaluate trading losses and downward percentage deviations on capital.",
    keywords: ["loss calculator", "trade loss", "loss percentage"],
    lastUpdated: "August 2026",
    relatedCalculators: ["profit-loss-calculator", "percentage-decrease-calculator"],
  },
  {
    id: "profit-loss-calculator",
    slug: "profit-loss-calculator",
    name: "Profit & Loss Calculator",
    category: "math",
    description: "Comprehensive CP vs SP financial profitability calculator with quantity multipliers.",
    keywords: ["profit and loss calculator", "cp sp calculator", "net gain loss"],
    lastUpdated: "August 2026",
    formulaDescription: "Profit = SP - CP | Profit % = (Profit / CP) × 100 | Loss % = (Loss / CP) × 100",
    relatedCalculators: ["profit-calculator", "loss-calculator", "margin-calculator", "markup-calculator"],
  },
  {
    id: "average-calculator",
    slug: "average-calculator",
    name: "Average Calculator",
    category: "math",
    description: "Calculate Arithmetic Mean, Median, Mode, Range, and Sum from a sequence of numbers.",
    keywords: ["average calculator", "mean median mode", "statistical average"],
    lastUpdated: "August 2026",
    relatedCalculators: ["ratio-calculator", "percentage-calculator", "grade-calculator"],
  },
  {
    id: "ratio-calculator",
    slug: "ratio-calculator",
    name: "Ratio Calculator",
    category: "math",
    description: "Simplify mathematical ratios, calculate scaling proportions, and visual percentage shares.",
    keywords: ["ratio calculator", "simplify ratio", "aspect ratio"],
    lastUpdated: "August 2026",
    relatedCalculators: ["average-calculator", "fraction-calculator", "percentage-calculator"],
  },
  {
    id: "markup-calculator",
    slug: "markup-calculator",
    name: "Markup Calculator",
    category: "math",
    description: "Calculate retail selling price and profit cash from cost markup percentages.",
    keywords: ["markup calculator", "cost markup", "pricing formula"],
    lastUpdated: "August 2026",
    relatedCalculators: ["margin-calculator", "markup-vs-margin-calculator", "profit-loss-calculator"],
  },
  {
    id: "margin-calculator",
    slug: "margin-calculator",
    name: "Margin Calculator",
    category: "math",
    description: "Calculate gross profit margins and revenue ratios from selling prices.",
    keywords: ["margin calculator", "gross profit margin", "trade margin"],
    lastUpdated: "August 2026",
    relatedCalculators: ["markup-calculator", "business-margin-calculator", "profit-loss-calculator"],
  },

  // ==========================================
  // 4. HEALTH & FITNESS
  // ==========================================
  {
    id: "bmi-calculator",
    slug: "bmi-calculator",
    name: "BMI Calculator",
    category: "health",
    description: "Calculate Body Mass Index (BMI) and healthy weight reference ranges for adults.",
    keywords: ["bmi calculator", "body mass index", "healthy weight"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "BMI = Weight (kg) / [Height (m)]^2",
    relatedCalculators: ["ideal-weight-calculator", "body-fat-calculator", "calorie-calculator"],
    faqs: [
      { q: "What is a healthy BMI range?", a: "For adults, a BMI between 18.5 and 24.9 is considered normal weight by WHO standards." },
    ],
  },
  {
    id: "bmr-calculator",
    slug: "bmr-calculator",
    name: "BMR Calculator",
    category: "health",
    description: "Calculate Basal Metabolic Rate using Mifflin-St Jeor formula for resting calorie burn.",
    keywords: ["bmr calculator", "basal metabolic rate", "resting calorie burn"],
    lastUpdated: "August 2026",
    relatedCalculators: ["calorie-calculator", "macro-calculator", "bmi-calculator"],
  },
  {
    id: "calorie-calculator",
    slug: "calorie-calculator",
    name: "Daily Calorie Calculator",
    category: "health",
    description: "Determine daily maintenance, deficit, and surplus calories for fitness goals.",
    keywords: ["calorie calculator", "tdee calculator", "weight loss calories"],
    popular: true,
    lastUpdated: "August 2026",
    relatedCalculators: ["bmr-calculator", "macro-calculator", "water-intake-calculator"],
  },
  {
    id: "ideal-weight-calculator",
    slug: "ideal-weight-calculator",
    name: "Ideal Body Weight Calculator",
    category: "health",
    description: "Estimate optimal body weight based on Devine, Robinson, and Miller formulas.",
    keywords: ["ideal weight calculator", "healthy body weight", "devine formula"],
    lastUpdated: "August 2026",
    relatedCalculators: ["bmi-calculator", "body-fat-calculator"],
  },
  {
    id: "body-fat-calculator",
    slug: "body-fat-calculator",
    name: "Body Fat Calculator",
    category: "health",
    description: "Estimate body fat percentage using US Navy circumference method.",
    keywords: ["body fat calculator", "us navy body fat", "lean mass"],
    lastUpdated: "August 2026",
    relatedCalculators: ["bmi-calculator", "ideal-weight-calculator", "calorie-calculator"],
  },
  {
    id: "water-intake-calculator",
    slug: "water-intake-calculator",
    name: "Water Intake Calculator",
    category: "health",
    description: "Calculate recommended daily hydration target based on weight and workout activity.",
    keywords: ["water intake calculator", "daily hydration", "water drinking target"],
    lastUpdated: "August 2026",
    relatedCalculators: ["calorie-calculator", "bmi-calculator"],
  },
  {
    id: "macro-calculator",
    slug: "macro-calculator",
    name: "Macro Calculator",
    category: "health",
    description: "Calculate daily protein, carbohydrate, and fat gram requirements for fitness diets.",
    keywords: ["macro calculator", "protein carbs fats", "diet macros"],
    lastUpdated: "August 2026",
    relatedCalculators: ["calorie-calculator", "bmr-calculator"],
  },

  // ==========================================
  // 5. TIME & DATE
  // ==========================================
  {
    id: "age-calculator",
    slug: "age-calculator",
    name: "Age Calculator",
    category: "time-date",
    description: "Calculate exact chronological age in years, months, days, hours, and next birthday countdown.",
    keywords: ["age calculator", "calculate age from dob", "date of birth calculator"],
    popular: true,
    lastUpdated: "August 2026",
    relatedCalculators: ["age-in-days-calculator", "date-difference-calculator", "countdown-calculator"],
  },
  {
    id: "date-difference-calculator",
    slug: "date-difference-calculator",
    name: "Date Difference Calculator",
    category: "time-date",
    description: "Calculate elapsed calendar days, weeks, and duration between two dates.",
    keywords: ["date difference", "days between dates", "calendar duration"],
    lastUpdated: "August 2026",
    relatedCalculators: ["days-between-dates", "date-add-calculator", "age-calculator"],
  },
  {
    id: "days-between-dates",
    slug: "days-between-dates",
    name: "Days Between Dates",
    category: "time-date",
    description: "Find total count of working days and weekends between any two calendar dates.",
    keywords: ["days between dates", "work days calculator", "calendar count"],
    lastUpdated: "August 2026",
    relatedCalculators: ["date-difference-calculator", "hours-calculator"],
  },
  {
    id: "time-duration-calculator",
    slug: "time-duration-calculator",
    name: "Time Duration Calculator",
    category: "time-date",
    description: "Add, subtract, and find duration between start and end clock times.",
    keywords: ["time duration calculator", "time difference", "hours minutes count"],
    lastUpdated: "August 2026",
    relatedCalculators: ["hours-calculator", "time-zone-calculator"],
  },
  {
    id: "hours-calculator",
    slug: "hours-calculator",
    name: "Hours Calculator",
    category: "time-date",
    description: "Calculate total work hours, timesheet shifts, and unpaid break deductions.",
    keywords: ["hours calculator", "work hours", "timesheet calculator"],
    lastUpdated: "August 2026",
    relatedCalculators: ["time-duration-calculator", "overtime-pay-calculator"],
  },
  {
    id: "date-add-calculator",
    slug: "date-add-calculator",
    name: "Date Add Calculator",
    category: "time-date",
    description: "Add days, weeks, months, or years to any date to calculate future target milestones.",
    keywords: ["add days to date", "future date calculator", "date addition"],
    lastUpdated: "August 2026",
    relatedCalculators: ["date-subtract-calculator", "date-difference-calculator"],
  },
  {
    id: "date-subtract-calculator",
    slug: "date-subtract-calculator",
    name: "Date Subtract Calculator",
    category: "time-date",
    description: "Subtract days, weeks, or months from any date to find historical calendar points.",
    keywords: ["subtract days from date", "past date calculator"],
    lastUpdated: "August 2026",
    relatedCalculators: ["date-add-calculator", "date-difference-calculator"],
  },
  {
    id: "age-in-days-calculator",
    slug: "age-in-days-calculator",
    name: "Age in Days Calculator",
    category: "time-date",
    description: "Find the exact number of total days and hours you have lived since birth.",
    keywords: ["age in days", "days alive calculator", "total days lived"],
    lastUpdated: "August 2026",
    relatedCalculators: ["age-calculator", "countdown-calculator"],
  },
  {
    id: "time-zone-calculator",
    slug: "time-zone-calculator",
    name: "Time Zone Converter",
    category: "time-date",
    description: "Convert meeting times across IST, practical international zones, and regional clocks.",
    keywords: ["time zone converter", "ist to est", "utc to ist converter"],
    lastUpdated: "August 2026",
    relatedCalculators: ["time-duration-calculator", "countdown-calculator"],
  },

  // ==========================================
  // 6. UNIT CONVERTERS
  // ==========================================
  {
    id: "unit-converter",
    slug: "unit-converter",
    name: "All-in-One Unit Converter",
    category: "converters",
    description: "Universal converter across length, mass, land area, volume, temperature, and speed.",
    keywords: ["unit converter", "metric converter", "all in one conversion"],
    popular: true,
    lastUpdated: "August 2026",
    relatedCalculators: ["length-converter", "weight-converter", "area-converter", "temperature-converter"],
  },
  {
    id: "length-converter",
    slug: "length-converter",
    name: "Length Converter",
    category: "converters",
    description: "Convert between meters, feet, inches, kilometers, centimeters, and miles.",
    keywords: ["length converter", "meters to feet", "distance converter"],
    lastUpdated: "August 2026",
    relatedCalculators: ["feet-to-meter", "meter-to-feet", "inch-to-cm", "height-converter"],
  },
  {
    id: "weight-converter",
    slug: "weight-converter",
    name: "Weight Converter",
    category: "converters",
    description: "Convert kilograms, pounds (lbs), grams, ounces, and metric tons.",
    keywords: ["weight converter", "kg to lbs", "mass conversion"],
    lastUpdated: "August 2026",
    relatedCalculators: ["kg-to-pound", "pound-to-kg", "unit-converter"],
  },
  {
    id: "height-converter",
    slug: "height-converter",
    name: "Height Converter",
    category: "converters",
    description: "Convert human height between feet + inches and centimeters.",
    keywords: ["height converter", "feet to cm", "cm to feet inches"],
    lastUpdated: "August 2026",
    relatedCalculators: ["length-converter", "bmi-calculator", "feet-to-meter"],
  },
  {
    id: "area-converter",
    slug: "area-converter",
    name: "Area Converter",
    category: "converters",
    description: "Convert land units: Square Feet, Square Meters, Acres, Hectares, and Bigha.",
    keywords: ["area converter", "sq ft to acre", "bigha to sq ft"],
    lastUpdated: "August 2026",
    relatedCalculators: ["length-converter", "unit-converter"],
  },
  {
    id: "volume-converter",
    slug: "volume-converter",
    name: "Volume Converter",
    category: "converters",
    description: "Convert Liters, Milliliters, Gallons, and Cubic Meters.",
    keywords: ["volume converter", "liters to gallons", "fluid ounces to ml"],
    lastUpdated: "August 2026",
    relatedCalculators: ["water-intake-calculator", "unit-converter"],
  },
  {
    id: "temperature-converter",
    slug: "temperature-converter",
    name: "Temperature Converter",
    category: "converters",
    description: "Convert between Celsius (°C), Fahrenheit (°F), and Kelvin (K).",
    keywords: ["temperature converter", "celsius to fahrenheit", "kelvin conversion"],
    lastUpdated: "August 2026",
    relatedCalculators: ["celsius-to-fahrenheit", "fahrenheit-to-celsius"],
  },
  {
    id: "speed-converter",
    slug: "speed-converter",
    name: "Speed Converter",
    category: "converters",
    description: "Convert km/h, mph, m/s, and knots instantly.",
    keywords: ["speed converter", "kmh to mph", "knots to kmh"],
    lastUpdated: "August 2026",
    relatedCalculators: ["mileage-calculator", "unit-converter"],
  },
  {
    id: "time-converter",
    slug: "time-converter",
    name: "Time Converter",
    category: "converters",
    description: "Convert seconds, minutes, hours, days, and weeks.",
    keywords: ["time converter", "hours to minutes", "seconds to hours"],
    lastUpdated: "August 2026",
    relatedCalculators: ["time-duration-calculator", "hours-calculator"],
  },
  {
    id: "data-storage-converter",
    slug: "data-storage-converter",
    name: "Data Storage Converter",
    category: "converters",
    description: "Convert Bytes, KB, MB, GB, TB, and PB digital storage sizes.",
    keywords: ["data converter", "mb to gb", "gb to tb converter"],
    lastUpdated: "August 2026",
    relatedCalculators: ["unit-converter"],
  },
  {
    id: "feet-to-meter",
    slug: "feet-to-meter",
    name: "Feet to Meter Converter",
    category: "converters",
    description: "Convert feet (ft) to meters (m) accurately.",
    keywords: ["feet to meter", "ft to m"],
    lastUpdated: "August 2026",
    relatedCalculators: ["meter-to-feet", "length-converter", "height-converter"],
  },
  {
    id: "meter-to-feet",
    slug: "meter-to-feet",
    name: "Meter to Feet Converter",
    category: "converters",
    description: "Convert meters (m) to feet (ft) with decimal precision.",
    keywords: ["meter to feet", "m to ft"],
    lastUpdated: "August 2026",
    relatedCalculators: ["feet-to-meter", "length-converter", "inch-to-cm"],
  },
  {
    id: "inch-to-cm",
    slug: "inch-to-cm",
    name: "Inch to CM Converter",
    category: "converters",
    description: "Convert inches (in) to centimeters (cm).",
    keywords: ["inch to cm", "in to cm"],
    lastUpdated: "August 2026",
    relatedCalculators: ["cm-to-inch", "height-converter", "length-converter"],
  },
  {
    id: "cm-to-inch",
    slug: "cm-to-inch",
    name: "CM to Inch Converter",
    category: "converters",
    description: "Convert centimeters (cm) to inches (in).",
    keywords: ["cm to inch", "cm to in"],
    lastUpdated: "August 2026",
    relatedCalculators: ["inch-to-cm", "height-converter", "length-converter"],
  },
  {
    id: "kg-to-pound",
    slug: "kg-to-pound",
    name: "KG to Pound Converter",
    category: "converters",
    description: "Convert kilograms (kg) to pounds (lbs).",
    keywords: ["kg to pound", "kg to lbs"],
    lastUpdated: "August 2026",
    relatedCalculators: ["pound-to-kg", "weight-converter", "bmi-calculator"],
  },
  {
    id: "pound-to-kg",
    slug: "pound-to-kg",
    name: "Pound to KG Converter",
    category: "converters",
    description: "Convert pounds (lbs) to kilograms (kg).",
    keywords: ["pound to kg", "lbs to kg"],
    lastUpdated: "August 2026",
    relatedCalculators: ["kg-to-pound", "weight-converter", "bmi-calculator"],
  },
  {
    id: "km-to-miles",
    slug: "km-to-miles",
    name: "KM to Miles Converter",
    category: "converters",
    description: "Convert kilometers (km) to statute miles (mi).",
    keywords: ["km to miles", "km to mi"],
    lastUpdated: "August 2026",
    relatedCalculators: ["miles-to-km", "speed-converter", "length-converter"],
  },
  {
    id: "miles-to-km",
    slug: "miles-to-km",
    name: "Miles to KM Converter",
    category: "converters",
    description: "Convert statute miles (mi) to kilometers (km).",
    keywords: ["miles to km", "mi to km"],
    lastUpdated: "August 2026",
    relatedCalculators: ["km-to-miles", "speed-converter", "length-converter"],
  },
  {
    id: "celsius-to-fahrenheit",
    slug: "celsius-to-fahrenheit",
    name: "Celsius to Fahrenheit",
    category: "converters",
    description: "Convert Celsius (°C) to Fahrenheit (°F).",
    keywords: ["celsius to fahrenheit", "c to f"],
    lastUpdated: "August 2026",
    relatedCalculators: ["fahrenheit-to-celsius", "temperature-converter"],
  },
  {
    id: "fahrenheit-to-celsius",
    slug: "fahrenheit-to-celsius",
    name: "Fahrenheit to Celsius",
    category: "converters",
    description: "Convert Fahrenheit (°F) to Celsius (°C).",
    keywords: ["fahrenheit to celsius", "f to c"],
    lastUpdated: "August 2026",
    relatedCalculators: ["celsius-to-fahrenheit", "temperature-converter"],
  },

  // ==========================================
  // 7. EDUCATION CALCULATORS
  // ==========================================
  {
    id: "grade-calculator",
    slug: "grade-calculator",
    name: "Grade Calculator",
    category: "education",
    description: "Calculate test scores, letter grades (A+, A, B, etc.), and 4.0 GPA standing.",
    keywords: ["grade calculator", "exam marks", "letter grade"],
    lastUpdated: "August 2026",
    relatedCalculators: ["gpa-calculator", "percentage-calculator", "average-calculator"],
  },
  {
    id: "gpa-calculator",
    slug: "gpa-calculator",
    name: "GPA Calculator",
    category: "education",
    description: "Calculate semester Grade Point Average (SGPA) with credit-hour weighting.",
    keywords: ["gpa calculator", "semester gpa", "4.0 scale gpa"],
    lastUpdated: "August 2026",
    relatedCalculators: ["cgpa-calculator", "grade-calculator", "cgpa-to-percentage"],
  },
  {
    id: "cgpa-calculator",
    slug: "cgpa-calculator",
    name: "CGPA Calculator",
    category: "education",
    description: "Calculate Cumulative Grade Point Average across all semesters.",
    keywords: ["cgpa calculator", "cumulative gpa", "college cgpa"],
    lastUpdated: "August 2026",
    relatedCalculators: ["gpa-calculator", "cgpa-to-percentage", "percentage-to-cgpa"],
  },
  {
    id: "cgpa-to-percentage",
    slug: "cgpa-to-percentage",
    name: "CGPA to Percentage (India)",
    category: "education",
    description: "Convert CBSE / AICTE 10-point CGPA into marks percentage (multiply by 9.5).",
    keywords: ["cgpa to percentage", "cbse cgpa to percentage", "aicte cgpa conversion"],
    popular: true,
    lastUpdated: "August 2026",
    formulaDescription: "Marks Percentage (%) = CGPA × 9.5",
    assumptions: [
      "Standard formula applies strictly to CBSE and AICTE affiliated universities.",
      "Check your individual university marksheet for autonomous scale multipliers.",
    ],
    relatedCalculators: ["percentage-to-cgpa", "cgpa-calculator", "gpa-calculator"],
  },
  {
    id: "percentage-to-cgpa",
    slug: "percentage-to-cgpa",
    name: "Percentage to CGPA",
    category: "education",
    description: "Convert academic marks percentage into standard 10-point CGPA.",
    keywords: ["percentage to cgpa", "marks to cgpa conversion"],
    lastUpdated: "August 2026",
    formulaDescription: "CGPA (10-Point Scale) = Marks Percentage / 9.5",
    relatedCalculators: ["cgpa-to-percentage", "cgpa-calculator", "percentage-calculator"],
  },

  // ==========================================
  // 8. OTHER USEFUL TOOLS
  // ==========================================
  {
    id: "fuel-cost-calculator",
    slug: "fuel-cost-calculator",
    name: "Fuel Cost Calculator",
    category: "other",
    description: "Calculate road trip petrol/diesel expenses, required liters, and running cost per km.",
    keywords: ["fuel cost calculator", "petrol expense", "trip cost"],
    popular: true,
    lastUpdated: "August 2026",
    relatedCalculators: ["mileage-calculator", "electricity-bill-calculator"],
  },
  {
    id: "mileage-calculator",
    slug: "mileage-calculator",
    name: "Vehicle Mileage Calculator",
    category: "other",
    description: "Calculate vehicle fuel economy in km/L from distance and fuel filled.",
    keywords: ["mileage calculator", "kmpl calculator", "fuel efficiency"],
    lastUpdated: "August 2026",
    relatedCalculators: ["fuel-cost-calculator", "speed-converter"],
  },
  {
    id: "electricity-bill-calculator",
    slug: "electricity-bill-calculator",
    name: "Electricity Bill Calculator",
    category: "other",
    description: "Estimate monthly power costs and kWh energy consumption for appliances.",
    keywords: ["electricity bill calculator", "power consumption", "bijli bill"],
    lastUpdated: "August 2026",
    relatedCalculators: ["fuel-cost-calculator", "savings-calculator"],
  },
  {
    id: "tip-calculator",
    slug: "tip-calculator",
    name: "Tip & Bill Split Calculator",
    category: "other",
    description: "Calculate dining tip percentages and divide restaurant bills equally.",
    keywords: ["tip calculator", "bill split", "restaurant tip"],
    lastUpdated: "August 2026",
    relatedCalculators: ["rent-split-calculator", "percentage-calculator"],
  },
  {
    id: "savings-calculator",
    slug: "savings-calculator",
    name: "Savings Calculator",
    category: "other",
    description: "Project future savings corpus from monthly deposits with interest compounding.",
    keywords: ["savings calculator", "savings growth", "monthly deposit"],
    lastUpdated: "August 2026",
    relatedCalculators: ["sip-calculator", "rd-calculator", "fd-calculator"],
  },
  {
    id: "countdown-calculator",
    slug: "countdown-calculator",
    name: "Date Countdown Calculator",
    category: "other",
    description: "Live countdown timer tracking remaining days, hours, and minutes until your event.",
    keywords: ["countdown calculator", "event countdown", "days left"],
    lastUpdated: "August 2026",
    relatedCalculators: ["age-calculator", "date-difference-calculator"],
  },
  {
    id: "fraction-calculator",
    slug: "fraction-calculator",
    name: "Fraction Calculator",
    category: "other",
    description: "Add, subtract, multiply, divide, and simplify fractions into mixed numbers.",
    keywords: ["fraction calculator", "simplify fractions", "mixed fraction"],
    lastUpdated: "August 2026",
    relatedCalculators: ["ratio-calculator", "percentage-calculator", "scientific-calculator"],
  },
  {
    id: "scientific-calculator",
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    category: "other",
    description: "Interactive browser scientific calculator for trigonometry, powers, roots, and logarithms.",
    keywords: ["scientific calculator", "trigonometry calculator", "online math tools"],
    lastUpdated: "August 2026",
    relatedCalculators: ["fraction-calculator", "percentage-calculator", "average-calculator"],
  },
];

export function getCalculatorsByCategory(cat: CalculatorCategory): CalculatorMeta[] {
  return CALCULATORS.filter((c) => c.category === cat);
}

export function getCalculatorBySlug(slug: string): CalculatorMeta | undefined {
  return CALCULATORS.find((c) => c.slug === slug);
}

export function getRelatedCalculators(current: CalculatorMeta, limit: number = 4): CalculatorMeta[] {
  if (current.relatedCalculators && current.relatedCalculators.length > 0) {
    const list = current.relatedCalculators
      .map((slug) => CALCULATORS.find((c) => c.slug === slug))
      .filter((c): c is CalculatorMeta => c !== undefined);
    if (list.length >= limit) return list.slice(0, limit);
  }
  const sameCategory = CALCULATORS.filter(
    (c) => c.category === current.category && c.slug !== current.slug
  );
  return sameCategory.slice(0, limit);
}
