import { CalculatorItem, CategoryInfo } from "./types";

export const CATEGORIES: CategoryInfo[] = [
  { id: "finance", name: "Finance Calculators", description: "Loans, investments, taxes & savings", href: "/calculators/finance" },
  { id: "business", name: "Business Calculators", description: "Profit, margins, payroll & rates", href: "/calculators/business" },
  { id: "math", name: "Math Calculators", description: "Percentages, ratios, fractions & algebra", href: "/calculators/math" },
  { id: "health", name: "Health Calculators", description: "BMI, BMR, calories & body metrics", href: "/calculators/health" },
  { id: "time-date", name: "Time & Date", description: "Age, date differences & timezones", href: "/calculators/time-date" },
  { id: "converters", name: "Unit Converters", description: "Length, weight, currency & speed", href: "/calculators/converters" },
  { id: "education", name: "Education", description: "GPA, CGPA, grades & marks conversion", href: "/calculators/education" },
  { id: "other", name: "Other Useful Tools", description: "Fuel cost, electricity, tip & countdowns", href: "/calculators/other" },
];

export const CALCULATORS: CalculatorItem[] = [
  // Finance
  { id: "emi", slug: "emi-calculator", name: "EMI Calculator", description: "Calculate monthly EMI, interest, and loan schedule.", category: "finance", popular: true, keywords: ["loan", "home loan", "car loan", "interest", "bank"] },
  { id: "gst", slug: "gst-calculator", name: "GST Calculator", description: "Calculate GST inclusive & exclusive prices instantly.", category: "finance", popular: true, keywords: ["tax", "cgst", "sgst", "invoice", "vat"] },
  { id: "sip", slug: "sip-calculator", name: "SIP Calculator", description: "Calculate mutual fund SIP returns and wealth growth.", category: "finance", popular: true, keywords: ["mutual fund", "investment", "cagr", "wealth"] },
  { id: "income-tax", slug: "income-tax-calculator", name: "Income Tax Calculator", description: "Estimate tax liability under Indian New & Old tax regimes.", category: "finance", popular: true, keywords: ["tax", "salary", "80c", "deduction", "itr"] },
  { id: "salary", slug: "salary-calculator", name: "Salary (In-Hand) Calculator", description: "Calculate Take-Home salary from CTC after PF & TDS.", category: "finance", popular: true, keywords: ["ctc", "take home", "paycheck", "pf"] },
  { id: "fd", slug: "fd-calculator", name: "FD Calculator", description: "Calculate Fixed Deposit interest payout and maturity.", category: "finance", popular: true, keywords: ["fixed deposit", "bank", "interest", "savings"] },
  { id: "ppf", slug: "ppf-calculator", name: "PPF Calculator", description: "Calculate Public Provident Fund 15-year maturity value.", category: "finance", popular: true, keywords: ["provident fund", "tax free", "post office"] },
  { id: "epf", slug: "epf-calculator", name: "EPF Calculator", description: "Track Employee Provident Fund balance and interest.", category: "finance", keywords: ["pf", "retirement", "pension"] },
  { id: "rd", slug: "rd-calculator", name: "RD Calculator", description: "Calculate Recurring Deposit monthly savings returns.", category: "finance", keywords: ["recurring deposit", "post office"] },
  { id: "nps", slug: "nps-calculator", name: "NPS Calculator", description: "National Pension Scheme retirement corpus estimation.", category: "finance", keywords: ["pension", "annuity", "retirement"] },
  { id: "hra", slug: "hra-calculator", name: "HRA Exemption Calculator", description: "Calculate tax exemption on House Rent Allowance.", category: "finance", keywords: ["rent", "tax exemption", "house rent"] },
  { id: "gratuity", slug: "gratuity-calculator", name: "Gratuity Calculator", description: "Estimate statutory gratuity amount on leaving job.", category: "finance", keywords: ["gratuity act", "corporate", "retirement"] },
  { id: "tds", slug: "tds-calculator", name: "TDS Calculator", description: "Calculate Tax Deducted at Source for professional & salary.", category: "finance", keywords: ["tax deduction", "withholding"] },
  { id: "home-loan-emi", slug: "home-loan-emi-calculator", name: "Home Loan EMI Calculator", description: "Plan housing loan EMIs and tax benefits.", category: "finance", keywords: ["housing loan", "mortgage", "property"] },
  { id: "car-loan-emi", slug: "car-loan-emi-calculator", name: "Car Loan EMI Calculator", description: "Calculate auto loan installments & down payments.", category: "finance", keywords: ["auto loan", "vehicle loan"] },
  { id: "personal-loan-emi", slug: "personal-loan-emi-calculator", name: "Personal Loan EMI Calculator", description: "Compute instant personal loan monthly installments.", category: "finance", keywords: ["instant loan", "unsecured"] },
  { id: "loan", slug: "loan-calculator", name: "General Loan Calculator", description: "Flexible loan interest and amortization tracker.", category: "finance", keywords: ["credit", "borrowing"] },
  { id: "simple-interest", slug: "simple-interest-calculator", name: "Simple Interest Calculator", description: "Standard PRT/100 interest calculations.", category: "finance", keywords: ["si", "principal", "math"] },
  { id: "compound-interest", slug: "compound-interest-calculator", name: "Compound Interest Calculator", description: "Calculate compound interest with multiple frequencies.", category: "finance", popular: true, keywords: ["ci", "compounding", "wealth"] },
  { id: "lumpsum", slug: "lumpsum-calculator", name: "Lumpsum Calculator", description: "One-time mutual fund investment return calculator.", category: "finance", keywords: ["mutual fund", "one time"] },
  { id: "cagr", slug: "cagr-calculator", name: "CAGR Calculator", description: "Calculate Compounded Annual Growth Rate of investments.", category: "finance", keywords: ["cagr", "growth rate", "stocks"] },
  { id: "inflation", slug: "inflation-calculator", name: "Inflation Calculator", description: "Determine future value of money adjusted for inflation.", category: "finance", keywords: ["purchasing power", "cpi"] },
  { id: "roi", slug: "roi-calculator", name: "ROI Calculator", description: "Calculate Return on Investment percentage.", category: "finance", keywords: ["return", "profitability"] },
  { id: "tax-savings", slug: "tax-savings-calculator", name: "Tax Savings Calculator", description: "Optimize 80C, 80D and NPS deductions.", category: "finance", keywords: ["80c", "tax save"] },
  { id: "savings-goal", slug: "savings-goal-calculator", name: "Savings Goal Calculator", description: "Find required monthly savings to achieve target corpus.", category: "finance", keywords: ["target", "corpus", "goal"] },

  // Math
  { id: "percentage", slug: "percentage-calculator", name: "Percentage Calculator", description: "Calculate percentage share, of values, and differences.", category: "math", popular: true, keywords: ["percent", "ratio", "proportion"] },
  { id: "percentage-increase", slug: "percentage-increase-calculator", name: "Percentage Increase Calculator", description: "Calculate percentage rise between old and new values.", category: "math", keywords: ["growth", "rise", "markup"] },
  { id: "percentage-decrease", slug: "percentage-decrease-calculator", name: "Percentage Decrease Calculator", description: "Calculate drop and markdown rates easily.", category: "math", keywords: ["drop", "markdown", "loss"] },
  { id: "discount", slug: "discount-calculator", name: "Discount Calculator", description: "Calculate sale price after flat or percentage discount.", category: "math", popular: true, keywords: ["sale", "shopping", "offer"] },
  { id: "profit", slug: "profit-calculator", name: "Profit Calculator", description: "Determine net profit and profit margin.", category: "math", keywords: ["gain", "business"] },
  { id: "loss", slug: "loss-calculator", name: "Loss Calculator", description: "Compute financial loss and loss percentage.", category: "math", keywords: ["deficit", "negative"] },
  { id: "profit-loss", slug: "profit-loss-calculator", name: "Profit & Loss Calculator", description: "Compare cost price vs selling price.", category: "math", keywords: ["cp", "sp", "margin"] },
  { id: "average", slug: "average-calculator", name: "Average Calculator", description: "Find Mean, Median, and Mode of numbers.", category: "math", keywords: ["mean", "statistics"] },
  { id: "ratio", slug: "ratio-calculator", name: "Ratio Calculator", description: "Simplify, scale, and compare mathematical ratios.", category: "math", keywords: ["proportion", "fraction"] },
  { id: "markup", slug: "markup-calculator", name: "Markup Calculator", description: "Calculate product markup price over cost.", category: "math", keywords: ["cost plus", "retail"] },
  { id: "margin", slug: "margin-calculator", name: "Margin Calculator", description: "Calculate gross and net profit margin.", category: "math", keywords: ["profit margin", "ebitda"] },

  // Time & Date
  { id: "age", slug: "age-calculator", name: "Age Calculator", description: "Calculate exact age in years, months, and days.", category: "time-date", popular: true, keywords: ["birthday", "dob", "chronological age"] },
  { id: "date-diff", slug: "date-difference-calculator", name: "Date Difference Calculator", description: "Find duration between any two given dates.", category: "time-date", keywords: ["calendar", "duration"] },
  { id: "days-between", slug: "days-between-dates", name: "Days Between Dates", description: "Total count of calendar and working days.", category: "time-date", keywords: ["business days", "working days"] },
  { id: "time-duration", slug: "time-duration-calculator", name: "Time Duration Calculator", description: "Add or subtract hours, minutes, and seconds.", category: "time-date", keywords: ["stopwatch", "hours"] },
  { id: "hours", slug: "hours-calculator", name: "Hours Calculator", description: "Calculate total work hours and payroll time logs.", category: "time-date", keywords: ["timesheet", "shift"] },
  { id: "date-add", slug: "date-add-calculator", name: "Date Add Calculator", description: "Add days, weeks, or months to any date.", category: "time-date", keywords: ["deadline", "future date"] },
  { id: "date-subtract", slug: "date-subtract-calculator", name: "Date Subtract Calculator", description: "Subtract time periods from any target date.", category: "time-date", keywords: ["past date", "history"] },
  { id: "age-in-days", slug: "age-in-days-calculator", name: "Age in Days Calculator", description: "Find exactly how many days you have been alive.", category: "time-date", keywords: ["milestone", "days alive"] },
  { id: "time-zone", slug: "time-zone-calculator", name: "Time Zone Converter", description: "Convert times across IST, UTC, EST, and global zones.", category: "time-date", keywords: ["utc", "ist", "gmt", "est"] },

  // Health
  { id: "bmi", slug: "bmi-calculator", name: "BMI Calculator", description: "Check Body Mass Index and healthy weight category.", category: "health", popular: true, keywords: ["body mass", "fitness", "obesity", "weight"] },
  { id: "bmr", slug: "bmr-calculator", name: "BMR Calculator", description: "Calculate Basal Metabolic Rate and resting calorie burn.", category: "health", keywords: ["metabolism", "calories", "tdee"] },
  { id: "calorie", slug: "calorie-calculator", name: "Daily Calorie Calculator", description: "Determine maintenance, surplus, or deficit calories.", category: "health", keywords: ["tdee", "diet", "gym", "weight loss"] },
  { id: "ideal-weight", slug: "ideal-weight-calculator", name: "Ideal Body Weight Calculator", description: "Calculate healthy target weight based on height.", category: "health", keywords: ["target weight", "devine formula"] },
  { id: "body-fat", slug: "body-fat-calculator", name: "Body Fat Calculator", description: "US Navy method body fat percentage estimator.", category: "health", keywords: ["lean mass", "fat percentage"] },
  { id: "water-intake", slug: "water-intake-calculator", name: "Water Intake Calculator", description: "Daily recommended water hydration target.", category: "health", keywords: ["hydration", "health", "water"] },
  { id: "macro", slug: "macro-calculator", name: "Macro Calculator", description: "Calculate Protein, Carbs, and Fat breakdown for fitness.", category: "health", keywords: ["protein", "carbs", "macros", "nutrition"] },

  // Converters
  { id: "unit", slug: "unit-converter", name: "All-in-One Unit Converter", description: "Universal converter for length, weight, area & volume.", category: "converters", keywords: ["convert", "units", "metric"] },
  { id: "length", slug: "length-converter", name: "Length Converter", description: "Meters, feet, inches, kilometers, and miles.", category: "converters", keywords: ["distance", "height", "meter"] },
  { id: "weight", slug: "weight-converter", name: "Weight Converter", description: "Convert KG, pounds (lbs), grams, ounces, and tons.", category: "converters", keywords: ["mass", "kg", "lbs"] },
  { id: "height", slug: "height-converter", name: "Height Converter", description: "Convert between Feet+Inches and Centimeters (CM).", category: "converters", keywords: ["feet to cm", "cm to feet"] },
  { id: "area", slug: "area-converter", name: "Area Converter", description: "Sq. ft, Sq. meters, Acres, Hectares, and Bigha.", category: "converters", keywords: ["land", "sqft", "acre"] },
  { id: "volume", slug: "volume-converter", name: "Volume Converter", description: "Liters, Gallons, Milliliters, Cubic Meters.", category: "converters", keywords: ["capacity", "liters", "gallons"] },
  { id: "temperature", slug: "temperature-converter", name: "Temperature Converter", description: "Celsius (°C), Fahrenheit (°F), and Kelvin (K).", category: "converters", keywords: ["celsius", "fahrenheit", "weather"] },
  { id: "speed", slug: "speed-converter", name: "Speed Converter", description: "km/h, mph, m/s, knots conversion.", category: "converters", keywords: ["kmph", "velocity"] },
  { id: "time-conv", slug: "time-converter", name: "Time Converter", description: "Seconds, minutes, hours, days, weeks conversion.", category: "converters", keywords: ["hours to mins", "seconds"] },
  { id: "data-storage", slug: "data-storage-converter", name: "Data Storage Converter", description: "KB, MB, GB, TB, and Petabytes calculator.", category: "converters", keywords: ["gigabytes", "terabytes", "bytes"] },
  { id: "feet-to-meter", slug: "feet-to-meter", name: "Feet to Meter Converter", description: "Instant conversion from feet to meters.", category: "converters", keywords: ["ft to m"] },
  { id: "meter-to-feet", slug: "meter-to-feet", name: "Meter to Feet Converter", description: "Instant conversion from meters to feet.", category: "converters", keywords: ["m to ft"] },
  { id: "inch-to-cm", slug: "inch-to-cm", name: "Inch to CM Converter", description: "Convert inches into centimeters accurately.", category: "converters", keywords: ["in to cm"] },
  { id: "cm-to-inch", slug: "cm-to-inch", name: "CM to Inch Converter", description: "Convert centimeters into inches accurately.", category: "converters", keywords: ["cm to in"] },
  { id: "kg-to-pound", slug: "kg-to-pound", name: "KG to Pound Converter", description: "Convert Kilograms (kg) to Pounds (lbs).", category: "converters", keywords: ["kg to lbs"] },
  { id: "pound-to-kg", slug: "pound-to-kg", name: "Pound to KG Converter", description: "Convert Pounds (lbs) to Kilograms (kg).", category: "converters", keywords: ["lbs to kg"] },
  { id: "km-to-miles", slug: "km-to-miles", name: "KM to Miles Converter", description: "Convert Kilometers to Miles.", category: "converters", keywords: ["km to mi"] },
  { id: "miles-to-km", slug: "miles-to-km", name: "Miles to KM Converter", description: "Convert Miles to Kilometers.", category: "converters", keywords: ["mi to km"] },
  { id: "celsius-to-fahrenheit", slug: "celsius-to-fahrenheit", name: "Celsius to Fahrenheit", description: "Convert °C to °F with instant formula.", category: "converters", keywords: ["c to f"] },
  { id: "fahrenheit-to-celsius", slug: "fahrenheit-to-celsius", name: "Fahrenheit to Celsius", description: "Convert °F to °C with instant formula.", category: "converters", keywords: ["f to c"] },

  // Business
  { id: "roas", slug: "roas-calculator", name: "ROAS Calculator", description: "Calculate Return on Ad Spend for marketing campaigns.", category: "business", keywords: ["ad spend", "marketing", "facebook ads"] },
  { id: "break-even", slug: "break-even-calculator", name: "Break-Even Point Calculator", description: "Find units and revenue needed to cover fixed costs.", category: "business", keywords: ["break even", "fixed cost"] },
  { id: "commission", slug: "commission-calculator", name: "Commission Calculator", description: "Calculate sales commissions and tiered incentive structures.", category: "business", keywords: ["sales incentive", "brokerage"] },
  { id: "freelance-rate", slug: "freelance-rate-calculator", name: "Freelance Hourly Rate", description: "Compute target hourly rate based on expenses & billable hours.", category: "business", keywords: ["freelancer", "consulting", "hourly"] },
  { id: "hourly-rate", slug: "hourly-rate-calculator", name: "Hourly to Annual Salary", description: "Convert hourly pay into monthly and yearly wages.", category: "business", keywords: ["wage", "annual salary"] },
  { id: "overtime", slug: "overtime-calculator", name: "Overtime Pay Calculator", description: "Calculate overtime compensation with 1.5x / 2.0x multipliers.", category: "business", keywords: ["ot pay", "overtime"] },
  { id: "salary-hike", slug: "salary-hike-calculator", name: "Salary Hike Calculator", description: "Calculate percentage hike and new appraisal salary.", category: "business", keywords: ["appraisal", "increment", "hike"] },
  { id: "salary-increment", slug: "salary-increment-calculator", name: "Salary Increment Calculator", description: "Project year-on-year wage increments.", category: "business", keywords: ["annual hike", "ctc increase"] },
  { id: "payroll", slug: "payroll-calculator", name: "Payroll Calculator", description: "Calculate employee gross vs net salary deductions.", category: "business", keywords: ["payroll", "epf", "esic"] },
  { id: "invoice", slug: "invoice-calculator", name: "Invoice Total Calculator", description: "Calculate invoice totals with line items, discounts & GST.", category: "business", keywords: ["billing", "tax invoice"] },
  { id: "biz-profit", slug: "business-profit-calculator", name: "Business Profit Calculator", description: "Revenue minus COGS and Operating Expenses.", category: "business", keywords: ["operating profit", "ebit"] },
  { id: "biz-margin", slug: "business-margin-calculator", name: "Business Margin Calculator", description: "Gross, operating, and net margins analyzer.", category: "business", keywords: ["net margin", "operating margin"] },
  { id: "markup-vs-margin", slug: "markup-vs-margin-calculator", name: "Markup vs Margin Calculator", description: "Convert markup percentage to profit margin and vice versa.", category: "business", keywords: ["markup margin diff"] },
  { id: "rent-split", slug: "rent-split-calculator", name: "Rent Split Calculator", description: "Fairly divide room rent based on room size & amenities.", category: "business", keywords: ["flatmates", "roommates", "split bills"] },

  // Education
  { id: "grade", slug: "grade-calculator", name: "Grade Calculator", description: "Calculate weighted final exam and assignment scores.", category: "education", keywords: ["marks", "test score", "percentage"] },
  { id: "gpa", slug: "gpa-calculator", name: "GPA Calculator", description: "Calculate Semester Grade Point Average (4.0 scale).", category: "education", keywords: ["sgpa", "college", "grades"] },
  { id: "cgpa", slug: "cgpa-calculator", name: "CGPA Calculator", description: "Cumulative Grade Point Average across all semesters.", category: "education", keywords: ["university", "cgpa"] },
  { id: "cgpa-to-percentage", slug: "cgpa-to-percentage", name: "CGPA to Percentage (India)", description: "Convert CBSE / AICTE 10-point CGPA into marks percentage.", category: "education", keywords: ["cbse", "multiply 9.5", "aicte"] },
  { id: "percentage-to-cgpa", slug: "percentage-to-cgpa", name: "Percentage to CGPA", description: "Convert percentage score into standard CGPA grade.", category: "education", keywords: ["percent to grade"] },

  // Other
  { id: "fuel-cost", slug: "fuel-cost-calculator", name: "Fuel Cost Calculator", description: "Calculate petrol/diesel trip expenses and cost per km.", category: "other", keywords: ["trip cost", "petrol", "diesel", "mileage"] },
  { id: "mileage", slug: "mileage-calculator", name: "Vehicle Mileage Calculator", description: "Calculate actual fuel economy in km/L or MPG.", category: "other", keywords: ["kmpl", "fuel efficiency"] },
  { id: "electricity-bill", slug: "electricity-bill-calculator", name: "Electricity Bill Calculator", description: "Estimate power bill based on appliance wattages & unit rates.", category: "other", keywords: ["kwh", "power units", "bijli bill"] },
  { id: "tip", slug: "tip-calculator", name: "Tip & Bill Split Calculator", description: "Calculate restaurant tip percentage and per-person share.", category: "other", keywords: ["dining", "bill split", "restaurant"] },
  { id: "savings", slug: "savings-calculator", name: "Savings Calculator", description: "Track compound interest growth on monthly deposits.", category: "other", keywords: ["piggy bank", "wealth builder"] },
  { id: "countdown", slug: "countdown-calculator", name: "Date Countdown Calculator", description: "Live days, hours, and minutes until your big event.", category: "other", keywords: ["event timer", "days left"] },
  { id: "fraction", slug: "fraction-calculator", name: "Fraction Calculator", description: "Add, subtract, multiply, and simplify fractions.", category: "other", keywords: ["mixed fractions", "math simplify"] },
  { id: "scientific", slug: "scientific-calculator", name: "Scientific Calculator", description: "Trigonometric, logarithmic, and power calculations.", category: "other", keywords: ["sin cos tan", "log", "sqrt"] },
];
