import React from "react";
import Link from "next/link";
import { Metadata } from "next";
import { AlertCircle, Landmark, HeartPulse, Scale, ShieldAlert } from "lucide-react";

export const metadata: Metadata = {
  title: "Calculation Methodology & Legal Disclaimer | MyCalculators",
  description: "Comprehensive legal disclaimer regarding financial, tax, health, and mathematical calculation estimates on MyCalculators.",
  alternates: {
    canonical: "https://mycalculators.xyz/disclaimer",
  },
};

export default function DisclaimerPage() {
  return (
    <main className="max-w-4xl mx-auto px-4 sm:px-6 py-10 space-y-8">
      {/* Breadcrumb */}
      <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs font-semibold text-navy/60">
        <Link href="/" className="hover:text-navy transition-colors">Home</Link>
        <span>/</span>
        <span className="text-navy">Disclaimer</span>
      </nav>

      {/* Header */}
      <div>
        <h1 className="text-3xl sm:text-4xl font-black text-navy tracking-tight mb-2">
          Calculation Methodology & Legal Disclaimer
        </h1>
        <p className="text-xs sm:text-sm text-navy/60">
          Last Reviewed: August 2026 | mycalculators.xyz
        </p>
      </div>

      <div className="bg-amber-500/10 border border-amber-500/25 rounded-3xl p-6 sm:p-8 space-y-6 text-xs sm:text-sm text-navy/85 leading-relaxed shadow-sm">
        <section className="space-y-2">
          <h2 className="text-base sm:text-lg font-bold text-navy flex items-center gap-2">
            <Landmark className="w-5 h-5 text-amber-700" /> 1. Financial & Banking Calculators Disclaimer
          </h2>
          <p>
            Calculations generated by our <strong>EMI, Home Loan, LTV, SIP, Mutual Funds, and Fixed Deposit tools</strong> are mathematical projections based on constant interest compounding and standard reducing balance formulas. Actual loan approvals, interest charges, amortization tenures, processing fees, and investment returns depend entirely on individual commercial bank policies, credit ratings, and market performance.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base sm:text-lg font-bold text-navy flex items-center gap-2">
            <Scale className="w-5 h-5 text-amber-700" /> 2. Tax & Statutory Provisions (GST, Income Tax, TDS)
          </h2>
          <p>
            Tax estimates reflect configured statutory rules (including <strong>AY 2026-27</strong> standard deductions and Section 87A rebate provisions). Tax laws, cess rates, and exemptions are subject to periodic legislative amendments by the Ministry of Finance and Central Board of Direct Taxes (CBDT). These estimates do not replace professional advice from a qualified Chartered Accountant (CA).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base sm:text-lg font-bold text-navy flex items-center gap-2">
            <HeartPulse className="w-5 h-5 text-amber-700" /> 3. Health & Biometric Estimates
          </h2>
          <p>
            Tools such as the <strong>BMI Calculator, BMR Calculator, Calorie Needs, and Body Fat Estimator</strong> use standardized demographic formulas (Mifflin-St Jeor, US Navy circumference method, Devine formula). These numbers are informational reference points and must not be used as clinical medical diagnoses, prescription advice, or treatment plans.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base sm:text-lg font-bold text-navy flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-amber-700" /> 4. Direct Support & Communication
          </h2>
          <p>
            If you notice a formula anomaly or wish to clarify a calculation assumption, contact our desk at{" "}
            <a href="mailto:mantupatra23@gmail.com" className="text-steel font-bold underline">
              mantupatra23@gmail.com
            </a>.
          </p>
        </section>
      </div>
    </main>
  );
}
